= Verwaltung

Hier befindet sich die Mehrheit der Konfigurationsparameter. Obwohl viele standardmäßig vorkonfiguriert sind.

La page est accessible par Administration -> Configuration : 


[IMPORTANT]
Wenn sie nicht im Experten-Modus sind, sind möglicherweise einige Parameter nicht sichtbar.

== Générale

Diese Registerkarte enthält allgemeine Informationen zu Jeedom : 

* *Name von Ihrem Jeedom* : kann in den Szenarien wieder verwendet werden oder zum identifizieren eines Backups
* *API Schlüssel* : Ihr API-Schlüssel, wird verwendet für jede Anfrage zur Jeedom-API  
* *Clef API Pro* : utilisée pour communiquer avec le système de gestion de parc
* *Installationsschlüssel* : Hardware-Schlüssel von Ihrem Jeedom auf dem Markt. Wenn Ihr Jeedom nicht in der Liste Ihrer Jeedom auf dem Markt erscheint, ist es ratsam auf diese Schaltfläche zu klicken
* *Sprache* : Ihre Sprache in Jeedom
* *Cache Verfallszeit (Stunde)* : Lebensdauer der PHP-Sitzungen es wird er geraten, dort nicht zu ändern
* *Datum und Uhrzeit* : Ihre Zeitzone
* *Zeitserver optional* : fügt einen optionalen Zeitserver hinzu (für Experten reserviert)
* *Die Überprüfung der Zeit ignorieren* : Weist Jeedom an, nicht zu überprüfen, ob die Zeit übereinstimmt. Nützlich zum Beispiel, wenn Sie Jeedom nicht an das Internet angeschlossen haben und es keine RTC-Batterie hat.

== API

Liste les differentes clef API de Jeedom : 

* le core à 2 clef API, une general (autant que possibile il faut eviter de l'utiliser) et pour les Pro (utilisée pour la gestion de parc)
* et une clef api par plugin en ayant besoin

Pour chaque clef API vous pouvez definir la porté : 

* *Désactiver* : la clef api ne peut etre utilisée
* *IP blanche* : seule une liste d'ip est autorisé (voir configuration réseaux)
* *Localhost* : seules les requetes venant du systeme lui meme sont autorisé
* *Activé* : aucune restriction

De plus vous pouvez aussi limité l'accès (par le meme systeme) aux APIs HTTP, JsonRpc et TTS

== OS/DB
 
=== Système

Permet d'accès à une interface d'administration systeme, sorte de console shell  (ATTENTION en touchant à cela le support peut refuser de vous aider)

=== Base de données

* *Administration* : permet d'accèder à une interface d'administration de la base en ligne de commande (ATTENTION en touchant à cela le support peut refuser de vous aider)
* *Geräte (hostname)* : Datenbank Standort
* *Benutzer* : von Jeedom verwendeter Benutzername
* *Passwort* : Passwort für den Zugriff auf die Datenbank von Jeedom 

== Sécurité

=== LDAP

* *LDAP-Authentifizierung aktivieren* : aktiviert die Authentifizierung über AD (LDAP)
* *Host* : Server-Host des AD
* *Domaine* : Ihr AD-Domaine
* *Basis-DN* : Basis-DN ihres AD
* *Benutzername* : Benutzernamen für die Verbindung von Jeedom mit dem AD
* *Passwort* : Passwort für die Verbindung von Jeedom mit dem AD
 * *Filter (optional)* : Filter auf dem AD (zum Beispiel für Gruppenmanagement)
* *REMOTE_USER zulassen* : REMOTE_USER aktivieren (zum Beispiel verwendet  in SSO)

=== Connexion

* *Nombre d'échec toléré* : defini le nombre de tentative successivent autorisées avant de bannir l'IP
* *Temps maximum entre les échecs (s)* : temps maximum pour que 2 tentatives soient considéré comme successive
* *Durée du bannissement (s), -1 pour infini* : temps de banissement de l'IP
* *IP "blanche"* : liste d'IP qui ne peuvent jamais etre banni

En dessous vous avez un tableau qui donne la liste des IP bannis

== Netzwerkkonfiguration

Das ist ein sehr wichtiger Teil in Jeedom, man muss ihn unbedingt richtig konfigurieren, andernfalls können viele Plugins nicht richtig funktionieren.

* *Interner Zugriff* : Daten, zum verbinden von Jeedom mit einem anderen Gerät in demselben Netzwerk
* *Protokolle* : Das zu verwendende Protokoll, meistens HTTP
** *URL oder IP Adresse* : Die Jeedom IP-Adresse eintragen
** *Complément (exemple : /jeedom)* : le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
** *Port* : Der Port, im allgemeinen 80. Achtung, den Port hier zu ändern, ändert tatsächlich nicht den Jeedom Port, der wird derselbe bleiben
** *Status* : Zeigt an, ob die interne Netzwerkkonfiguration korrekt ist
* *Externer Zugriff* : Daten, um Jeedom von einem Externen Gerät zu verbinden. Nur ausfüllen wenn sie kein Jeedom DNS verwenden.
** *Protokolle* : verwendetes Protokoll für den Zugriff von außen 
** *URL oder IP Adresse* : wenn eine externe Adresse oder IP fest sein soll
** *Complément (exemple : /jeedom)* :  le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
* *Gestion avancée* : peut ne pas apparaitre en fonction de la compatibilité avec votre matériel. Vous aurez ici la liste de vos interface réseaux
** *Deaktivieren der Jeedom Netzwerkverwaltung* : gibt an ob Jeedom das Netzwerk überwachen soll  (ist zu Aktivieren, wenn Jeedom mit einem Netzwerk verbunden ist)
* *Markt Proxy* : erlaubt einen entfernten Zugang zu Ihrem Jeedom ohne ein DNS, eine feste IP oder offene Ports auf Ihrem System
** *Die Jeedom DNS benutzen* : aktive Jeedom DNS (Achtung, das erfordert mindestens ein Servicepack)
** *DNS Status* : der DNS-http-Status
** *Verwaltung* : ermöglicht das Beenden und Neustarten des DNS Dienstes

[TIP]
Wenn Sie den HTTPS-Port haben, ist der Port 443 (Standard) und der HTTP-Port ist standardmäßig 80

[IMPORTANT]
Cette partie est juste là pour expliquer à Jeedom son environnement : une modification du port ou de l'IP ici ne changera pas le port ou l'IP de Jeedom. Pour cela il faut se connecter en SSH et éditer le fichier /etc/network/interfaces pour l'IP et les fichiers etc/nginx/sites-available/default et etc/nginx/sites-available/default_ssl (pour le HTTPS). En cas de mauvaise manipulation de votre Jeedom, l'équipe Jeedom ne pourra être tenue pour responsable et pourra refuser toute demande de support.

[NOTE]
Sie können link:http://blog.domadoo.fr/2014/10/15/acceder-depuis-lexterieur-jeedom-en-https[hier] eine Tutoriel sehen, wie ein selbst signiertes HTTPS Zertifikat eingerichtet wird

[IMPORTANT]
Wenn Sie die DNS-Jeedom betreiben können, betrachten Sie die Konfiguration der Firewall und Kindersicherung Filter von der Box (Livebox sollte z. B. die Firewall in der Mittelstellung sein)

== Couleurs

Die farbliche Kennzeichnung der Widgets erfolgt entsprechend der Kategorie des Widgets, die in der Konfiguration der einzelnen Module definiert ist (siehe Plugin Z-Wave, RFXCOM... etc.). Die Kategorien umfassen Heizung, Licht, Automation etc....  

Für jede Kategorie, können wir eine andere Farbe zwischen der Desktop-Version und Mobile-Version wählen. Außerdem gibt es zwei Arten von Farben, Widget Hintergrundfarben  und Befehls Farbe, wenn das Widget erfolgt schrittweise Typ, zB Beleuchtung, Jalousien, Temperaturen.

En cliquant sur la couleur une fenêtre s'ouvre, permettant de choisir sa couleur.

Sie können auch hier die Transparenz der Widgets allgemein konfigurieren (das wird die Standardvorgabe sein, es ist danach möglich, diesen Wert der Widget zu ändern

[TIP]
Vergessen Sie nicht, nach jeder Veränderung zu speichern.

== Commandes

* *Chronik* : siehe link:https://jeedom.com/doc/documentation/core/fr_FR/doc-core-history.html#_configuration_général_de_l_historique[hier]
* *drücken*
** *Globale Push URL* : Erlaubt eine URL hinzuzufügen, die bei Aktualisierung eines Befehls aufzurufen ist. Sie können die folgenden Tags benutzen :  \#value# für den Wert des Befehls, \#cmd_name# für den Namen des Befehls, \#cmd_id# für die eindeutige Kennung des Befehls, \#humanname# für den vollständigen Namen des Befehls (z.B. \#[Bad][Hydrometrie][Feuchtigkeit]#)

== Cache

Permet de surveiller et d'agir sur le cache de Jeedom : 

* *Statistiques* : Nombre d'objet actuellement en cache
* *Nettoyer le cache* : Force la suppression des objets qui ne sont plus utile (Jeedom le fait automatiquement toute les nuits)
* *Vider toutes les données en cache* : Vide completement le cache (attention cela peut faire perdre des données)
* *Temps de pause pour le long polling* : Fréquence a laquelle Jeedom verifie si il y a des evenements en attente pour les clients (interface web, application mobile...). Plus ce temps est cours plus l'interface se mettra à jour rapidement, en contre partie cela utilise plus de ressources et peut donc ralentir jeedom

== Interactions

Voir link:doc-core-interact.html#_configuration_2[ici]

== Rapports

Permet de configuration la generation et la gestion des raports

* *Delai d'attente après génération de la page (en ms)* : Délai d'attente après chargement du rapport pour faire la "photo", à changer si votre rapport est incomplet par exemple
* *Nettoyer les rapport plus anciens de (jours)* : défini le nombre de jour avant de supprimer un rapport (les rapports prennent un peu de place donc attention à ne pas mettre trop de conservation)

== Liens

Permet de configurer le graphique de lien

* *Profondeur pour les scénarios* : Permet de définir, lors de l'affichage d'un graphique de lien d'un scénario, le nombre d'élément maximum à afficher (plus il y a d'élément plus le graphique sera lent à générer et plus il sera difficile à lire)
* *Profondeur pour les objets* : idem pour les objets
* *Profondeur pour les équipements* : idem pour les équipements
* *Profondeur pour les commandes* : idem pour les commandes
* *Profondeur pour les variables* : idem pour les variables
* *Paramètre de prerender* : permet d'agir sur la disposition du graph
* *Paramètre de render* : idem

== Résumés

Permet d'ajouter des résumés d'objet (information affiché tout en haut dans la barre de menu Jeedom ou a coté des objets) : 

* *Clef* : clef du résumé, a ne surtout pas toucher
* *Nom* : Nom du résumé
* *Calcul* : Méthode de calcul, peut etre de type 
** *Somme* : somme les differentes valeur
** *Moyenne* : fait la moyenne des valeurs
** *Texte* : afficher textuellement la valeur (surtout pour celle de type chaine de caractere)
* *Icone* : icone du résumé
* *Unité* : unité du résumé
* *Méthode de comptage* : si vous compté une donnée binaire alors il faut mettre cette valeur a binaire, exemple si vous comptez ne nombre de lampe allumées mais que vous avez juste la valeur du variateur (0 à 100), alors il faut mettre binaire, comme cela jeedom considera que si la valeur est >1 alors Jeedom considera la lampe allumée 
* *Affiché si valeur égale 0* : masquer la valeur si elle vos 0 
* *Liée à un virtuel* : lance la création de commande virtuel ayant pour valeur celle du résumé

== Logs

Voir link:doc-core-log.html#_configuration[ici]

== Equipements

* *Anzahl der Fehler vor dem Deaktivieren der Geräte* : Anzahl von Kommunikationsausfällen der Geräte bevor sie Deaktiviert werden (eine Nachricht wird Sie warnen, wenn dies geschieht)
* *Batterien Schwellenwerte* : erlaubt, die globalen Alarmschwellen für die Batterien zu verwalten

== Update und Dateien

* *Source de mise à jour* : choisir la source de mise à jour du core de jeedom
* *Version du core* : version du core à récuperer
* *Faire une sauvegarde avant la mise à jour* : indique si il faut faire une sauvegarde avant la mise à jour
* *Vérifier automatiquement s'il y a des mises à jour* : indique si il faut chercher automatiquement si il y a de nouvelle mise à jour (attention pour eviter de faire tomber le market l'heure de verification peut changer)

=== Das Depot

Das Depot ist ein Internet-Speicherplatz (und Service), um Backups zu speichern, Plugins wiederherzustellen, den Jeedom Core wiederherstellen zu können….

==== Dateien

Depot aktivieren, zum versenden von Plugins als Dateien.

==== Github

Depot, das dazu dient, Jeedom mit Github zu verbinden

* *Token* : Token für den Zugriff auf den privaten Aufbewahrungsort
* *Utilisateur ou organisation du dépôt pour le core Jeedom* : nom de l'utilisateur ou de l'organisation sur github pour le core
* *Nom du dépôt pour le core Jeedom* : nom du dépot pour le core
* *Branche pour le core Jeedom* : branche du dépot pour le core

==== Markt

Aufbewahrungsort, der dazu dient, Jeedom mit dem Markt zu verbinden, es wird sehr geraten, diesen Ort zu benutzen. Achtung, es kann jede Supportanfrage abgelehnt werden, wenn Sie einen anderen Aufbewahrungsort wie diesen benutzt.

* *Adresse* : Markt Adresse
* *Benutzername* : Ihr Benutzername auf dem Markt
* *Passwort* : Ihr Passwort auf dem Markt

==== Samba

Dépôt permettant d'envoyer automatiquement un backup de Jeedom sur un partage Samba (ex NAS Synology).

* *[Backup] IP* : IP des Samba Servers
* *[Backup] Benutzer* : Benutzernamen für die Verbindung (anonyme Verbindungen sind nicht möglich)
* * L'utilisateur doit forcement avoir les droits lecture/ecriture sur ce repertoire
* *[Backup] Passwort* : Benutzerpasswort
* *[Backup] Partage* : chemin du partage (attention à bien s'arrêter au niveau du partage)
* *[Backup] Chemin* : chemin dans le partage (à mettre en relatif), celui-ci doit exister

[NOTE]
Si le chemin d'accès à votre dossier de sauvegarde samba est : \\192.168.0.1\Sauvegardes\Domotique\Jeedom
Alors IP = 192.168.0.1 , Partage = //192.168.0.1/Sauvegardes , Chemin = Domotique/Jeedom

[NOTE]
Lors de la validation du partage samba, tel que décrit précédement, une nouvelle forme de sauvegarde apparait dans l'onglet
backup de jeedom. En l'activant, jeedom procedera à son envoi automatique lors du prochain backup. Un test est possible en
effectuant un backup manuel. Le log devra donc ressembler à ceci :

[IMPORTANT]
Es wir notwendig sein, das sie das smbclient Software-Paket installieren, damit das Depot funktioniert

[IMPORTANT]
Jeedom doit être le seul à écrire dans ce dossier et il doit être vide par défaut (c'est à dire avant la configuration et l'envoi du premier backup, le dossier ne doit contenir aucun fichier ou dossier).

==== URL

* *URL Jeedom Kern*
* *URL Jeedom Kern Version*