= Verwaltung

Hier befindet sich die Mehrheit der Konfigurationsparameter. Obwohl viele standardmäßig vorkonfiguriert sind.

La page est accessible par Administration -> Configuration : 


[IMPORTANT]
Wenn sie nicht im Experten-Modus sind, sind möglicherweise einige Parameter nicht sichtbar.

== Générale

Diese Registerkarte enthält allgemeine Informationen zu Jeedom : 

* *Name von Ihrem Jeedom* : kann in den Szenarien wieder verwendet werden oder zum identifizieren eines Backups
* *Système* : Type hardware du systeme sur lequelle est installé jeedom
* *Clef d'installation* : clef hardware de votre Jeedom sur le market. Si votre Jeedom n'apparaît pas dans la liste de vos Jeedom sur le market il est conseillé de cliquer sur le bouton *Remise à zéro*
* *Sprache* : Ihre Sprache in Jeedom
* *Générer les traductions* : permet de générer les traductions, attention peut ralentir votre système
* *Cache Verfallszeit (Stunde)* : Lebensdauer der PHP-Sitzungen es wird er geraten, dort nicht zu ändern
* *Datum und Uhrzeit* : Ihre Zeitzone
* *Zeitserver optional* : fügt einen optionalen Zeitserver hinzu (für Experten reserviert)
* *Die Überprüfung der Zeit ignorieren* : Weist Jeedom an, nicht zu überprüfen, ob die Zeit übereinstimmt. Nützlich zum Beispiel, wenn Sie Jeedom nicht an das Internet angeschlossen haben und es keine RTC-Batterie hat.

== API

Liste les differentes clef API de Jeedom : 

* le core à 2 clef API, une general (autant que possibile il faut eviter de l'utiliser) et pour les Pro (utilisée pour la gestion de parc)
* et une clef api par plugin en ayant besoin

Pour chaque clef API vous pouvez definir la porté : 

* *Désactiver* : la clef api ne peut etre utilisée
* *IP blanche* : seule une liste d'ip est autorisé (voir configuration réseaux)
* *Localhost* : seules les requetes venant du systeme lui meme sont autorisé
* *Activé* : aucune restriction

De plus vous pouvez aussi limiter l'accès (par le même système) aux APIs HTTP, JsonRpc et TTS

== OS/DB
 
=== Système

Permet d'accès à une interface d'administration systeme, sorte de console shell  (ATTENTION en touchant à cela le support peut refuser de vous aider)

=== Base de données

* *Administration* : permet d'accèder à une interface d'administration de la base en ligne de commande (ATTENTION en touchant à cela le support peut refuser de vous aider)
* *Geräte (hostname)* : Datenbank Standort
* *Benutzer* : von Jeedom verwendeter Benutzername
* *Passwort* : Passwort für den Zugriff auf die Datenbank von Jeedom 

== Sécurité

=== LDAP

* *LDAP-Authentifizierung aktivieren* : aktiviert die Authentifizierung über AD (LDAP)
* *Host* : Server-Host des AD
* *Domaine* : Ihr AD-Domaine
* *Basis-DN* : Basis-DN ihres AD
* *Benutzername* : Benutzernamen für die Verbindung von Jeedom mit dem AD
* *Passwort* : Passwort für die Verbindung von Jeedom mit dem AD
 * *Filter (optional)* : Filter auf dem AD (zum Beispiel für Gruppenmanagement)
* *REMOTE_USER zulassen* : REMOTE_USER aktivieren (zum Beispiel verwendet  in SSO)

=== Connexion

* *Nombre d'échec toléré* : defini le nombre de tentative successivent autorisées avant de bannir l'IP
* *Temps maximum entre les échecs (s)* : temps maximum pour que 2 tentatives soient considéré comme successive
* *Durée du bannissement (s), -1 pour infini* : temps de banissement de l'IP
* *IP "blanche"* : liste d'IP qui ne peuvent jamais etre banni

En dessous vous avez un tableau qui donne la liste des IP bannis

== Netzwerkkonfiguration

Das ist ein sehr wichtiger Teil in Jeedom, man muss ihn unbedingt richtig konfigurieren, andernfalls können viele Plugins nicht richtig funktionieren.

* *Interner Zugriff* : Daten, zum verbinden von Jeedom mit einem anderen Gerät in demselben Netzwerk
* *Protokolle* : Das zu verwendende Protokoll, meistens HTTP
** *URL oder IP Adresse* : Die Jeedom IP-Adresse eintragen
** *Complément (exemple : /jeedom)* : le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
** *Port* : Der Port, im allgemeinen 80. Achtung, den Port hier zu ändern, ändert tatsächlich nicht den Jeedom Port, der wird derselbe bleiben
** *Status* : Zeigt an, ob die interne Netzwerkkonfiguration korrekt ist
* *Externer Zugriff* : Daten, um Jeedom von einem Externen Gerät zu verbinden. Nur ausfüllen wenn sie kein Jeedom DNS verwenden.
** *Protokolle* : verwendetes Protokoll für den Zugriff von außen 
** *URL oder IP Adresse* : wenn eine externe Adresse oder IP fest sein soll
** *Complément (exemple : /jeedom)* :  le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
* *Gestion avancée* : peut ne pas apparaitre en fonction de la compatibilité avec votre matériel. Vous aurez ici la liste de vos interface réseaux
** *Deaktivieren der Jeedom Netzwerkverwaltung* : gibt an ob Jeedom das Netzwerk überwachen soll  (ist zu Aktivieren, wenn Jeedom mit einem Netzwerk verbunden ist)
* *Markt Proxy* : erlaubt einen entfernten Zugang zu Ihrem Jeedom ohne ein DNS, eine feste IP oder offene Ports auf Ihrem System
** *Die Jeedom DNS benutzen* : aktive Jeedom DNS (Achtung, das erfordert mindestens ein Servicepack)
** *DNS Status* : der DNS-http-Status
** *Verwaltung* : ermöglicht das Beenden und Neustarten des DNS Dienstes

[TIP]
Wenn Sie den HTTPS-Port haben, ist der Port 443 (Standard) und der HTTP-Port ist standardmäßig 80

[IMPORTANT]
Cette partie est juste là pour expliquer à Jeedom son environnement : une modification du port ou de l'IP ici ne changera pas le port ou l'IP de Jeedom. Pour cela il faut se connecter en SSH et éditer le fichier /etc/network/interfaces pour l'IP et les fichiers etc/nginx/sites-available/default et etc/nginx/sites-available/default_ssl (pour le HTTPS). En cas de mauvaise manipulation de votre Jeedom, l'équipe Jeedom ne pourra être tenue pour responsable et pourra refuser toute demande de support.

[NOTE]
Sie können link:http://blog.domadoo.fr/2014/10/15/acceder-depuis-lexterieur-jeedom-en-https[hier] eine Tutoriel sehen, wie ein selbst signiertes HTTPS Zertifikat eingerichtet wird

[IMPORTANT]
Wenn Sie die DNS-Jeedom betreiben können, betrachten Sie die Konfiguration der Firewall und Kindersicherung Filter von der Box (Livebox sollte z. B. die Firewall in der Mittelstellung sein)

== Couleurs

Die farbliche Kennzeichnung der Widgets erfolgt entsprechend der Kategorie des Widgets, die in der Konfiguration der einzelnen Module definiert ist (siehe Plugin Z-Wave, RFXCOM... etc.). Die Kategorien umfassen Heizung, Licht, Automation etc....  

Für jede Kategorie, können wir eine andere Farbe zwischen der Desktop-Version und Mobile-Version wählen. Außerdem gibt es zwei Arten von Farben, Widget Hintergrundfarben  und Befehls Farbe, wenn das Widget erfolgt schrittweise Typ, zB Beleuchtung, Jalousien, Temperaturen.

En cliquant sur la couleur une fenêtre s'ouvre, permettant de choisir sa couleur.

Sie können auch hier die Transparenz der Widgets allgemein konfigurieren (das wird die Standardvorgabe sein, es ist danach möglich, diesen Wert der Widget zu ändern

[TIP]
Vergessen Sie nicht, nach jeder Veränderung zu speichern.

== Commandes

=== Historique

* *Afficher les statistiques sur les widgets* : permet d'afficher ou non les statistiques sur les widgets ; il faut que le widget soit compatible, ce qui est le cas pour la plupart ; il faut aussi que la commande soit de type numérique
* *Période de calcul pour min, max, moyenne (en heures)* : période de calcul des statistiques (par défaut 24h), il n'est pas possible de mettre moins d'une heure
* *Période de calcul pour la tendance (en heures)* : période de calcul des tendances (par défaut 2h), il n'est pas possible de mettre moins d'une heure
* *Délai avant archivage (en heures)* : donne le délai avant archivage, par défaut la valeur est de 24h, c'est-à-dire que les données historisées doivent avoir plus de 24h pour être archivées (pour rappel, l'archivage va soit moyenner, soit prendre le maximum ou le minimum de la donnée sur une période qui correspond à la taille des paquets)
* *Archiver par paquet de (en heures)* : ce paramètre donne justement la taille des paquets, par defaut 1h ; cela signifie que Jeedom va prendre des périodes de 1h, moyenner (par exemple, suivant le réglage de la commande) et stocker cette nouvelle valeur (en supprimant les valeurs moyennées).
* *Seuil de calcul de tendance basse* : cette valeur correspond au seuil de tendance basse (Jeedom indique que la valeur est en baisse), il doit être négatif (par défaut -0.1).
* *Seuil de calcul de tendance haut* : idem mais à la tendance haute.
* *Période d'affichage des graphiques par defaut* : pour des questions de performance lors de l'affichage à la volée (en cliquant sur le widget ou par la page historique) Jeedom n'affiche qu'une période restreinte de l'historique (cela permet un affichage plus rapide) ; il est ici possible de régler cette valeur.

[NOTE]
Il est possible d'activer sur les widgets l'affichage du minimum, de la moyenne, du maximum et de la tendance (par défaut ceci est désactivé car cela a une tendance à allonger le temps d'affichage du dashboard à cause des calculs). Si vous activez cette option, par défaut, Jeedom se fonde sur les données des dernières 24h pour calculer ces statistiques. Les tendances sont par défaut calculées sur 2h. Ce paramètre est bien sûr modifiable (voir plus bas).La méthode de calcul de tendance est fondée sur le calcul des moindres carrés (voir https://fr.wikipedia.org/wiki/M%C3%A9thode_des_moindres_carr%C3%A9s[ici] pour le détail).

=== Push

** *Globale Push URL* : Erlaubt eine URL hinzuzufügen, die bei Aktualisierung eines Befehls aufzurufen ist. Sie können die folgenden Tags benutzen :  \#value# für den Wert des Befehls, \#cmd_name# für den Namen des Befehls, \#cmd_id# für die eindeutige Kennung des Befehls, \#humanname# für den vollständigen Namen des Befehls (z.B. \#[Bad][Hydrometrie][Feuchtigkeit]#)

== Cache

Permet de surveiller et d'agir sur le cache de Jeedom : 

* *Statistiques* : Nombre d'objet actuellement en cache
* *Nettoyer le cache* : Force la suppression des objets qui ne sont plus utile (Jeedom le fait automatiquement toute les nuits)
* *Vider toutes les données en cache* : Vide completement le cache (attention cela peut faire perdre des données)
* *Temps de pause pour le long polling* : Fréquence a laquelle Jeedom verifie si il y a des evenements en attente pour les clients (interface web, application mobile...). Plus ce temps est cours plus l'interface se mettra à jour rapidement, en contre partie cela utilise plus de ressources et peut donc ralentir jeedom

== Interactions

=== Général

Vous avez ici 3 paramètres : 

* *Sensibilité* : il y a 4 niveaux de correspondance (La sensibilité va de 1 (correspond exactement) à 99)
** pour 1 mot : le niveau de correspondance pour les interactions à un seul mot
** 2 mots : le niveau de correspondance pour les interactions à deux mots
** 3 mots : le niveau de correspondance pour les interactions à trois mots
** + de 3 mots : le niveau de correspondance pour les interactions à plus de trois mots
* *Ne pas répondre si l'interaction n'est pas comprise* : par défaut Jeedom répond "je n'ai pas compris" si l'interaction n'est pas comprise. Il est possible de désactiver ce fonctionnement pour que Jeedom ne réponde rien, mettre le bouton à oui pour désactiver la réponse.
* *Regex général d'exclusion pour les interactions* : permet de définir une regexp qui, si elle correspond à une interaction, supprimera automatiquement cette phrase de la génération (réservé aux experts). Pour plus d'infos voir les explications dans le chapitre *"Regexp d'exclusion"*

=== Interaction automatique, contextuelle & avertissement

Les interactions automatique permettent a Jeedom de tenter de comprendre la commande meme si il n'y a pas d'interaction definie (il va chercher un nom d'objet et/ou d'équipement et/ou de commande pour essayer de répondre le mieux possible)

Les interactions contextuelle vous permette d'enchainer plusieurs demande sans tout repeter, jeedom gardant le contexte, exemple : 

* Vous : Combien fait-il dans la chambre ?
* Jeedom : Température 25.2 °C
* Vous : et dans le salon ?
* Jeedom : Température 27.2 °C

Il est aussi possible de poser 2 questions en une : 

* Vous : Combien fait-il dans la chambre et dans le salon ?
* Jeedom : Température 27.2 °C
		   Température 27.2 °C

Les intéractions de type prévient moi permette de demander à Jeedom de vous prevenir si une commande dépasse/descend ou vaut une certaine valeur. Ex :

* Vous : Préviens moi si la température du salon dépasse 25°C ?
* Jeedom : OK

Dès que la température du salon dépassera 25°C jeedom vous le dira (une seule fois)

[NOTE]
Par defaut Jeedom vous répondra par le meme canal que celui que vous avez utilisé pour lui demander de vous prévenir. Si il n'en trouve pas alors il utilisera la commande par defaut spécifié dans la configuration

* *Activer les interactions automatique* : active les interactions automatique
* *Activer les réponses contextuelle* : active les interactions contextuelle
* *Réponse contextuelle prioritaire si la phrase commence par* : si la phrase commence par le mot en question alors Jeedom va prioritiser une réponse contextuelle (vous pouvez mettre plusieurs mot en les séparant par des ;)
* *Découper une interaction en 2 si elle contient* : idem mais pour le découpage d'une interaction contenant plusieurs question
* *Réponse de type "previens moi" si la phrase commence par* : si la phrase commence par ce/ces mots alors Jeedom cherchera pour faire une interaction de type préviens moi (vous pouvez mettre plusieurs mot en les séparant par des ;)
* *Commande de retour par défaut* : commande de retour par defaut pour une interaction de type préviens (utilisé notament si vous avez programé l'alerte par l'interface mobile)
* *Synonyme pour les objets* : liste des synomnyme pour les objets (ex : rdc|rez de chaussé|sous sol|bas;sdb|salle de bain)
* *Synonyme pour les équipements* : liste des synomnyme pour les équipements
* *Synonyme pour les commandes* : liste des synomnyme pour les commandes
* *Synonyme pour les résumé* : liste des synomnyme pour les résumés

=== Couleurs

Cette partie permet de definir les couleurs pour le pilotage des bandeaux de LED par exemple (pour que Jeedom comprenne les couleurs type rouge/bleu/noir...)

== Rapports

Permet de configuration la generation et la gestion des raports

* *Delai d'attente après génération de la page (en ms)* : Délai d'attente après chargement du rapport pour faire la "photo", à changer si votre rapport est incomplet par exemple
* *Nettoyer les rapport plus anciens de (jours)* : défini le nombre de jour avant de supprimer un rapport (les rapports prennent un peu de place donc attention à ne pas mettre trop de conservation)

== Liens

Permet de configurer le graphique de lien

* *Profondeur pour les scénarios* : Permet de définir, lors de l'affichage d'un graphique de lien d'un scénario, le nombre d'élément maximum à afficher (plus il y a d'élément plus le graphique sera lent à générer et plus il sera difficile à lire)
* *Profondeur pour les objets* : idem pour les objets
* *Profondeur pour les équipements* : idem pour les équipements
* *Profondeur pour les commandes* : idem pour les commandes
* *Profondeur pour les variables* : idem pour les variables
* *Paramètre de prerender* : permet d'agir sur la disposition du graph
* *Paramètre de render* : idem

== Résumés

Permet d'ajouter des résumés d'objet (information affiché tout en haut dans la barre de menu Jeedom ou a coté des objets) : 

* *Clef* : clef du résumé, a ne surtout pas toucher
* *Nom* : Nom du résumé
* *Calcul* : Méthode de calcul, peut etre de type 
** *Somme* : somme les differentes valeur
** *Moyenne* : fait la moyenne des valeurs
** *Texte* : afficher textuellement la valeur (surtout pour celle de type chaine de caractere)
* *Icone* : icone du résumé
* *Unité* : unité du résumé
* *Méthode de comptage* : si vous compté une donnée binaire alors il faut mettre cette valeur a binaire, exemple si vous comptez ne nombre de lampe allumées mais que vous avez juste la valeur du variateur (0 à 100), alors il faut mettre binaire, comme cela jeedom considera que si la valeur est >1 alors Jeedom considera la lampe allumée 
* *Affiché si valeur égale 0* : masquer la valeur si elle vos 0 
* *Liée à un virtuel* : lance la création de commande virtuel ayant pour valeur celle du résumé

== Logs

Vous avez ici les options suivantes :

* *Message*
** *Ajouter un message à chaque erreur dans les logs* : si un plugin ou Jeedom écrit un message d'erreur dans un log, Jeedom ajoute automatiquement un message dans le centre des messages (au moins vous êtes sûr de ne pas le manquer)
** *Commande d'information utilisateur* : permet de sélectionner une ou plusieurs commandes (à séparer par des &&) de type message qui seront utilisées lors de nouveaux messages (permet d'être tout de suite prévenu)
* *Alertes*
** *Ajouter un message à chaque Timeout* : ajoute un message dans le centre de message si un équipement tombe en timeout
** *Commande sur Timeout* : commande de type message à utiliser si un équipement est en timeout
** *Ajouter un message à chaque Batterie en Warning* : ajoute un message dans le centre de message si un équipement à son niveau de batterie en warning
** *Commande sur Batterie en Warning* : commande de type message à utiliser si un équipement à son niveau de batterie en warning
** *Ajouter un message à chaque Batterie en Danger* : ajoute un message dans le centre de message si un équipement à son niveau de betterie en danger
** *Commande sur Batterie en Danger* : commande de type message à utiliser si un équipement à son niveau de betterie en danger
** *Ajouter un message à chaque Warning* : ajoute un message dans le centre de message si une commande passe en alerte warning
** *Commande sur Warning* : commande de type message à utiliser si une commande passe en alerte warning
** *Ajouter un message à chaque Danger* : ajoute un message dans le centre de message si une commande passe en alerte danger
** *Commande sur Danger* : commande de type message à utiliser si une commande passe en alerte danger
* *Log* 
** *Moteur de log* : permet de changer le moteur de log pour par exemple les envoyer à un demon syslog(d)
** *Format des logs* : Format des logs à utiliser (attention ca n'affecte pas les logs des démons)
** *Nombre de lignes maximum dans un fichier de log* : Définit le nombre maximum de lignes dans un fichier de log, il est recommandé de ne pas toucher cette valeur, car une valeur trop grande pourrait remplir le système de fichiers et/ou rendre Jeedom incapable d'afficher le log
** *Niveau de log par défaut* : niveau de log par defaut de jeedom

En dessous vous retrouvez un tableau permet de gerer finement le niveau de log par type ou plugin de Jeedom

== Equipements

* *Anzahl der Fehler vor dem Deaktivieren der Geräte* : Anzahl von Kommunikationsausfällen der Geräte bevor sie Deaktiviert werden (eine Nachricht wird Sie warnen, wenn dies geschieht)
* *Batterien Schwellenwerte* : erlaubt, die globalen Alarmschwellen für die Batterien zu verwalten

== Update und Dateien

* *Source de mise à jour* : choisir la source de mise à jour du core de jeedom
* *Version du core* : version du core à récuperer
* *Faire une sauvegarde avant la mise à jour* : indique si il faut faire une sauvegarde avant la mise à jour
* *Vérifier automatiquement s'il y a des mises à jour* : indique si il faut chercher automatiquement si il y a de nouvelle mise à jour (attention pour eviter de faire tomber le market l'heure de verification peut changer)

=== Das Depot

Das Depot ist ein Internet-Speicherplatz (und Service), um Backups zu speichern, Plugins wiederherzustellen, den Jeedom Core wiederherstellen zu können….

==== Dateien

Depot aktivieren, zum versenden von Plugins als Dateien.

==== Github

Depot, das dazu dient, Jeedom mit Github zu verbinden

* *Token* : Token für den Zugriff auf den privaten Aufbewahrungsort
* *Utilisateur ou organisation du dépôt pour le core Jeedom* : nom de l'utilisateur ou de l'organisation sur github pour le core
* *Nom du dépôt pour le core Jeedom* : nom du dépot pour le core
* *Branche pour le core Jeedom* : branche du dépot pour le core

==== Markt

Aufbewahrungsort, der dazu dient, Jeedom mit dem Markt zu verbinden, es wird sehr geraten, diesen Ort zu benutzen. Achtung, es kann jede Supportanfrage abgelehnt werden, wenn Sie einen anderen Aufbewahrungsort wie diesen benutzt.

* *Adresse* : Markt Adresse
* *Benutzername* : Ihr Benutzername auf dem Markt
* *Passwort* : Ihr Passwort auf dem Markt

==== Samba

Dépôt permettant d'envoyer automatiquement un backup de Jeedom sur un partage Samba (ex NAS Synology).

* *[Backup] IP* : IP des Samba Servers
* *[Backup] Benutzer* : Benutzernamen für die Verbindung (anonyme Verbindungen sind nicht möglich)
* * L'utilisateur doit forcement avoir les droits lecture/ecriture sur ce repertoire
* *[Backup] Passwort* : Benutzerpasswort
* *[Backup] Partage* : chemin du partage (attention à bien s'arrêter au niveau du partage)
* *[Backup] Chemin* : chemin dans le partage (à mettre en relatif), celui-ci doit exister

[NOTE]
Si le chemin d'accès à votre dossier de sauvegarde samba est : \\192.168.0.1\Sauvegardes\Domotique\Jeedom
Alors IP = 192.168.0.1 , Partage = //192.168.0.1/Sauvegardes , Chemin = Domotique/Jeedom

[NOTE]
Lors de la validation du partage samba, tel que décrit précédement, une nouvelle forme de sauvegarde apparait dans l'onglet
backup de jeedom. En l'activant, jeedom procedera à son envoi automatique lors du prochain backup. Un test est possible en
effectuant un backup manuel. Le log devra donc ressembler à ceci :

[IMPORTANT]
Es wir notwendig sein, das sie das smbclient Software-Paket installieren, damit das Depot funktioniert

[IMPORTANT]
Jeedom doit être le seul à écrire dans ce dossier et il doit être vide par défaut (c'est à dire avant la configuration et l'envoi du premier backup, le dossier ne doit contenir aucun fichier ou dossier).

==== URL

* *URL Jeedom Kern*
* *URL Jeedom Kern Version*