==== Beschreibung
Ein wichtiger Teil in einer Software ist die Chronik, dies ist ein richtiges Gedächtnis.  Es ist in Jeedom möglich
jede Art von Steuerinformationen zu archivieren, das Prinzip ist ziemlich einfach, der Befehl ist ein
Ereignis,  es wird sobald das Ereignis eintritt archiviert. Wenn die Befehl kein Ereignis Typ ist
dann wird Jeedom versuchen, den Wert alle die 5 Minuten für die chronik wieder zu erlangen. 

Une fois cette historisation précise (temps entre chaque données de l’ordre de 5 à 10 min) faite, un archivage est fait en fonction des préférences de l’utilisateur :

- Wie lange die Daten zu archivieren sind
- La taille des paquets à faire
Par défaut Jeedom archive les données plus veilles de 2 heures par paquet de 1 heure.

Es gibt mehrere Möglichkeiten, um die Chronik zu zeigen:

- In einem Diagrammbereich in einer Ansicht
- Durch Klick auf den gewünschten Befehl in einem Widget
- Oder indem Sie auf der Chronik-Seite, die verschiedenen Kurven überlagern und verbinden es sind verschiedene Stiele erlaubt
(Fläche, Kurve, balken). Auf dieser Seite können Sie auch die ganze Chronik eines Auftrages löschen

Kern 
include::index.asciidoc[]
