= Armaturenbrett

Das ist die Hauptseite von Jeedom, es zeigt eine Übersicht über die ganze Heimautomation. Dieser Bericht (im Gegensatz zu den Ansichten und Design) wird von Jeedom selbst erzeugt.

Es kann zugegriffen werden, indem Sie auf Mein Haus -> Armaturenbrett klicken 

[TIP]
Il est possible d'aller directement sur un objet de votre domotique. Cela permet de n'avoir que les équipements qui vous intéressent et donc de charger la page plus rapidement

* Vous avez en haut à gauche une petite icône pour faire afficher/masquer l'arbre des objets (celui-ci affiche aussi les informations des résumés d'objet) 
* Au milieu vous pouvez choisir de ne filtrer que sur certains types d'équipements
* A droite un premier bouton pour passer en mode édition, pour par exemple modifier l'ordre des widgets (à l'aide d'un cliqué déposé sur le widget), vous pouvez aussi dans ce mode édition redimensionner certains widgets et réorganiser l'ordre des commandes à l'intérieur de celui-ci
* A gauche un bouton pour afficher/masquer les scénarios
* En cliquant sur un résumé d'objet vous pouvez filtrer pour n'affiché que les équipements comportant des commandes de celui-ci
* Un clique sur une commande de type information permet d'afficher l'historique de la commande (si elle est historisée)

[TIP]
Es ist in ihrem Profil möglich, Jeedom so zu konfigurieren, das der Gerätebaum und/oder die Szenarien standardmäßig sichtbar sind, wenn sie auf das Armaturenbrett kommen

[TIP]
En mobile un appui long sur une commande de type info permet d'afficher un menu vous proposant soit d'afficher l'historique de la commande, ou de mettre une alerte sur celle-ci pour que jeedom vous previenne (une seule fois) dès que la valeur passe un certain seuil

== Mode édition

En mode édition vous pouvez changer la taille des widgets et leur disposition sur le dashboard. 

Vous pouvez aussi editer la disposition interne des commande du widget : 

* soit les reorganiser par glisser/déposé
* en faisant un clic droit sur le widget vous pouvez aussi changer la disposition de celui-ci de standart à tableau : 
** standard : dispsition par defaut, tout est en automatique avec juste la possibilité de reorganiser l'ordre de commande
** tableau : permet de mettre les commandes dans un tableau, les colonnes et lignes s'ajoutent et se suppriment par clic droit, ensuite il suffit de déplacer les commandes dans les cases voulu, vous pouvez mettre plusieurs commande par cases
