= FAQ

== Jeedom nécessite-t-il un abonnement ?
Non, Jeedom ne nécessite pas d'abonnement pour son utilisation. Hors service de sauvegarde en ligne et d'appels/SMS qui sont soumis à abonnement (mais vraiment optionnel) .

== Jeedom utilise-t-il des serveurs extérieurs pour fonctionner ?
Nein, Jeedom verwendet keine solche "Cloud" Infrastruktur. Alles wird vor Ort durchgeführt, sodas sie unseren Server nicht brauchen, damit Ihre Installation funktioniert. Nur Dienstleistungen wie der Markt, Online-Backup oder Jeedom-DNS erfordern den Einsatz von unserem Server.

== Peut-on réordonner les commandes d'un équipement ?
Ja, ´sie können einfach per Drag/Drop die Befehle auf dem Objekte verschieben und neu anordnen.

== Peut-on éditer le style des widgets ?
Ja, es ist möglich, entweder über das Widget-Plugin, oder mit Hilfe der Seite Allgemein -> Anzeige

== Peut-on mettre plusieurs fois le même équipement sur un design ?
Das ist nicht möglich, aber Sie können diese Geräte vervielfältigen, dank des virtuellen Plugins.

== Comment changer une donnée erronée de l'historique ?
Es genügt auf einer Kurve der entsprechenden Chronik, auf den fraglichen Punkt zu klicken. Wenn Sie das Feld leer lassen, dann wird der Wert gelöscht.

== Combien de temps dure un backup ?
Es gibt keine Standard-Länge, es hängt von dem System ab, aber es kann mehr als 5 Minuten in Anspruch nehmen, das ist normal.

== Y a-t-il une application mobile dédiée ?
Jeedom possède une version mobile adaptée à l'utilisation sur mobile et tablette. Il existe aussi une application native pour Android et iOS

== Quels sont les identifiants pour me connecter la première fois ?
Wenn sie sich das erste mal mit Jeedom Verbinden (und sogar danach, wenn Sie die Loggindaten nicht geändert haben) ist der Benutzernamen und das Standardkennwort admin/admin.
Bei der ersten Verbindung, wird dringend gebeten, diese Loggindaten für zusätzliche Sicherheit zu ändern.

== Peut-on mettre Jeedom en https ?
Oui :
* Sie haben ein PowerPack oder mehr, in diesem Fall verwenden sie nur die Jeedom-DNS.
* Entweder sie haben eine DNS und sie wissen wie ein gültiges Zertifikat zu erstellen ist, in diesem Fall ist es eine standardisierte Zertifikat Installation.

== Comment remettre à plat les droits ?
In SSH eingeben : 
[source,bash]
sudo su -
chmod -R 775 /var/www/html
chown -R www-data:www-data /var/www/html

== Où se trouvent les backups de Jeedom ?
Ils sont dans le dossier /var/www/html/backup

== Comment mettre à jour Jeedom en SSH ?
In SSH eingeben : 

[source,bash]
sudo su -
php /var/www/html/install/install.php
chmod -R 775 /var/www/html
chown -R www-data:www-data /var/www/html

== La Webapp est-elle compatible Symbian ?
Die Webapp erfordert ein Smartphone, das HTML5 und CSS3 unterstützt. Sie ist daher leider nicht mit Symbian kompatibel.

== Sur quelles plateformes Jeedom peut-il fonctionner ?
Damit Jeedom funktioniert, ist eine Linux Plattform mit root Rechten notwendig oder ein typisches Docker System.