= FAQ

Erfordert Jeedom ein Abonnement ?::
Jeedom erfordert kein Abonnement für seine Benutzung. Nur ein optioneller Online-Backup-Service ist nicht kostenlos.

'''
Benutzt Jeedom einen externen Server, um zu funktionieren ?::
Non, Jeedom n'utilise pas d'infrastructure type "Cloud". Tout se fait en local et vous n'avez pas besoin de nos serveurs pour que votre installation fonctionne. Seuls les services comme le Market, la sauvegarde online ou le DNS Jeedom nécessitent l'utilisation de nos serveurs.

'''
Können die Befehle der Geräte neu angeordnet werden ?::
Ja, ´sie können einfach per Drag/Drop die Befehle auf dem Objekte verschieben und neu anordnen.

'''
Können wir den Widget Stil bearbeiten ?::
Ja, es ist möglich, entweder über das Widget-Plugin, oder mit Hilfe der Seite Allgemein -> Anzeige

'''
Können wir mehrmals die gleichen Geräte auf einem Design darstellen ?::
Das ist nicht möglich, aber Sie können diese Geräte vervielfältigen, dank des virtuellen Plugins.

'''
Wie kann man eine fehlerhafte Chronik ändern ?::
Es genügt auf einer Kurve der entsprechenden Chronik, auf den fraglichen Punkt zu klicken. Wenn Sie das Feld leer lassen, dann wird der Wert gelöscht.

'''
Wie kann man einen Computer registrieren damit mann sich nicht anzumelden muß ?::
Nur beim Verbinden das Kontrollkästchen "Speichern auf Computer" anklicken.

'''
Wie lange dauert eine Sicherung ?::
Es gibt keine Standard-Länge, es hängt von dem System ab, aber es kann mehr als 5 Minuten in Anspruch nehmen, das ist normal.

'''
Gibt es eine spezielle Mobile Anwendung ?::
Jeedom hat eine mobile Version für den Einsatz auf Handy und Tablet. Das Team ist aber dabei eine mobile Anwendung zu entwickeln, derzeit wurde noch kein Release-Datum angekündigt. 
Es ist durchaus möglich, dass Drittentwickler eine Anwendung für Jeedom anbietet.

'''
Was sind die Anmeldeinformationen, um mich das erste Mal einzuloggen ?::
Wenn sie sich das erste mal mit Jeedom Verbinden (und sogar danach, wenn Sie die Loggindaten nicht geändert haben) ist der Benutzernamen und das Standardkennwort admin/admin.
Bei der ersten Verbindung, wird dringend gebeten, diese Loggindaten für zusätzliche Sicherheit zu ändern.

'''
Oder kaufen Sie die Mini+ ?::
Die Jeedom-Mini wird von unseren Partner http://www.domadoo.fr/ vertrieben .

'''
Seit dem Kauf ist es nicht möglich von aussen auf Jeedom  zuzugreifen.::
Standardmäßig ist auf der Box Jeedom die Wurzel von Nginx. Sie dürfen nicht nach /jeedom/ die Zugriffsadresse hinzufügen. Die genaue Adresse ist : Ihre_öffentliche_IP:Ihr_Port/

'''
Kann Jeedom https ?::
Ja, es  giebt 3 Möglichkeiten :
* Sie haben ein PowerPack oder mehr, in diesem Fall verwenden sie nur die Jeedom-DNS.
* Entweder sie haben eine DNS und sie wissen wie ein gültiges Zertifikat zu erstellen ist, in diesem Fall ist es eine standardisierte Zertifikat Installation.
* Sie haben entweder keine DNS, und nachdem ein selbstsigniertes Zertifikat (für Rückruf ein selbstsigniertes Zertifikat-Verschlüsselung der Daten aber nicht die Validierung der Website bietet) Sie behindern, in diesem Fall um zu tun, was folgt, wenn es nicht funktioniert, wenn man Https in der URL :

[source,bash]
sudo su -
/usr/share/nginx/www/jeedom/install/install.sh nginx_ssl

Sie können in der Jeedom Konfiguration https erzwingen.

'''
Ich erhalte die Meldung : "Vous avez un trop grand nombre de système jeedom déclaré, veuillez en réduire le nombre et demander une réinitialisation de vos clefs d'installation", was ist zu tun?
Gehen sie auf den Markt, melden sie sich auf Ihr Konto an und gehen sie zu ihrem Profil und fragen nach dem Rücksetzen des Installationsschlüssels.

'''
Was ist, nur Ereignis und Lifetime Cache ?::
* nur Ereignis : weist Jeedom an, niemals nach dem Wert zu fragen(c'est l'équipement qui la remonte). Also beim Empfang eines Werts, hat dieser eine unendliche Lebensdauer (bis zum nächsten Empfang). 
* Lifetime cache : Durée de validité d'une valeur, si vous mettez 60 secondes par exemple, quand la valeur datera de plus de 60 secondes ET que jeedom en a besoin (dashboard, scénario...) alors il ira interroger le module pour avoir une valeur à jour.

Achtung, diese 2 Optionen sind für erfahrene Benutzer die diese Funktionen verstehen vorbehalten, ein Konfigurationsfehler in diesem Teil kann das System instabil oder funktionsunfähig machen. Zum Beispiel sollte in Zwave, RFXCOM und enocean, das Feld Ereignis IMMER angekreutzt werden,

'''
Wie sind die Rechte zu überarbeiten ?::
In SSH eingeben : 
[source,bash]
sudo su -
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom

'''
Oder ist die Sicherungen von Jeedom ?::
Sie sind im Verzeichnis /usr/share/nginx/www/jeedom/backup

'''
Wie kann mann Jeedom mit SSH auf den neuesten Stand bringen ?::
In SSH eingeben : 

[source,bash]
sudo su -
php /usr/share/nginx/www/jeedom/install/install.php
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom

'''
La Webapp est-elle compatible Symbian ?::
La webapp necessite un smartphone supportant le HTML5 et le CSS3. Elle n'est donc malheureusement pas compatible Symbian.

'''
Sur quelles plateformes Jeedom peut-il fonctionner ?::
Pour que Jeedom fonctionne il faut une plateforme linux avec les droits root ou un système type docker. Il ne fonctionne donc pas sur une plateforme android pure.