= Chronik

Partie importante dans un logiciel : la partie historisation, véritable mémoire de celui-ci. Il est possible dans Jeedom d'historiser n'importe quelle commande de type information (binaire ou numérique). Cela vous permettra donc par exemple d'historiser une courbe de température, de consommation ou les ouvertures d'une porte...

== Bestandteil

Hier ist das Prinzip der Archivierung von Jeedom beschrieben. Es ist erforderlich es zu begreifen, wenn Sie Probleme mit der Archivierung oder die Protokoll-Einstellungen ändern möchten. Die Standardeinstellungen eignen sich aber in den meisten Fällen.

=== Archivierung

L'archivage de données permet à Jeedom de réduire la quantité de données conservées en mémoire. Cela permet de ne pas utiliser trop de place et de ne pas ralentir le système. En effet, si vous conservez toute les mesures, cela fait d'autant plus de points à afficher et donc peut considérablement allonger les temps pour rendre un graphique. En cas d'un nombre trop important de points, cela peut même faire planter l'affichage du graphique.

L'archivage est une tâche qui se lance dans la nuit et compacte les données récupérées dans la journée. Par défaut Jeedom récupère toutes les données plus vieilles de 2h et en fait des paquets de 1h (soit une moyenne, un minimum ou un maximum en fonction des réglages). On a donc ici 2 paramètres, un pour la taille des paquets et un autre pour savoir à partir de quand en faire (pour rappel par défaut ce sont des paquets de 1h avec des données qui ont plus de 2h d'ancienneté).

[TIP]
Si vous avez bien suivi vous devriez avoir une haute précision sur les 2 dernières heures seulement. Pourtant quand je me connecte à 17h, j'ai une précision sur les 17 dernières heures. Pourquoi ? En fait, pour éviter de consommer des ressources inutilement, la tâche qui fait l'archivage ne se déroule qu'une fois par jour, le soir.

[IMPORTANT]
Bien sûr, ce principe d'archivage ne s'applique qu'aux commandes de type numérique ; sur les commandes de type binaire, Jeedom ne conserve que les dates de changement d'état.

== Diagramm anzeigen

Es gibt mehrere Möglichkeiten, um die Chronik anzuzeigen :

* einen Diagrammbereich in einer Ansicht einsetzen (siehe unten),
* Durch Klick auf den gewünschten Befehl in einem Widget,
* en allant dans la page historique qui permet de superposer différentes courbes et de combiner les styles (aire, courbe, barre)
* en mobile en restant appuyé sur le widget en question

Wenn Sie eine Diagramm auf der Chronik Seite oder durch einen Klick auf das Widget angezeigt bekommen, haben Sie Zugriff auf mehrere Anzeigeoptionen : 

On retrouve en haut à droite la période d'affichage (ici sur la dernière semaine car, par défaut je veux que ça soit seulement une semaine - voir 2 paragraphes au-dessus), ensuite viennent les paramètres de la courbe (ces paramètres sont gardés d'un affichage à l'autre ; vous n'avez donc qu'a les configurer une fois).

* *Treppe* : Zeigt die Kurve in Form einer Treppe oder sie wird kontinuierlich wiedergegeben.
* *Wertänderung* : Zeigen den Unterschied der Werte im Vergleich zu dem vorherigen Punkt an.
 * *Linie* : Zeigt das Diagramm in einer Linie an.
* *Fläche* : Zeigt das Diagramm als eine Fläche an. 
* *Balken** : Zeigt das Diagramm in einer Balken Form an.

== Grafik auf der Ansicht und dem Design

Sie können die Grafik auch in der Ansicht anzeigen (hier werden wir die Konfigurationsoptionen angezeigt und nicht wie, dafür muß man sich in die Dokumention der Ansicht oder des Designs zur Funktion begeben). Hier sind die Optionen : 

Sobald die Daten aktiviert sind, können Sie wählen : 

* *Farbe* : Die Farbe der Kurve.
* *Typ* : Der Typ des Diagramms (Fläche, Linie oder Balken). 
* *Maßstab* : Weil Sie mehrere Diagramme (Daten) in der gleichen Grafik anzeigen können, ist es mit der Einstellung möglich, den Maßstab (rechts oder links) zu unterscheiden.
* *Treppe* : Zeigt die Kurve in Form einer Treppe oder sie wird kontinuierlich wiedergegeben.
* *Stapeln* : Erlaubt, die Werte der Kurven zu stapeln (siehe das Ergebnis darunter)
* *Wertänderung* : Zeigen den Unterschied der Werte im Vergleich zu dem vorherigen Punkt an.

== Optionen auf der Chronik Seite

La page d'historique donne accès à quelques options supplémentaires

=== Historique calculé

Permet d'affiché une courbe en fonction d'un calcul sur plusieurs commande (vous pouvez à peu pret tout faire, +-/* valeur absolue... voir documentation PHP pour certaine fonction). Ex : abs(#[Jardin][Hygrometrie][Température]# - #[Espace de vie][Hygrométrie][Température]#)

Vous avez aussi accès à un gestion de formules de calcul qui vous permet de les sauvegarder pour les réafficher plus facilement

[TIP]
Klicken Sie einfach auf den Namen des Objekts um es zu entfalten ; angezeigt werden die archivierten Befehle, die ein Diagramm sein können.

=== Historique de commande

Vor jedem Datensatz der als Diagramm angezeigt werden kann, finden Sie zwei Symbole : 

* *Papierkorb* : Löscht die gespeicherten Daten ; beim Klicken, fragt Jeedom, ob die Daten von einem bestimmten Datum oder alle Daten zu löschen sind.
* *Pfeil* : Erlaubt einen CSV-Export archivierter Daten.

== Löschen von inkonsistenten Wert

Parfois, il se peut que vous ayez des valeurs incohérentes sur les graphiques. Cela est souvent dû à un souci d'interprétation de la valeur. Il est possible de supprimer ou changer la valeur du point en question, en cliquant sur celui-ci directement sur le graphique ; de plus, vous pouvez régler le minimum et le maximum autorisés afin d'éviter des problèmes futurs.

= Timeline

La timeline affiche certain évènements de votre domotique sous forme chronologique.

Pour les voirs vous faut d'abord activer le suivi sur la timeline des commandes ou scénarios voulu : 

* *Scenario* : soit directement sur la page de scénario ou sur la page de résumé de scénario pour le faire en "mass"
* *Commande* : soit dans la configuration avancé de la commande soit dans la configuration de l'historique pour le faire en "mass"

[TIP]
Vous avez accès au fenetre de résumé des scénarios ou configuration de l'historique directement à partir de la page de timeline

Une fois que vous avez activer le suivi dans la timeline des commandes et scénario voulu vous pourrez voir apparaitre ceux-ci sur la timeline 

[IMPORTANT]
Il faut attendre de nouveau évènement après avoir activer le suivi sur la timeline avant de les voir apparaitre

Les cartes sur la timeline affiche : 

* *Commande action* : en fond rouge, une icone à droite vous permet d'afficher la fenetre de configuration avancée de la commande
* *Commande info* : en fond bleu, une icone à droite vous permet d'afficher la fenetre de configuration avancée de la commande
* *Scénario* : en fond gris, vous avez 2 icônes, une pour afficher le log du scénario et une pour aller sur le scénario