= Protokolle

== Ansicht

Le menu Logs permet de suivre ce qui se passe sur sa domotique. Dans la plupart des cas les logs ne serviront qu'à effectuer du debuggage et à résoudre des problèmes par l'équipe de support. Ce menu est d'ailleurs accessible uniquement en mode expert.

Pour y accéder il faut aller dans Administration -> Logs : 

Die Logs-Seite ist ganz einfach, oben links ist ein Dropdown-Menü, dass die Auswahl der Logs ermöglicht und oberen rechts sind 5 Schaltflächen :

* *Rechercher* : permet de filtrer l'affiche de log
* *Pause/Reprendre* : permet de mettre en pause/reprendre la mise à jour en temps réel des logs
* *Herunterladen* : zum herunterladen des aktuellen Protokolls ,
* *Leeren* : wird verwendet, um das aktuelle Protokoll zu löschen,
* *Löschen* : Löscht das aktuelle Protokoll, wenn Jeedom es benötigt, wird es automatisch neu erstellt, 
* *Alle Protokolle löschen* : Löscht alle vorhandene Protokolle.

[TIP]
A noter que le log http.error ne peut être supprimé. Il est essentiel ! si vous le supprimez (en ligne de commande par exemple) celui-ci ne se recréera pas tout seul, il faut redémarrer le système.

== Le log "Event"

Le log "Event" est un peu particulier. Tout d'abord pour qu'il fonctionne, il faut qu'il soit en niveau info ou debug, ensuite celui-ci recense tous les évènements ou actions qui se passent sur la domotique. Pour y accéder, il faut soit aller sur la page de log soit dans Analyse -> Temps réel

Une fois que vous avez cliqué dessus, vous obtenez une fenêtre qui se met à jour en temps réel et vous affiche tous les évènements de votre domotique.

Oben rechts haben sie ein Suchfelder  (funktioniert nur, wenn sie nicht angehalten haben) und eine Schaltfläche für die Pause (nützlich zum Beispiel für Kopieren/Einfügen).