= Markt

Doc un peu particulière car elle va traiter uniquement de votre page profil du market.

Disponible en allant sur votre nom d'utilisateur puis profil à partir du market (un peu comme sur Jeedom).

Er besteht aus mehreren Teilen : 

== Mein Profil

Hier können sie verschiedene Einstellungen Ihres Profiles anpassen : 

* *Profil*
** *Login* : Ihre Anmeldung auf dem Markt, es kann nicht geändert werden.
** *Name* : Ihren Namen (Diese Information ist sinnvoll, um freundliche E-Mails zubekommen)
** *Vorname* : Ihren Vorname (Diese Information ist sinnvoll, um freundliche E-Mails zubekommen)
** *Nom d'utilisateur sur le forum* : Votre pseudo sur le forum
** *Email* : Ihre E-Mail
** *Sprache* : Ihre Sprache
** *Passwort && Passwort bestätigen* : Um ihr Passwort zu ändern.


Pour les développeurs :

** *Nom d'utilisateur sur le forum* : Votre pseudo sur le forum
** *Email public* : Votre mail pour recevoir des éventuelles communications de notre part
** *Paypal Konto* : Ihre E-Mail vom Paypal Konto (wird nur verwendet, um die Entwickler zu bezahlen)

Pour les pros :

** *Compte mail installateur* : Votre mail de contact pro
** *Destinataire des demandes de support* : savoir qui recevra les mails de support (client final, installateur ou les deux)

* *CGU*
** *Benutzer* : Allgemeine Geschäftsbedingungen (Achtung, vor Benutzung gut durchlesen)
** *Entwickler* : Allgemeine Geschäftsbedingungen für Entwickler
* *Tickets*
** *Gutschein Anzahl* : Anzahl der Gutscheine für den laufenden Monat, sowie Ihr Limit
** *Support* : Schaltfläche, um eine Support-Anfrage zu senden (auch zugänglich durch das Ausrufezeichen am rechten oberen Rand auf dem Markt oder auf ihr Jeedom). 

* *Accés aux betas*
** *Activer l'accès aux plugins beta* : permet d'activer l'accès aux plugins betas (attention cela vous interdira tout accès au support)

* *Résumé*
Ici vous retrouverez un résumé de vos différents droits et services 

[TIP]
Vergessen Sie nicht, zu speichern.

== Mein Jeedom

* *Niveau*
** *Jeedom* : Ihr Service Pack Niveau
** *Eine Service-Pack Nummer eingeben* : Ihre Service-Pack Nummer eingeben (sie ist in der E-Mail, die bei der Bestellung, von Jeedom geschickt wird)
* *Installationsschlüssel*
** *Anzahl der Installationsschlüssel* : Zeige die Anzahl, die mit Ihrem Konto gegenwärtig verbundenen Jeedom Installationen  an, sowie das gestattete Limit

[TIP]
Es ist möglich, dass sie der Markt mal bittet, den Installationsschlüssel wieder auf null zu stellen, normalerweise genügt es dem zu folgen, was er sie fragt.

* *Mein Jeedom* : Hier sind alle Ihre Jeedoms aufgelistet
** *Name* : Der Name, den sie ihr Jeedom geben wollen (findet sich im Namen des Backup wieder, wenn Sie das Cloud Backup Abonnement haben)
** *Etat* : permet de voir l'état du Jeedom en question
** *IP locale / distante* : IP ou addresse de ce Jeedom, se configure dans Jeedom, si vous ne mettez rien ça sera la dernière IP connue
** *DNS* : permet de personnaliser le nom de votre DNS 
** *URL* : liste les différentes URL d'accès au Jeedom.
** *Serveur DNS* : vous indique si le serveur DNS auquel vous êtes rattachés
** *Statut du DNS* : permet de voir le statut du DNS
** *Erstellungsdatum* : Erstellungsdatum dieses Jeedom auf Ihrem Markt Konto (zur Erinnerung, das macht es automatisch, wenn Sie es mit dem Markt verknüpfen)
** *Zuletzt aktualisiert* : die letzte Kommunikation von Jeedom mit dem Markt
** *Hardware* : Name der Jeedom Hardware
** *Version* : installierte Jeedom Version

[TIP]
Vergessen Sie nicht, zu speichern.

== Meine Backups

Auf dieser Registerkarte können sie die vorhandenen Sicherungen auf dem Markt ansehen und herunterladen. Im folgenden haben sie Zugriff auf die Links, zum kauf von einem 1,3,6 oder 12-Monats-Abonnement für die Backup Cloud.

== Mes SMS/Appels

Sur cette onglet vous pouvez consulter votre solde SMS/Appels (utilisable avec le plugin Phone market). En dessous vous avez les différentes options permettant d'acheter du solde supplémentaire.

== Meine Einkäufe/Gutscheine/Spenden

Hier finden sie all ihre Einkäufe und Sie können die Überweisung der E-Mail-Rechnung oder Quittung anfordern.

[IMPORTANT]
Wenn sie ein offizielles Plugin kaufen, erhalten sie eine Rechnung, im Gegensatz zu einem Plugin von dritten, ist das eine Quittung, für die Rechnung muss man den Entwickler fragen.

Sie können auch darin einen Gutscheincode eingeben (zum Beispiel ein Code für ein Plugin, dass der Entwickler an sie weitergegeben hat) und eine Spende machen.  

== Meine Entwicklungen

Wenn sie Entwickler sind finden sie hier eine Liste aller Verkäufe über einen Zeitraum, die Liste der Zahlungen und eine Übersicht über die Anzahl der Downloads, die Zahl der Verkäufe ...