= Design

Cette page permet de configurer l'affichage de toute votre domotique de manière très fine. Celle-ci demande du temps mais sa seule limite est votre imagination.

Elle est accessible par Acceuil -> Dashboard

[TIP]
Il est possible d'aller directement sur un design grâce au sous-menu.

[IMPORTANT]
Toute les actions ce font par un clic droit sur cette page, attention a bien le faire dans le design. Lors de la création il faut donc le faire au milieu de la page (pour etre sur d'etre sur le design)

Dans le menu nous retrouvons (clic droit donc) nous retrouvons les actions suivantes : 

* *Designs* : Affiche la liste de vos designs et vous permet de naviguer de dedans
* *Edition* : Permet de passer en édition
* *Plein ecran* : Affiche le design en pleine écran
* *Ajouter graphique* : Permet d'ajouter un graphique
* *Ajouter texte/html* : Permet d'ajouter du texte ou du code html/javascript
* *Ajouter scénario* : Permet d'ajouter un scénario
* *Ajouter lien*
** *Vers une vue* : Permet d'ajouter un lien vers une vue
** *Vers un design* : Permet d'ajouter un lien vers un autre design
* *Ajouter équipement* : Permet d'ajouter un équipement
* *Ajouter commande* : Permet d'ajouter une commande
* *Ajouter image/caméra* : Permet d'ajouter une image ou le flux d'une caméra
* *Ajouter zone* : Permet d'ajouter une zone transparante cliquable qui pourra executer une serie d'action lors d'un clic (en fonction ou non de l'état d'une autre commande)
* *Ajouter résumé* : Ajoute les informations d'un résumé d'objet ou général
* *Ansicht *
** *Aucune* : N'affiche aucune grille
** *10x10* : Affiche une grille de 10 par 10
** *15x15* : Affiche une grille de 15 par 15
** *20x20* : Affiche une grille de 20 par 20
** *Aimanter les élements* : Ajoute une aimantation entre les élements pour permettre de les coller plus facilement
** *Aimanter à la grille* : Ajouter une aimantation des éléments à la grille (attention en fonction du zoom de l'élément cette fonctionalité peut plus ou moins fonctionner) 
** *Masquer la surbrillance des éléments* : Masque la surbrillance autour des élements
* *Supprimer le design* : supprime le design
* *Créer un design* : permet d'ajouter un design
* *Dupliquer le design* : duplique le design courant
* *Configurer le design* : accès à la configuration du design
* *Sauvegarder* : permet de sauvegarder le design (attention il y aussi des sauvegarde automatique lors de certaine action)

[IMPORTANT]
La configuration des éléments du désign se fait par un clic sur ceux-ci

== Configuration design

Hier haben wir : 

* *Général*
** *Nom* : Le nom de votre design
** *Icône* : Une icône pour celui-ci (apparait dans le menu de choix de design)
** *Image* 
*** *Envoyer* : permet d'ajouter une image de fond au design
*** *Supprimer l'image* : permet de supprimer l'image
* *Größe*
** *Größe (LxH)* : Erlaubt, die Größe Ihres Designs festzulegen (grauer Rahmen in Bearbeiten-Modus)

== Configuration général des éléments

[NOTE]
En fonction du type de l'élement les options peuvent changer

[NOTE]
L'element séléctionné apparait en surbrillance rouge (au lieu de vert pour tous les autres)

=== Paramètre d'affichage

* *Tiefe* : erlaubt das Niveau der Tiefe zu wählen
* *Position X (%)* :
* *Position Y (%)* :
* *Largeur (px)* :
* *Hauteur (px)* :

=== Supprimer

Permet de supprimer l'élement

=== Dupliquer

Permet de dupliquer l'élement

=== Verrouiller

Permet de verrouiller l'élement pour plus qu'il soit déplacable ou redimmensionnable

== Graphique

=== Paramètre d'affichage

* *Période* : permet de choisir la période d'affichage
* *Afficher la légende* : permet d'afficher ou non la légende
* *Navigator* : ermöglicht, das Anzeigen oder Ausblenden eines Navigators (etwas unterhalb des Diagramms) 
* *Afficher le sélecteur de période* : affiche ou non le sélecteur de période en haut à gauche
* *Afficher la barre de défilement* : affiche ou non la barre de défilement
* *Transparenter Hintergrund* : macht den Hintergrund transparent  
* *Rand (Achtung css syntax, bsp.: solid 1px black)* : um einen Rand hinzuzufügen, Achtung es ist die HTML Syntax zu verwenden

=== Erweiterte Konfiguration

Permet de choisir les commandes à grapher

== Text/html

* *Icone* : Icone à affiché devant
* *Hintergrundfarbe* : Hier können sie die Hintergrundfarbe oder die Transparenz ändern, vergessen sie nicht  "Standard" auf nein zu stellen
* *Text Farbe* : Hier können Sie die Symbol und Text Farbe ändern (Achtung, Standard auf nein stellen)
* *Runde Ecken (vergessen Sie nicht das % einzugeben, bsp. 50%)* : wird verwendet, um die Ecken abzurunden, vergessen sie nicht das % Zeichen einzugeben
* *Rand (Achtung css syntax, bsp.: solid 1px black)* : um einen Rand hinzuzufügen, Achtung es ist die HTML Syntax zu verwenden
* *Schriftgröße (z.B. 50%, das % -Zeichen muß eingegeben werden)* : ermöglicht die Schriftgröße zu ändern
* *Alignement du texte* : permet de choisir l'alignement du texte (gauche/droit/centré)
* *Gras* : met le texte en gras
* *Texte* : Texte au code html qui sera dans l'élement

[IMPORTANT]
Si vous mettez du code html (en particulier du javascript), attention à bien le vérifier avant car vous pouvez si il y a une erreur dedans ou si il écrase un composant Jeedom planter completement le design et il ne restera plus qu'a le supprimer directement base de données

== Szenario

=== Paramètre d'affichage

Aucun paramètre spécifique d'affichage

== Link

=== Paramètre d'affichage

* *Nom* : Nom du lien (texte affiché)
* *Lien* : Lien vers le design ou la vue en question
* *Hintergrundfarbe* : Hier können sie die Hintergrundfarbe oder die Transparenz ändern, vergessen sie nicht  "Standard" auf nein zu stellen
* *Text Farbe* : Hier können Sie die Symbol und Text Farbe ändern (Achtung, Standard auf nein stellen)
* *Runde Ecken (vergessen Sie nicht das % einzugeben, bsp. 50%)* : wird verwendet, um die Ecken abzurunden, vergessen sie nicht das % Zeichen einzugeben
* *Rand (Achtung css syntax, bsp.: solid 1px black)* : um einen Rand hinzuzufügen, Achtung es ist die HTML Syntax zu verwenden
* *Schriftgröße (z.B. 50%, das % -Zeichen muß eingegeben werden)* : ermöglicht die Schriftgröße zu ändern
* *Alignement du texte* : permet de choisir l'alignement du texte (gauche/droit/centré)
* *Gras* : met le texte en gras

== Geräte

=== Paramètre d'affichage

Aucun paramètre spécifique d'affichage

=== Erweiterte Konfiguration

Affiche la fenetre de configuration avancé de l'équipement (voir documentation Résumé domotique ("display"))

== Befehle

=== Paramètre d'affichage

Aucun paramètre spécifique d'affichage

=== Erweiterte Konfiguration

Affiche la fenetre de configuration avancé de la commande (voir documentation Résumé domotique ("display"))

== Image/Caméra

=== Paramètre d'affichage

* *Afficher* : défini ceux que vous voulez afficher, image fixe ou flux d'une caméra
* *Image* : permet d'envoyer l'image en question (si vous avez choisi une image)
* *Caméra* : caméra à afficher (si vous avez choisi caméra)

== Zone

=== Paramètre d'affichage

* *Type de zone* : C'est ici que vous choissez le type de la zone : Macro simple, Macro Binaire ou Widget au survol

==== Macro simple

Dans ce mode la un clic sur la zone execute une ou plusieurs action.

Il vous suffit ici d'indiquer la liste des actions à faire lors du clic sur la zone

==== Macro binaire

Dans ce mode Jeedom va executer la ou les action(s) On ou Off en fonction de l'état de la commande que vous donnez. Ex si la commande vaut 0 alors Jeedom executera la ou les action(s) On sinon il executera la ou les action(s) off

* *Information binaire* : Commande donnant l'état à verifier pour decider de l'action à faire (on ou off)

Il vous suffit en dessous de mettre les actions à faire pour le on et pour le off

==== Widget au survol

Dans ce mode lors du survole ou du clic dans la zone jeedom vous affichera le widget en question

* *Equipement* : widget à afficher lors du survole ou du clic
* *Afficher au survol* : si coché affiche le widget au survol
* *Afficher sur un clic* : si coché alors le widget est affiché au clic
* *Position* : permet de choisir l'emplacement d'apparition du widget (par defaut bas droite)

== Zusammenfassung

* *Lien* : Permet d'indiqué le résumé à afficher (Général pour le globale sinon indiquer l'objet)
* *Hintergrundfarbe* : Hier können sie die Hintergrundfarbe oder die Transparenz ändern, vergessen sie nicht  "Standard" auf nein zu stellen
* *Text Farbe* : Hier können Sie die Symbol und Text Farbe ändern (Achtung, Standard auf nein stellen)
* *Runde Ecken (vergessen Sie nicht das % einzugeben, bsp. 50%)* : wird verwendet, um die Ecken abzurunden, vergessen sie nicht das % Zeichen einzugeben
* *Rand (Achtung css syntax, bsp.: solid 1px black)* : um einen Rand hinzuzufügen, Achtung es ist die HTML Syntax zu verwenden
* *Schriftgröße (z.B. 50%, das % -Zeichen muß eingegeben werden)* : ermöglicht die Schriftgröße zu ändern
* *Gras* : met le texte en gras