= Grundlagen

Jeedom ist aus einem Kern, der Basisfunktionen ausführt zusammensetzt : 

* Szenario
* Chronik
* Ansicht
* Interaktion
* Update und Sicherung

Autour de ce core viennent se greffer des plugins qui peuvent être de toutes sortes :
 
* Home-Automatisierungs Protokolle (Z-Wave, RFXcom, EnOcean...)
* IP Protokolle (KNX,xPL...)
* Kommunikationsobjekte (Nest, Netatmo ...)
* hohes Niveau (Alarm, Thermostat)
* Schnittstelle (Widget)
* Organisation (Kalender, Google Kalender)
* Entwicklung (Skript)

Ces plugins peuvent être récupérés par le biais du Market et permettent d'étendre les possibilités de Jeedom.

Jeedom ermöglicht es jedem Plugin, mit einem anderen auf standardisierter Basis zu komunizieren. Dies ermöglicht es beispielsweise, das Thermostat-Plugin zu verwenden oder Alarm mit beliebigem Haus-Automatisierungs-Protokoll oder sogar ein IP Plugin oder Kommunikationsobjekt ...

Außerdem hat Jeedom die Besonderheit, ohne Abo und ohne Cloud zu sein, wodurch das Funktionieren ihrer Hause-Automatisierung garantiert wird, auch wenn sie kein Internet mehr haben. Dadurch wird auch die Sicherheit ihrer Daten garantiert (vermeidet die Risiken der massenhaften Konten Piraterie).

Das Projekt ist offen und Open-Source das gewährleistet auch eine hohe Rate der Entwicklung, dank der vielen Entwickler die teilnehmen.  