= Grundlagen

Jeedom est composé d'un core qui se charge des fonctions de base : 

* Szenario
* Chronik
* Ansicht
* Interaktion
* Update und Sicherung

Autour de ce core viennent se greffer des plugins qui peuvent être de toutes sortes :
 
* protocole domotique (zwave, rfxcom, enOcean...)
* IP Protokolle (KNX,xPL...)
* Kommunikationsobjekte (Nest, Netatmo ...)
* hohes Niveau (Alarm, Thermostat)
* Schnittstelle (Widget)
* Organisation (Kalender, Google Kalender)
* Entwicklung (Skript)

Ces plugins peuvent être récupérés par le biais du Market et permettent d'étendre les possibilités de Jeedom.

Jeedom permet à n'importe quel plugin de discuter avec un autre sur une base normalisée, cela permet par exemple d'utiliser les plugins thermostat ou alarme avec n'importe quel protocole domotique ou même un plugin IP ou objet communiquant...

Außerdem hat Jeedom die Besonderheit, ohne Abo und ohne Cloud zu sein, wodurch das Funktionieren ihrer Hause-Automatisierung garantiert wird, auch wenn sie kein Internet mehr haben. Dadurch wird auch die Sicherheit ihrer Daten garantiert (vermeidet die Risiken der massenhaften Konten Piraterie).

Das Projekt ist offen und Open-Source das gewährleistet auch eine hohe Rate der Entwicklung, dank der vielen Entwickler die teilnehmen.  