= Grundlagen

Jeedom ist aus einem Kern, der Basisfunktionen ausführt zusammensetzt : 

* Szenario
* Chronik
* Ansicht
* Interaktion
* Update und Sicherung

Um diesen Kern herum kommen Plugins hinzu, die verschieden sein können : 
 
* Home-Automatisierungs Protokolle (Z-Wave, RFXcom, EnOcean...)
* IP Protokolle (KNX,xPL...)
* Kommunikationsobjekte (Nest, Netatmo ...)
* hohes Niveau (Alarm, Thermostat)
* Schnittstelle (Widget)
* Organisation (Kalender, Google Kalender)
* Entwicklung (Skript)

Diese Plugins können über den Markt geladen werden und ermöglichen es, Jeedom zu erweitern.

Jeedom ermöglicht es jedem Plugin, mit einem anderen auf standardisierter Basis zu komunizieren. Dies ermöglicht es beispielsweise, das Thermostat-Plugin zu verwenden oder Alarm mit beliebigem Haus-Automatisierungs-Protokoll oder sogar ein IP Plugin oder Kommunikationsobjekt ...

Außerdem hat Jeedom die Besonderheit, ohne Abo und ohne Cloud zu sein, wodurch das Funktionieren ihrer Hause-Automatisierung garantiert wird, auch wenn sie kein Internet mehr haben. Dadurch wird auch die Sicherheit ihrer Daten garantiert (vermeidet die Risiken der massenhaften Konten Piraterie).

Das Projekt ist offen und Open-Source das gewährleistet auch eine hohe Rate der Entwicklung, dank der vielen Entwickler die teilnehmen.  