= Dépannage

== J'ai une page blanche

Il faut se connecter en SSH à jeedom et lancer un script d'auto-diagnostic : 

[source,bash]
sudo chmod +x /var/www/html/health.sh;sudo /var/www/html/health.sh

Wenn es Probleme gibt, versucht das Skript sie zu korrigieren, wenn das nicht funktioniert, werden sie informiert.

Vous pouvez aussi regarder le log /var/www/html/http.error, très souvent celui-ci indique le souci

== J'ai un problème d'identifiant BDD

Sie müssen diese Zurücksetzen
[source,bash]
bdd_password=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 15)
echo "DROP USER 'jeedom'@'localhost'" | mysql -uroot -p
echo "CREATE USER 'jeedom'@'localhost' IDENTIFIED BY '${bdd_password}';" | mysql -uroot -p
echo "GRANT ALL PRIVILEGES ON jeedom.* TO 'jeedom'@'localhost';" | mysql -uroot -p
cd /usr/share/nginx/www/jeedom
sudo cp core/config/common.config.sample.php core/config/common.config.php
sudo sed -i -e "s/#PASSWORD#/${bdd_password}/g" core/config/common.config.php 
sudo chown www-data:www-data core/config/common.config.php

.Ich habe {{...}} überall.

La cause la plus fréquente est l'utilisation d'un plugin en version beta, et Jeedom en stable, ou l'inverse. Pour avoir le details de l'erreur il faut regarder le log http.error (dans /var/www/html/log)

== Bei einem Befehl habe ich ein Rad, das sich dreht, ohne stehen zu bleiben

Encore une fois cela est souvent dû à un plugin en beta alors que Jeedom est en stable. Pour voir l'erreur il faut faire F12 puis console

== Ich habe keinen Zugriff auf Jeedom oder SSH

Dieser Fehler ist nicht in Jeedom sondern ein Problem in dem System. Wenn das Problem infolge einer Reinstallation besteht, wird empfohlen, mit Service die Hardware-Problemen anzusehen .

== Mein Szenario hört nicht mehr auf

Il est conseillé de regarder les commandes exécutées par le scénario, souvent cela vient d'une commande qui ne se termine pas

== Mon scénario est lent à se déclencher

Wenn es im Szenario keine Pause gibt, wird geraten das Kontrollkästchen anzukreuzen "so schnell wie möglich auszuführen" (verfügbar im Experten-Modus)

== J'ai des instabilités ou des erreurs 504

Vérifiez si votre système de fichiers n'est pas corrompu, en SSH la commande est : "sudo dmesg | grep error"

== Je ne vois pas tous mes équipements sur le dashboard

Souvent cela est dû au fait que les équipements sont affectés à un objet qui n'est pas le fils ou l'objet lui-même du premier objet sélectionné à gauche dans l'arbre (vous pouvez dans votre profil configurer celui-ci)

== Lors de la connexion du maître avec les esclaves j'ai des erreurs

Vérifiez que vous avez bien mis les /jeedom si vous utilisez ceux-ci juste après l'IP de jeedom (souvent le cas en installation DIY)

== J'ai l'erreur suivante : SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

Cela est dû à MySQL qui s'est arrêté, ce n'est pas normal, les cas courants sont : 

* souci de place sur le système de fichiers (peut être vérifié en faisant la commande "df -h", en SSH)
* problème de corruption de fichier(s), arrive souvent suite à un arrêt non propre de Jeedom (coupure de courant)

Leider gibt es nicht viel Auswahl, wenn dies der zweite Fall ist, ist der beste Weg, ein Backup wiederherzustellen (standardmäßig in /usr/share/nginx/www/jeedom/backup verfügbahr), installieren Sie Jeedom neu und stellen die Sicherung wieder her. Sie können auch ssh verwenden, um zu sehen, warum mysql nicht starten möchte: 
[source,bash]
sudo su -
service mysql stop
mysqld --verbose

Oder in das Protokoll sehen  : /var/log/mysql/error.log

== Die Ausschalten/Neustart Schaltflächen funktionieren nicht

Auf einer DIY Installation ist das normal, man muss daher unter SSH den Befehl visudo eingeben und am Ende der Datei fügen sie folgendes hinzu : www-data ALL=(ALL) NOPASSWD: ALL.

[source,bash]
sudo service apache2 restart

== Einiges Plugins des Marktes sehe ich nicht

Diese Art von Ereignissen kommen vor, wenn Ihr Jeedom mit dem Plugin nicht kompatibel ist, im Allgemeinen verbessert eine Jeedom Aktualisierung diese Probleme.