SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `jeedom`.`jeeNetwork` (
  `id` INT(11) NOT NULL,
  `ip` VARCHAR(63) NULL DEFAULT NULL,
  `apikey` VARCHAR(255) NULL DEFAULT NULL,
  `plugin` TEXT NULL DEFAULT NULL,
  `configuration` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE `jeedom`.`jeeNetwork` 
ADD COLUMN `name` VARCHAR(127) NULL DEFAULT NULL AFTER `configuration`;

ALTER TABLE `jeedom`.`jeeNetwork` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `jeedom`.`jeeNetwork` 
CHANGE COLUMN `ip` `ip` VARCHAR(127) NULL DEFAULT NULL ,
ADD COLUMN `status` VARCHAR(127) NULL DEFAULT NULL AFTER `name`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

