SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `jeedom`.`listener` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(127) NULL DEFAULT NULL,
  `function` VARCHAR(127) NULL DEFAULT NULL,
  `event` VARCHAR(255) NULL DEFAULT NULL,
  `option` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `event` (`event` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
