= FAQ

Does Jeedom need a subscription?::
No, Jeedom does not require a subscription to use. Only an online backup service is optional surcharge.

'''
Does Jeedom require external servers to operate?::
Non, Jeedom n'utilise pas d'infrastructure type "Cloud". Tout se fait en local et vous n'avez pas besoin de nos serveurs pour que votre installation fonctionne. Seuls les services comme le Market, la sauvegarde online ou le DNS Jeedom nécessitent l'utilisation de nos serveurs.

'''
Can the order of the controls of a device be changed?::
Yes it is possible, simply drag & drop the controls of your device.

'''
Can the style of the widgets be edited? ::
Yes it is possible either via the widget plugin, or using the page Main -> Command setup -> Advanced display

'''
Can the same device be present many times on the same design ?::
No this is not possible, but you can duplicate it using the virtual Plugin.

'''
How to change an erroneous data in the history?::
On a historical chart, just click on the point in question to edit it. If you leave the fields blank then the value is deleted.

'''
How to avoid to log in each time?::
At login just check the box "Register this computer".

'''
How long takes a backup?::
There is no standard time, it depends on the system and the data volume, so it may take more than 5 minutes, which is normal.

'''
Is there a native mobile app?::
Jeedom has a version of the web application for mobile and tablet. A native mobile application is being developed by the team right now, but no release date has been announced yet.
It is quite possible that third-party developers realized dedicated applications for Jeedom.

'''
What are the credentials to use at login the first time?::
When you first connect to Jeedom (and beyond if you don't change it) the user name is admin and the default password is admin.
At the first connection, it is strongly recommended to change these identifiers for better security.

'''
Where to buy the Mini+?::
Jeedom Mini is marketed at our partner http://www.domadoo.fr/.

'''
Impossible to access Jeedom from to the outside after purchasing a box::
By default Jeedom is running at the root of Nginx on a box. You do not have to add /jeedom/ in the access address. The exact address will be: your_public_ip:your_port/

'''
Can Jeedom be accessed over HTTPS?::
Yes, 3 possibilities:
* You have a pack power or more, simply use the Jeedom DNS.
* You already have a DNS name and you know how to produce a certificate, in this case it is a standard certificate installation.
* You do not have a DNS, and you do not mind using a self-signed certificate (remember that a self-signed certificate encrypts the data but does not provide the validation of the site), in this case follows the steps below, if using HTTPS is not already working:

[source,bash]
sudo su -
/usr/share/nginx/www/jeedom/install/install.sh nginx_ssl

You can then force HTTPS in the Jeedom configuration.

'''
I get the message: "You have too many Jeedom systems declared, please reduce the number and ask for a reset of your installation key". What should I do?::
Go on the Market, log in with your account then go to your profiles page and ask for a reset of the installation keys.

'''
What "event only" and "lifetime cache" means?::
* Event only: tells Jeedom to never request the value (it is the device / module that provides it). So when receiving a value, it is set as infinite lifetime (until reception of the next one).
* Lifetime cache: how long a value is valid, if you put 60 seconds for example, when the value get older than 60 sec AND jeedom needs the value (dashboard, scenario ...) then it will ask for the device / module to get an updated value.

Please note that these 2 options are reserved for advanced users who understand their function, a configuration error there can make the system unstable at worse inoperative. Eg with Zwave, RFXCOM and enocean the "event" box should ALWAYS be checked.

'''
How can I reset the permissions ?::
Connect with SSH and do the following: 
[source,bash]
sudo su -
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom

'''
Where are the backups of Jeedom?::
They are in the folder /usr/share/nginx/www/jeedom/backup

'''
How to update Jeedom from SSH?::
In ssh do : 

[source,bash]
sudo su -
php /usr/share/nginx/www/jeedom/install/install.php
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom

'''
La Webapp est-elle compatible Symbian ?::
La webapp necessite un smartphone supportant le HTML5 et le CSS3. Elle n'est donc malheureusement pas compatible Symbian.

'''
Sur quelles plateformes Jeedom peut-il fonctionner ?::
Pour que Jeedom fonctionne il faut une plateforme linux avec les droits root ou un système type docker. Il ne fonctionne donc pas sur une plateforme android pure.