= Principal

Jeedom is composed of a core which is on charge of basic functions : 

* scenario
* historisation
* display
* interaction
* update and saving

Around this core are grafted plugins that can be of any kind :
 
* protocole domotique (zwave, rfxcom, enOcean...)
* protocole IP (knx,xPL...)
* objet communiquant (nest, netatmo...)
* high level (alarm, thermostat...)
* interface (widget)
* organisation (agenda, Google agenda)
* développement (script)

Ces plugins peuvent être récuperés par le biais du market et permettent d'étendre les possibilités de Jeedom.

Jeedom permet à n'importe quel plugin de discuter avec un autre sur une base normalisée, cela permet par exemple d'utiliser les plugins thermostat ou alarme avec n'importe quel protocole domotique ou même un plugin IP ou objet communiquant...

De plus Jeedom a la particularité d'être sans abonnement et sans cloud. Cela permet de garantir le fonctionnement de votre domotique même si vous n'avez plus Internet. Cela garantit aussi la sécurité de vos données (évite les risques de piratage en masse de comptes).

Le projet étant ouvert et open-source, cela lui garantit aussi un fort taux d'évolution grâce aux nombreux contributeurs qui y participent.