= Sauvegarde et restauration

La sauvegarde et restauration de Jeedom permet de sauvegarder celui-ci et de le restaurer sur lui-même ou sur un autre Jeedom.

== Configuration

Accessible depuis Administration -> Sauvegarde, cette page permet la gestion des sauvegardes.

Sur cette page vous retrouvez à gauche les paramètres et les boutons d'action, et à droite le statut en temps réel de l'action en cours (sauvegarde en cours ou restauration), si vous en avez lancée une.

Sur la gauche on a : 

* *Sauvegardes*
** *Sauvegarde* : permet de lancer une sauvegarde immédiatement (utile si vous voulez faire un changement critique, cela vous permettra de revenir en arrière). Vous avez aussi un bouton pour lancer une sauvegarde sans envoyer l'archive sur le cloud (nécessite un abonnement voir plus bas), l'envoi de l'archive peut prendre du temps cela permet donc d'en gagner un peu.
** *Emplacement des sauvegardes* : endroit où Jeedom met les sauvegardes, il est recommandé de ne pas le changer. Si vous êtes en chemin relatif, alors son origine est l'endroit ou Jeedom est installé.
** *Nombre de jours de mémorisation des sauvegardes* : nombre de jours de sauvegarde à garder. Une fois ce délai passé les sauvegardes sont supprimées. Attention à ne pas mettre un nombre de jours trop élevé, sinon vous pouvez remplir votre système de fichiers.
** *Taille totale maximale des backups (Mo)* : Permet de limiter la taille totale des sauvegardes. Si cette valeur est dépassée alors Jeedom va supprimer les sauvegardes les plus vieilles jusqu'à retomber en-dessous de la taille maximale ou à garder une seule sauvegarde

* *Sauvegardes locales*
** *Sauvegardes disponibles* : liste des sauvegardes disponibles
** *Restaurer la sauvegarde* : lance la restauration de la sauvegarde sélectionnée au-dessus
** *Supprimer la sauvegarde* : supprime la sauvegarde sélectionnée au-dessus
** *Envoyer une sauvegarde* : vous permet d'envoyer à Jeedom une archive de sauvegarde (permet par exemple de restaurer une archive précédemment récupérée sur un nouveau Jeedom ou une réinstallation)
** *Télécharger la sauvegarde* : vous permet de récupérer l'archive de la sauvegarde sélectionnée au-dessus

* *Sauvegardes market*
** *Envoi des sauvegardes* : indique à Jeedom d'envoyer les sauvegardes au Market, attention il faut avoir pris l'abonnement.
** *Envoyer une sauvegarde* : vous permet d'envoyer sur le cloud une archive de sauvegarde
** *Sauvegardes disponibles* : liste des sauvegardes cloud disponibles
** *Restaurer la sauvegarde* : lance la restauration d'une sauvegarde cloud

* *Sauvegardes samba*
** *Envoi des sauvegardes* : indique à Jeedom d'envoyer les sauvegardes sur le partage samba configuré ici Administration->Configuration->Onglet mise à jours.
** *Sauvegardes disponibles* : liste des sauvegardes cloud disponibles
** *Restaurer la sauvegarde* : lance la restauration d'une sauvegarde cloud

[TIP]
Selon ce qui sera activé ou non dans la page Administration->Configuration->Onglet mise à jours, vous pouvez voir moins de sections.

[TIP]
Lors d'une réinstallation de Jeedom et en ayant pris l'abonnement de sauvegarde cloud, vous avez juste sur votre nouveau Jeedom à renseigner votre compte Market puis à venir ici pour lancer la restauration.

[TIP]
Il est possible, en cas de soucis, de faire un backup en ligne de commandes : `sudo php /usr/share/nginx/www/jeedom/install/backup.php` ou `sudo php /var/www/html/install/backup.php` selon votre système

[TIP]
Il est possible aussi de restaurer un backup en ligne de commandes (par défaut Jeedom restaure le backup le plus récent présent dans le répertoire de backup) : `sudo php /usr/share/nginx/www/jeedom/install/restore.php` ou `sudo php /var/www/html/install/restore.php`

== Qu'est-ce qui est sauvegardé ?

Lors d'une sauvegarde, Jeedom va sauvegarder tous ses fichiers et la base de données. Cela contient donc toute votre configuration (équipement, commande, historique, scénario, design...).

Au niveau des protocoles, seul le Z-Wave (OpenZwave) est un peu différent car il n'est pas possible de sauvegarder les inclusions. Celles-ci sont directement incluses dans le contrôleur, il faut donc garder le même pour tout retrouver.

== Sauvegarde cloud

La sauvegarde dans le cloud permet à Jeedom d'envoyer vos sauvegardes directement sur le Market. Cela vous permet de les restaurer facilement et d'être sûr de ne pas les perdre. Le Market conserve les 6 dernières sauvegardes. Pour vous abonner il suffit d'aller sur votre page profil sur le Market.
Puis dans l'onglet mes backups. Vous pouvez, à partir de cette page, récupérer un backup ou acheter un abonnement (pour 1, 3, 6 ou 12 mois).

[TIP]
Vous pouvez mettre un nom de sauvegarde plus sympa à partir de l'onglet "Mes Jeedoms" en donnant un nom à ceux-ci.

== Fréquence des backups

Jeedom effectue une sauvegarde tous les jours.Vous pouvez modifier cette heure à partir du "Moteur de tâches" (la tâche est nommée 'Jeedom backup') mais ce n'est pas recommandé car cette heure est calculée par rapport à la charge et l'heure de la sauvegarde du Market.