= Administración

Aquí están la mayoría de los ajustes de configuración. Muchos de ellos vienen pre configurados de manera predeterminada.

Puede acceder a través de Administración -> Configuración 


[IMPORTANTE]
Algunos parámetros pueden no ser visibles si no ha seleccionado el modo experto, 

== Générale

En esta ficha, encontrará información general sobre Jeedom: 

* * Nombre de Jeedom* : se puede reutlizar en los escenarios o permite identificar un backup
* *Clave API: la clave de la API a utilizar para cualquier aplicación en la API de Jeedom
* *Clave API Pro *: utilizado para conectar con el sistema de gestión de Parque
* *Clave de instalación* : clave de hardware de su Jeedom en el market. Si tu Jeedom no aparece en la lista de tus Jeedom en el market, es recomendable hacer clic en este botón 
* *Idioma* : Idioma de su Jeedom
* *Duración de sesión (tiempo)*: Duración de la sesión PHP; se aconseja no modificar este valor
* *Fecha y hora* : Su zona horaria
* *Servidor de tiempo opcional* : permite añadir un servidor de tiempo opcional (reservado para expertos) 
* *Ignorar la verificación horario* : indica a Jeedom que no verifique si la hora es coherente. Útil por ejemplo si no conecta Jeedom a Internet y no dispone de ninguna batería RTC

== API

Liste les differentes clef API de Jeedom : 

* le core à 2 clef API, une general (autant que possibile il faut eviter de l'utiliser) et pour les Pro (utilisée pour la gestion de parc)
* et une clef api par plugin en ayant besoin

Pour chaque clef API vous pouvez definir la porté : 

* *Désactiver* : la clef api ne peut etre utilisée
* *IP blanche* : seule une liste d'ip est autorisé (voir configuration réseaux)
* *Localhost* : seules les requetes venant du systeme lui meme sont autorisé
* *Activé* : aucune restriction

De plus vous pouvez aussi limité l'accès (par le meme systeme) aux APIs HTTP, JsonRpc et TTS

== OS/DB
 
=== Système

Permet d'accès à une interface d'administration systeme, sorte de console shell  (ATTENTION en touchant à cela le support peut refuser de vous aider)

=== Base de données

* *Administration* : permet d'accèder à une interface d'administration de la base en ligne de commande (ATTENTION en touchant à cela le support peut refuser de vous aider)
* *Máquina (hostname)* : Ubicación de la base de datos
* *Usuario* : Nombre de usuario utilizado por Jeedom
* *Contraseña* : Contraseña de accesso a la base de datos utilizada por Jeedom

== Sécurité

=== LDAP

* *Activar autentificaación LDAP* : Activar la autentificación a través de Active Directory (LDAP)
* *Anfitrión* : Servidor de Active Directory
* *Dominio* : Dominio de Active Directory
* *Base DN* : Base DN de Active Directory
* *Nombre de usuario* : Nombre de usuario para que Jeedom se conecte a Active Directory
* *Contraseña* : Contraseña para que Jeedom se conecte a Active Directory
* *Filtro (opcional)* : Filtro de Active Directory (para la gestión de grupos por ejemplo)
* *Permitir REMOTE_USER* : Activar REMOTE_USER (Utilizado en SSO por ejemplo)

=== Connexion

* *Nombre d'échec toléré* : defini le nombre de tentative successivent autorisées avant de bannir l'IP
* *Temps maximum entre les échecs (s)* : temps maximum pour que 2 tentatives soient considéré comme successive
* *Durée du bannissement (s), -1 pour infini* : temps de banissement de l'IP
* *IP "blanche"* : liste d'IP qui ne peuvent jamais etre banni

En dessous vous avez un tableau qui donne la liste des IP bannis

== Configuración de red

Parte muy importante en Jeedom, debe ser capaz de configurarlo correctamente, de lo contrario una gran cantidad de plugins pueden no ser no funcionales.

* *Acceso a internet* : Información para acceder a Jeedom desde un equipo de la misma red
** *Protocolo* : El protocolo a utilizar, normalmente HTTP
** *Dirección URL o IP* : IP de Jeedom para informar
** *Complemento (por ejemplo: /jeedom)* : Fragmento adicional de URL (escriba /jeedom). Para saber si debe definir este valor, vea si necesita añadir /jeedom después de la IP.
** *Puerto *: El puerto, generalmente 80. Atención, cambiar el puerto aquí no cambia el puerto real de Jeedom, que seguirá siendo el mismo.
** *Estado* : indica si la configuración de la red interna es correcta
** Acceso externo* : información para conectar a Jeedom desde el exterior. Rellenar sólo si no utilizas el DNS Jeedom
** *Protocolo* : Protocolo a utilizar para el acceso desde el exterior
** *Dirección URL o IP* : Dirección o IP externa si es fija
** *Complemento (por ejemplo: /jeedom)* : ruta adicional de la URL (escriba /jeedom). Para saber si debe definir este valor, vea si necesita añadir /jeedom después de la IP.
* *Gestion avancée* : peut ne pas apparaitre en fonction de la compatibilité avec votre matériel. Vous aurez ici la liste de vos interface réseaux
** *Desactivar la gestión de redes en Jeedom* : Jeedom no supervisará la red (deberá ser activado si Jeedom no está conectado a ninguna red)
* *Proxy market* : permite el acceso remoto a su Jeedom sin necesidad de un servidor DNS, una IP fija o puertos abiertos en su dispositivo
** *Usar DNS Jeedom* : Activar DNS Jeedom (se requiere disponer de un service pack)
** Estado DNS* : estado de http DNS
** *Gestión *: Permite detener y reiniciar el servicio DNS

[TIP]
Si accede a través de HTTPS, el puerto por defecto es el 443 y si lo hace a través de HTTP, el puerto por defecto es el 80

[IMPORTANTE]
Esta parte es para mostrar el entorno Jeedom: un cambio en el puerto o IP, no va a cambiar el puerto y la IP de Jeedom. Para ello debe conectarse por SSH y editar el archivo/etc/network/interfaces para la IP y los archivos etc/nginx/sitios-disponible/default y etc/nginx/sitios-disponible/default_ssl (para HTTPS). En caso de manipulación inadecuada de su configuración, el equipo de Jeedom no será responsable y podrá denegar cualquier solicitud de soporte.

[NOTA]
Puede ver el link:http://blog.domadoo.fr/2014/10/15/acceder-depuis-lexterieur-jeedom-en-https[aquí] un tutorial para instalar un certificado autofirmado

[IMPORTANTE]
Si no le es posible hacer funcionar DNS Jeedom, revise la configuración del firewall y el filtro parental de su router

== Couleurs

El ajuste de color de los widgets se realiza en función de la categoría a la que pertenece el widget que se define en la configuración de cada módulo (ver plugin de Z-Wave, RFXCOM... etc). Las categorías incluyen calefacción, luces, automatización etc ...

Para cada categoría se puede elegir un color diferente para la versión de escritorio y la versión móvil. También hay 2 tipos de colores, los colores de fondo de los widgets y colores de comandos color cuando el widget es de tipo gradual, por ejemplo, las luces, persianas, temperaturas.

Al hacer clic en el color, se abre una ventana que le permite seleccionar el color.

También puede ajustar la transparencia de los widgets en una forma global (que será el valor por defecto, es posible cambiar este valor widget por widget)

[TIP]
No olvide guardar los cambios después de hacer modificaciones

== Commandes

* *Histórico* : Ver link:https://jeedom.com/doc/documentation/core/es_ES/doc-core-history.html#_configuration_général_de_l_historique[aquí]
* *Push*
** *URL global de push*:  le permite añadir una dirección URL para invocarla en caso de actualización de un comando. Puede utilizar la etiqueta: \#valor# para el valor del comando, \#cmd_name# para el nombre del comando, \#cmd_id# para el identificador único del comando, \#humanname# para el nombre completo del comando (por ejemplo \#[Salle de bain][Hydrometrie][Humidité]#)

== Cache

Permet de surveiller et d'agir sur le cache de Jeedom : 

* *Statistiques* : Nombre d'objet actuellement en cache
* *Nettoyer le cache* : Force la suppression des objets qui ne sont plus utile (Jeedom le fait automatiquement toute les nuits)
* *Vider toutes les données en cache* : Vide completement le cache (attention cela peut faire perdre des données)
* *Temps de pause pour le long polling* : Fréquence a laquelle Jeedom verifie si il y a des evenements en attente pour les clients (interface web, application mobile...). Plus ce temps est cours plus l'interface se mettra à jour rapidement, en contre partie cela utilise plus de ressources et peut donc ralentir jeedom

== Interactions

Voir link:doc-core-interact.html#_configuration_2[ici]

== Rapports

Permet de configuration la generation et la gestion des raports

* *Delai d'attente après génération de la page (en ms)* : Délai d'attente après chargement du rapport pour faire la "photo", à changer si votre rapport est incomplet par exemple
* *Nettoyer les rapport plus anciens de (jours)* : défini le nombre de jour avant de supprimer un rapport (les rapports prennent un peu de place donc attention à ne pas mettre trop de conservation)

== Liens

Permet de configurer le graphique de lien

* *Profondeur pour les scénarios* : Permet de définir, lors de l'affichage d'un graphique de lien d'un scénario, le nombre d'élément maximum à afficher (plus il y a d'élément plus le graphique sera lent à générer et plus il sera difficile à lire)
* *Profondeur pour les objets* : idem pour les objets
* *Profondeur pour les équipements* : idem pour les équipements
* *Profondeur pour les commandes* : idem pour les commandes
* *Profondeur pour les variables* : idem pour les variables
* *Paramètre de prerender* : permet d'agir sur la disposition du graph
* *Paramètre de render* : idem

== Résumés

Permet d'ajouter des résumés d'objet (information affiché tout en haut dans la barre de menu Jeedom ou a coté des objets) : 

* *Clef* : clef du résumé, a ne surtout pas toucher
* *Nom* : Nom du résumé
* *Calcul* : Méthode de calcul, peut etre de type 
** *Somme* : somme les differentes valeur
** *Moyenne* : fait la moyenne des valeurs
** *Texte* : afficher textuellement la valeur (surtout pour celle de type chaine de caractere)
* *Icone* : icone du résumé
* *Unité* : unité du résumé
* *Méthode de comptage* : si vous compté une donnée binaire alors il faut mettre cette valeur a binaire, exemple si vous comptez ne nombre de lampe allumées mais que vous avez juste la valeur du variateur (0 à 100), alors il faut mettre binaire, comme cela jeedom considera que si la valeur est >1 alors Jeedom considera la lampe allumée 
* *Affiché si valeur égale 0* : masquer la valeur si elle vos 0 
* *Liée à un virtuel* : lance la création de commande virtuel ayant pour valeur celle du résumé

== Logs

Voir link:doc-core-log.html#_configuration[ici]

== Equipements

* *Número de fallos antes de la desactivación del dispositivo*: Número de errores de comunicación con el dispositivo antes de su desactivación (un mensaje le avisará si esto ocurre)
** Umbrales de batería* : le permite administrar los umbrales de alertas globales sobre las baterías

== Actualización y ficheros

* *Source de mise à jour* : choisir la source de mise à jour du core de jeedom
* *Version du core* : version du core à récuperer
* *Faire une sauvegarde avant la mise à jour* : indique si il faut faire une sauvegarde avant la mise à jour
* *Vérifier automatiquement s'il y a des mises à jour* : indique si il faut chercher automatiquement si il y a de nouvelle mise à jour (attention pour eviter de faire tomber le market l'heure de verification peut changer)

== Los Repositiorios

Los repositorio son espacios de almacenamiento (y servicio) para poder poner copias de seguridad, obtener plugins, recuperar la base de jeedom...

==== Archivo

Repositorio para activar el  envio de ficheros de plugin.

==== Github

Repositiorio utilizado para conectar Jeedom a Github

* *Token* : Token para el acceso al repositorio privado
* *Utilisateur ou organisation du dépôt pour le core Jeedom* : nom de l'utilisateur ou de l'organisation sur github pour le core
* *Nom du dépôt pour le core Jeedom* : nom du dépot pour le core
* *Branche pour le core Jeedom* : branche du dépot pour le core

==== Market

Servidor de repositiorios conectados al market de Jeedom, es recomendable utilizar este repositorio. Atención cualquier solicitud de soporte podrá ser denegada si usted utiliza otro repositorio diferente a este.

* *Dirección* : Dirección del market
* *Nombre de usuario* : Su nombre de usuario para el market
* *Contraseña* : Su contraseña para el market

==== Samba

Repositorio para enviar un backup automático de jeedom en un recurso compartido de samba (ej. NAS Synology)

* *[Backup] IP* : IP del servidor Samba
* *[Usuario backup] *: Nombre de usuario para la conexión (conexiones anónimas no son posibles)
* * L'utilisateur doit forcement avoir les droits lecture/ecriture sur ce repertoire
* *[Contraseña backup]* : contraseña del usuario
* *[Backup] recurso* : La ruta del recurso compartido (Asegúrese de indicar la ruta compartida correcta)
* *[Ruta Backup] * : Ruta para compartirr (para ser relativa),  debe existir

[NOTA]
SI la ruta de acceso a vuestra carpeta de backup samba es : \\192.168.0.1\Sauvegardes\Domotique\Jeedom
Si IP = 192.168.0.1 , Compartir = //192.168.0.1/Sauvegardes , ruta = Domotique/Jeedom

[NOTA]
Lors de la validation du partage samba, tel que décrit précédement, une nouvelle forme de sauvegarde apparait dans l'onglet
backup de jeedom. En l'activant, jeedom procedera à son envoi automatique lors du prochain backup. Un test est possible en
effectuant un backup manuel. Le log devra donc ressembler à ceci :

[IMPORTANTE]
Tal vez necesite instalar el paquete smbclient para que el repositorio funcione

[IMPORTANTE]
Jeedom debe poder escribir en esta carpeta, y debe estar vacía por defecto (es decir, que antes de hacer la configuración y enviar el primer Backup, la carpeta no puede contener ningún archivo o carpeta)

==== URL

* *URL core Jeedom*
* *URL version core Jeedom*