= API HTTP

Jeedom proporciona a los desarrolladores y usuarios una API completa para poder controlar cualquier objeto conectado.

Hay 2 APIs disponibles: una piloto orientada a desarrollado en JSON RPC 2.0 y otra vía URL y HTTP.

Cette API s'utilise très facilement par de simples requêtes HTTP via URL.

[NOTE]
Pour toute cette documentation, \#IP_JEEDOM# correspond à votre url d’accès à Jeedom. Il s’agit (sauf si vous êtes connecté à votre réseau local) de l’adresse internet que vous utilisez pour accéder à Jeedom depuis l’extérieur.

[NOTE]
Pour toute cette documentation, \#API_KEY# correspond à votre clé API, propre à votre installation. Pour la trouver, il faut aller dans le menu « Général », puis « Administration ».

== Scénario

Aquí la URL = http://\#IP_JEEDOM#/core/api/jeeApi.php?apikey=\#APIKEY#&type=scenario&id=\#ID#&action=\#ACTION#

* *id* :  correspond à l’id de votre scénario. L'ID se trouve sur la page des scénarios...(Ne pas oublier d'activer le mode Expert)
* *action* :  correspond à l'action que vous voulez appliquer au scénario. Les commandes disponibles sont : "start" pour démarrer un scénario ,"stop" pour arrêter un scénario ,"désactiver" pour désactiver un scénario ,"activer" pour activer un scénario
* *tags* [optionnel] : si l'action est start, vous pouvez passer des tags au scénario (voir doc scénario) sous la forme tags=toto%3D1%20tata%3D2 (a noter que %20 est pour un espace et %3D pour =)

== Info/Action commande

Aquí la URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=cmd&id=\#ID#

* *id* : correspond à l’id de ce que vous voulez piloter ou recevoir comme informations

Le plus simple pour avoir cette URL est d'aller sur la page Résumé domotique, de chercher la commande puis d'ouvrir sa configuration avancée et là vous allez voir une URL qui contient déjà tout ce qu'il faut en fonction du type et du sous-type de la commande.

[NOTE]
Il est possible pour le champs \#ID# de passer plusieurs commandes d'un coup, pour cela il faut passer un tableau en json (ex %5B12,58,23%5D, a noter que [ et ] doivent etre encodés d'où les %5B et %5D). Le retour de Jeedom sera un json

[NOTE]
Les paramètres doivent être encodés pour les url, voir https://meyerweb.com/eric/tools/dencoder/[ici]

== Interaction

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=interact&query=\#QUERY#

* *query* : question à poser à jeedom
* *utf8* [optionnel] : indique à jeedom si il faut encoder query en utf8 avant de chercher à répondre
* *emptyReply* [optionnel] : 0 pour que jeedom réponde même si il n'a pas compris, 1 sinon
* *profile* [optionnel] : nom d'utilisateur de la personne déclenchant l'interaction
* *reply_cmd* [optionnel] : ID de la commande à utiliser pour répondre à la demande

== Message

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=message&category=\#CATEGORY#&message=\#MESSAGE#

* *category* : catégorie du message à ajouter au centre de message
* *message* : message en question, attention à bien penser à encoder le message (espace devient %20, = %3D...)

== Objet

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=object

Renvoie en json la liste de tous les objets de jeedom

== Equipement

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=eqLogic&object_id=\#OBJECT_ID#

* *object_id* : ID de l'objet dont on veut récupérer les équipements

== Commande

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=command&eqLogic_id=\#EQLOGIC_ID#

* *eqLogic_id* : ID de l'équipement dont on veut récupérer les commandes

== Full Data

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=fullData

Renvoie tous les objets, équipements,commandes (et leur valeur si ce sont des infos) en json


