= Backup y restauración

La copia de seguridad y restauración de Jeedom permite guardar y restaurar en local o en otros Jeedom.

== Configuración

Accesible desde Administración -> Copia de seguridad, esta página permite la gestión de copias de seguridad.

En esta página puede encontrar a la izquierda la configuración y botones de acción y a la derecha el estado en tiempo real de la acción en curso (backup o restore), si se ha iniciado alguna.

A la izquierda: 

* *Backups*
** Backup* : permite iniciar una copia de seguridad inmediatamente (útil si usted quiere hacer un cambio crítico, esto le permitirá volver atrás). También tiene un botón para iniciar una copia de seguridad para enviar el archivo a la nube (requiere un suscripción, ver más abajo). El envío del archivo puede llevar tiempo, por lo tanto esto puede acelerar el proceso un poco.
** *Ubicación de las copias de seguridad* : donde guarda Jeedom las copias de seguridad, se recomienda no cambiarlo. Si usted está en la ruta relativa, entonces su origen es donde está instalado Jeedom.
** *Número de día(s) de respaldo de Backups*: número de días de respaldo a mantener. Una vez finalizado este período se eliminan las copias de seguridad anteriores. PRECAUCIÓN No coloque un número de días demasiado alto, de lo contrario usted puede llenar el sistema de archivos.
** *Taille totale maximale des backups (Mo)* : Permet de limiter la taille totale des sauvegardes. Si cette valeur est dépassée alors Jeedom va supprimer les sauvegardes les plus vieilles jusqu'à retomber en-dessous de la taille maximale ou à garder une seule sauvegarde

* *Backups locales*
**  *Backups disponibles* : lista de Backups disponibles
** *Restaurar desde Backup* : lanza la restauración seleccionando una copia de seguridad anterior
** *Eliminar Backup* : elimina las copias de seguridad os Backups seleccionados
** Enviar un Backup* : le permite a Jeedom cargar un archivo de copia de seguridad (permite por ejemplo, restaurar desde un archivo previamente salvado, en un nuevo Jeedom o tras una reinstalación)
**  *Descargar backup* : le permite descargar el archivo de una copia de seguridad anterior

* *Copias de seguridad del market*
** *Envío de copias de seguridad* : le pide a Jeedom que envíe copias de seguridad al market, así que tenga cuidado, necesita suscripción.
** *Enviar copia de seguridad* : le permite enviar un archivo de copia de seguridad a la nube
**  *Backups disponibles* : lista de copias de seguridad disponibles en la nube
** *Restaurar desde Backup* : inicia la restauración de una copia de seguridad desde la nube

* *Copias de seguridad Samba*
** *Envoi des sauvegardes* : indique à Jeedom d'envoyer les sauvegardes sur le partage samba configuré ici Administration->Configuration->Onglet mise à jours.
**  *Backups disponibles* : lista de copias de seguridad disponibles en la nube
** *Restaurar desde Backup* : inicia la restauración de una copia de seguridad desde la nube

[TIP]
Selon ce qui sera activé ou non dans la page Administration->Configuration->Onglet mise à jours, vous pouvez voir moins de sections.

[TIP]
Durante una reinstalación de Jeedom y habiendo abonado la suscripción de copia de seguridad en la nube, usted tiene derecho en su nuevo Jeedom introducir su cuenta del Market y luego venir aquí para iniciar la restauración.

[TIP]
Il est possible, en cas de soucis, de faire un backup en ligne de commandes : `sudo php /usr/share/nginx/www/jeedom/install/backup.php` ou `sudo php /var/www/html/install/backup.php` selon votre système

[TIP]
Il est possible aussi de restaurer un backup en ligne de commandes (par défaut Jeedom restaure la sauvegarde la plus récente présente dans le répertoire de sauvegarde) : `sudo php /usr/share/nginx/www/jeedom/install/restore.php` ou `sudo php /var/www/html/install/restore.php`

== ¿ Que es lo que se salva ?

Durante una copia de seguridad, Jeedom guardará todos sus archivos y la base de datos. Contiene por lo tanto su configuración (equipo, ordenes, historial, escenas, diseño...).

A nivel de los protocolos, sólo Z-Wave (OpenZwave) es un poco diferente porque no es posible guardar las inclusiones. Estos se incluyen directamente en el controlador, por lo tanto, mantener el mismo para todo.

== Nube de Backups

La sauvegarde dans le cloud permet à Jeedom d'envoyer vos sauvegardes directement sur le Market. Cela vous permet de les restaurer facilement et d'être sûr de ne pas les perdre. Le Market conserve les 6 dernières sauvegardes. Pour vous abonner il suffit d'aller sur votre page profil sur le Market.
Puis dans l'onglet mes backups. Vous pouvez, à partir de cette page, récupérer un backup ou acheter un abonnement (pour 1, 3, 6 ou 12 mois).

[TIP]
Puedes poner un nombre más adecuado a tus Backups en la pestaña "Mi Jeedoms" indicando un nombre.

== Frecuencia de los backups

Jeedom realiza una copia de seguridad cada día a las 2:00 de la mañana. Puede modificarse (esta es la copia de seguridad Jeedom) pero no es recomendable porque este horario se calcula en relación con la carga de trabajo y el tiempo de la copia de seguridad del Market.