= FAQ

Jeedom nécessite-t-il un abonnement ?::
Non, Jeedom ne nécessite pas d'abonnement pour son utilisation. Seul un service de sauvegarde en ligne optionnel est payant.

'''
Jeedom utilise-t-il des serveurs extérieurs pour fonctionner ?::
Non, Jeedom n'utilise pas d'infrastructure type "Cloud". Tout se fait en local et vous n'avez pas besoin de nos serveurs pour que votre installation fonctionne. Seuls les services comme le Market ou la sauvegarde online nécessitent l'utilisation de nos serveurs.

'''
Peut-on réordonner les commandes d'un équipement ?::
Oui c'est possible, il suffit de glisser/déposer les commandes de votre objet sur sa configuration.

'''
Peut-on éditer le style des widgets ?::
Oui c'est possible, soit en passant par le plugin widget, ou en utilisant la page Général -> Affichage

'''
Peut-on mettre plusieurs fois le même équipements sur un design ?::
Non ce n'est pas possible, mais vous pouvez dupliquer celui-ci grâce au plugin virtuel.

'''
Comment changer une donnée erronée de l'historique ?::
Il suffit sur une courbe historique de la commande, de cliquer sur le point en question. Si vous laissez le champs vierge, alors la valeur est supprimée.

'''
Comment enregistrer un ordinateur pour ne plus avoir à s'identifier ?::
Il suffit lors de la connexion de cocher la case "Enregistrer cet ordinateur".

'''
On me demande de mettre à jour Jeedom alors qu'il ne me propose rien, meme après vérification.::
C'est normal, pendant la phase de développement de la futur bêta, les numéros de version ne sont pas forcément incrémentés après chaque mise à jour.

'''
Combien de temps dure un backup ?::
Il n'y a pas de durée standard, cela dépend du système et du volume de données à sauvegarder, mais il peut prendre plus de 5 minutes, c'est normal.

'''
Y a-t-il une application mobile dédiée ?::
Jeedom possède une version mobile adaptée à l'utilisation sur mobile et tablette. Une application mobile est en cours de développement par l'équipe actuellement, aucune date de sortie n'est annoncée pour l'instant.
Il est tout à fait possible que des développeurs tiers proposent des applications dédiées pour Jeedom.

'''
Quels sont les identifiants pour me connecter la première fois ?::
Lors de votre première connexion à Jeedom (et même après si vous ne les avez pas modifiés), le nom d'utilisateur et le mot de passe par défaut sont admin/admin.
A la première connexion, il vous est fortement recommandé de modifier ces identifiants pour plus de sécurité.

'''
Comment externaliser la BDD ?::
Il suffit d'éditer le fichier /usr/share/nginx/www/jeedom/core/config/common.config.php.
Dans ce fichier se trouve la configuration de la base de données :

[source,php]
    $CONFIG = array(
        //MySQL parametres
        'db' => array(
            'host' => 'localhost',
            'port' => 3306,
            'dbname' => 'jeedom',
            'username' => 'jeedom',
            'password' => '************',
        )
    );

Il suffit de modifier les paramètres en fonction des identifiants de la base Jeedom sur le serveur MySQL.
Ejecutamos estos cambios : 

[source,bash]
sudo php /usr/share/nginx/www/jeedom/install/install.php

¡Listo!  

'''
Ou acheter la Mini+ ?::
La Jeedom Mini est commercialisée chez notre partenaire http://www.domadoo.fr/ .

'''
Quelle est la date de sortie de la Jeedom Center ?::
La Jeedom Center est prévue dans le courant de cette année.

'''
Quelle est le tarif de la Jeedom Center ?::
No hay precio aún anunciado.

'''
Impossible d'accéder à Jeedom de l'extérieur depuis l'achat d'une box::
Par défaut, Jeedom est à la racine de Nginx sur les box. Vous n'avez plus à rajouter /jeedom/ dans l'adresse d'accès. L'adresse exacte sera donc : votre_ip_public:votre_port/

'''
Peut on mettre Jeedom en https ?::
Oui, 3 possibilités :
* Vous avez un pack power ou plus, dans ce cas il vous suffit d'utiliser le DNS Jeedom.
* Soit avez un DNS et vous savez mettre en place un certificat valide, dans ce cas c'est une installation standard d'un certificat.
* Soit vous n'avez pas de DNS, et avoir un certificat auto-signé (pour rappel un certificat auto-signé assure le cryptage des données mais pas la validation du site) ne vous gêne pas, dans ce cas il faut faire ce qui suit, si ça ne marche pas quand vous mettez https devant l'URL :

[source,bash]
sudo su -
/usr/share/nginx/www/jeedom/install/install.sh nginx_ssl

Vous pouvez ensuite forcer le https dans la configuration Jeedom.

'''
J'ai le message : "Vous avez un trop grand nombre de système jeedom déclaré, veuillez en réduire le nombre et demander une réinitialisation de vos clefs d'installation", que faire ?::
Rendez vous sur le market, connectez-vous avec votre compte puis allez sur votre page profil et demandez une réinitilisation des clefs d'installation.

'''
Qu'est ce que événement seulement et lifetime cache ?::
* Événement seulement : indique à Jeedom de ne jamais demander la valeur (c'est l'équipement qui la remonte). Donc lors de la réception d'une valeur, celle-ci à une durée de vie infinie (jusqu’à la réception de la suivante).
* Lifetime cache : Durée de validité d'une valeur, si vous mettez 60 secondes par exemple, quand la valeur datera de plus de 60 secondes ET que jeedom en a besoin (dashboard, scénario...) alors il ira interroger le module pour avoir une valeur à jour.

Attention, ces 2 options sont reservées aux utilisateurs avancés qui comprennent parfaitement leur fonction, une erreur de configuration dans cette partie peut rendre une installation instable voire inopérante. Par exemple, en zwave, rfxcom et enocean, la case événement seulement devrait TOUJOURS etre cochée.

'''
Comment remettre à plat les droits ?::
En SSH faites : 
[source,bash]
sudo su -
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom

'''
Ou se trouve les backups de jeedom ?::
Están en la carpeta /usr/share/nginx/www/jeedom/backup

'''
Comment mettre à jour jeedom en SSH ?::
En ssh faites : 

[source,bash]
sudo su -
php /usr/share/nginx/www/jeedom/install/install.php
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom
