= Log

== Affichage

Le menu Logs permet de suivre ce qui se passe sur sa domotique. Dans la plupart des cas les logs ne serviront qu'à effectuer du debuggage et à résoudre des problèmes par l'équipe de support. Ce menu est d'ailleurs accessible uniquement en mode expert.

Pour y accèder il faut aller dans Administration -> Logs : 

La página de registros es bastante sencilla, en la parte superior izquierda veras un menú desplegable que permite la elección del registro a consultar, en la parte superior derecha hay 5 botones:

* *Rechercher* : permet de filtrer l'affiche de log
* *Pause/Reprendre* : permet de mettre en pause/reprendre la mise à jour en temps réel des logs
* *Télécharger* : permet de télécharger le log actuel,
* *Vider* : permet de vider le log actuel,
* *Supprimer* : permet de supprimer le log actuel, si Jeedom en a besoin il le recréera automatiquement,
* *Supprimer tous les logs* : supprime tous les logs présents.

[TIP]
A noter que le log http.error ne peut être supprimé. Il est essentiel ! si vous le supprimez (en ligne de commande par exemple) celui-ci ne se recréera pas tout seul, il faut redémarrer le système.

== Le log "Event"

Le log "Event" est un peu particulier. Tout d'abord pour qu'il fonctionne, il faut qu'il soit en niveau info ou debug, ensuite celui-ci recense tous les évènements ou actions qui se passent sur la domotique. Pour y accéder, il faut soit aller sur la page de log soit dans Analyse -> Temps réel

Une fois que vous avez cliqué dessus, vous obtenez une fenêtre qui se met à jour en temps réel et vous affiche tous les évènements de votre domotique.

Arriba a la derecha tienes un campo de búsqueda (sólo funcional cuando este pausado) y un botón de pausa (útil para hacer un copy/paste por ejemplo).