= Administration

C’est ici que se trouvent la plupart des paramètres de configuration. Bien que nombreux, ils sont pré-configurés par défaut.

La page est accessible par Administration -> Configuration : 

== Général

Dans cet onglet on retrouve des informations générales sur Jeedom : 

* *Nom de votre Jeedom* : peut être réutilisé dans les scénarios ou permettre d'identifier un backup
* *Système* : Type hardware du système sur lequel est installé Jeedom
* *Clef d'installation* : clef hardware de votre Jeedom sur le market. Si votre Jeedom n'apparaît pas dans la liste de vos Jeedom sur le market il est conseillé de cliquer sur le bouton *Remise à zéro*
* *Langue* : Langue de votre Jeedom
* *Générer les traductions* : permet de générer les traductions, attention peut ralentir votre système
* *Durée de vie des sessions (heure)* : durée de vie des sessions PHP, il déconseillé de toucher à ce paramètre
* *Date et heure* : votre fuseau horaire
* *Serveur de temps optionnel* : permet d'ajouter un serveur de temps optionnel (à réserver aux experts)
* *Ignorer la vérification de l'heure* : indique à Jeedom de ne pas vérifier si l'heure est cohérente. Utile par exemple si vous ne connectez pas Jeedom à Internet et qu'il n'a pas de pile RTC sur le hardware utilisé

== API

Liste les différentes clef API de Jeedom : 

* le core à 2 clef API, une générale (autant que possibile il faut éviter de l'utiliser) et pour les Pro (utilisée pour la gestion de parc)
* et une clef API par plugin en ayant besoin

Pour chaque clef API vous pouvez définir la portée : 

* *Désactiver* : la clef API ne peut être utilisée
* *IP blanche* : seule une liste d'ip est autorisée (voir configuration réseaux)
* *Localhost* : seules les requêtes venant du système lui-même sont autorisées
* *Activé* : aucune restriction

De plus vous pouvez aussi limiter l'accès (par le même système) aux APIs HTTP, JsonRpc et TTS

== OS/DB
 
=== Système

Permet l'accès à une interface d'administration système, sorte de console shell  (ATTENTION en touchant à cela le support peut refuser de vous aider)

=== Base de données

* *Administration* : permet d'accéder à une interface d'administration de la base en ligne de commande (ATTENTION en touchant à cela le support peut refuser de vous aider)
* *Machine (hostname)* : localisation de la base
* *Utilisateur* : nom d'utilisateur utilisé par Jeedom
* *Mot de passe* : mot de passe d'accès à la base utilisée par Jeedom

== Sécurité

=== LDAP

* *Activer l'authentification LDAP* : active l'authentification à travers un AD (LDAP)
* *Hôte* : serveur hébergeant l'AD
* *Domaine* : domaine de votre AD
* *Base DN* : base DN de votre AD
* *Nom d'utilisateur* : nom d'utilisateur pour que Jeedom se connecte à l'AD
* *Mot de passe* : mot de passe pour que Jeedom se connecte à l'AD
* *Filtre (optionnel)* : filtre sur l'AD (pour la gestion des groupes par exemple)
* *Autoriser REMOTE_USER* : Active le REMOTE_USER (utilisé en SSO par exemple)

=== Connexion

* *Nombre d'échec toléré* : défini le nombre de tentatives successives autorisées avant de bannir l'IP
* *Temps maximum entre les échecs (s)* : temps maximum pour que 2 tentatives soient considérées comme successives
* *Durée du bannissement (s), -1 pour infini* : temps de banissement de l'IP
* *IP "blanche"* : liste d'IP qui ne peuvent jamais être bannies

En dessous vous avez un tableau qui donne la liste des IP bannies

== Réseaux

Partie très importante dans Jeedom, il faut absolument la configurer correctement sinon beaucoup de plugins risquent d'être non fonctionnels.

* *Accès interne* : information pour joindre Jeedom à partir d'un équipement sur le même réseau (LAN)
** *Protocole* : le protocole à utiliser, souvent HTTP
** *Adresse URL ou IP* : IP de Jeedom, à renseigner
** *Complément (exemple : /jeedom)* : le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
** *Port* : le port, en général 80. Attention changer le port ici ne change pas le port réel de Jeedom qui restera le même
** *Statut* : indique si la configuration réseau interne est correcte
* *Accès externe* : information pour joindre Jeedom de l'extérieur. À ne remplir que si vous n'utilisez pas le DNS Jeedom
** *Protocole* : protocole utilisé pour l'accès extérieur
** *Adresse URL ou IP* : adresse ou IP externe si fixe
** *Complément (exemple : /jeedom)* :  le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
* *Gestion avancée* : peut ne pas apparaitre en fonction de la compatibilité avec votre matériel. Vous aurez ici la liste de vos interfaces réseaux
** *Désactiver la gestion du réseau par Jeedom* : indique à Jeedom de ne pas monitorer le réseau (à activer si Jeedom n'est connecté à aucun réseau)
* *Proxy market* : permet un accès distant à votre Jeedom sans avoir besoin d'un DNS, d'une IP fixe ou d'ouvrir les ports de votre box
** *Utiliser les DNS Jeedom* : active les DNS Jeedom (attention cela nécessite au moins un service pack)
** *Statut DNS* : statut du DNS HTTP
** *Gestion* : permet d'arrêter et relancer le service DNS

[TIP]
Si vous êtes en HTTPS le port est le 443 (par défaut) et en HTTP le port est le 80 (par défaut)

[IMPORTANT]
Cette partie est juste là pour expliquer à Jeedom son environnement : une modification du port ou de l'IP ici ne changera pas le port ou l'IP de Jeedom. Pour cela il faut se connecter en SSH et éditer le fichier /etc/network/interfaces pour l'IP et les fichiers etc/apache2/sites-available/default et etc/apache2/sites-available/default_ssl (pour le HTTPS). En cas de mauvaise manipulation de votre Jeedom, l'équipe Jeedom ne pourra être tenue pour responsable et pourra refuser toute demande de support.

[NOTE]
Vous pouvez voir link:http://blog.domadoo.fr/2014/10/15/acceder-depuis-lexterieur-jeedom-en-https[ici] un tutoriel pour mettre en place un certificat HTTPS auto-signé.

[IMPORTANT]
Si vous n'arrivez pas à faire fonctionner le DNS Jeedom, regardez la configuration du pare-feu et filtre parental de votre box (sur livebox il faut par exemple le pare-feu en moyen).

== Couleurs

La colorisation des widgets est effectuée en fonction de la catégorie d'appartenance du widget qui est définie dans la configuration de chaque module (voir plugin Z-Wave, RFXCOM, etc.). Parmi les catégories on retrouve le chauffage, les lumières, les automatismes etc.

Pour chaque catégorie, on pourra choisir une couleur différente entre la version desktop et la version mobile. Il y a également 2 types de couleur, les couleurs de fond des widgets et les couleurs des commandes lorsque le widget est de type graduel, par exemple les lumières, les volets, les températures.

En cliquant sur la couleur une fenêtre s'ouvre, permettant de choisir sa couleur.

Vous pouvez aussi configurer ici la transparence des widgets de manière globale (qui sera la valeur par défaut, il est possible ensuite de modifier cette valeur widget par widget).

[TIP]
N'oubliez pas de sauvegarder après toute modification.

== Commandes

=== Historique

* *Afficher les statistiques sur les widgets* : permet d'afficher ou non les statistiques sur les widgets ; il faut que le widget soit compatible, ce qui est le cas pour la plupart ; il faut aussi que la commande soit de type numérique
* *Période de calcul pour min, max, moyenne (en heures)* : période de calcul des statistiques (par défaut 24h), il n'est pas possible de mettre moins d'une heure
* *Période de calcul pour la tendance (en heures)* : période de calcul des tendances (par défaut 2h), il n'est pas possible de mettre moins d'une heure
* *Délai avant archivage (en heures)* : donne le délai avant archivage, par défaut la valeur est de 24h, c'est-à-dire que les données historisées doivent avoir plus de 24h pour être archivées (pour rappel, l'archivage va soit moyenner, soit prendre le maximum ou le minimum de la donnée sur une période qui correspond à la taille des paquets)
* *Archiver par paquet de (en heures)* : ce paramètre donne justement la taille des paquets, par défaut 1h ; cela signifie que Jeedom va prendre des périodes de 1h, moyenner (par exemple, suivant le réglage de la commande) et stocker cette nouvelle valeur (en supprimant les valeurs moyennées).
* *Seuil de calcul de tendance basse* : cette valeur correspond au seuil de tendance basse (Jeedom indique que la valeur est en baisse), il doit être négatif (par défaut -0.1).
* *Seuil de calcul de tendance haut* : idem mais à la tendance haute.
* *Période d'affichage des graphiques par défaut* : pour des questions de performance lors de l'affichage à la volée (en cliquant sur le widget ou par la page historique) Jeedom n'affiche qu'une période restreinte de l'historique (cela permet un affichage plus rapide) ; il est ici possible de régler cette valeur.

[NOTE]
Il est possible d'activer sur les widgets l'affichage du minimum, de la moyenne, du maximum et de la tendance (par défaut ceci est désactivé car cela a tendance à allonger le temps d'affichage du dashboard à cause des calculs). Si vous activez cette option, par défaut, Jeedom se fonde sur les données des dernières 24h pour calculer ces statistiques. Les tendances sont par défaut calculées sur 2h. Ce paramètre est bien sûr modifiable (voir plus bas).La méthode de calcul de tendance est fondée sur le calcul des moindres carrés (voir https://fr.wikipedia.org/wiki/M%C3%A9thode_des_moindres_carr%C3%A9s[ici] pour le détail).

=== Push

** *URL de push globale* :  permet de rajouter une URL à appeler en cas de mise à jour d'une commande. Vous pouvez utiliser les tags suivant : \#value# pour la valeur de la commande, \#cmd_name# pour le nom de la commande, \#cmd_id# pour l'identifiant unique de la commande, \#humanname# pour le nom complet de la commande (ex : \#[Salle de bain][Hydrometrie][Humidité]#)

== Cache

Permet de surveiller et d'agir sur le cache de Jeedom : 

* *Statistiques* : Nombre d'objets actuellement en cache
* *Nettoyer le cache* : Force la suppression des objets qui ne sont plus utiles (Jeedom le fait automatiquement toutes les nuits)
* *Vider toutes les données en cache* : Vide complètement le cache (attention cela peut faire perdre des données)
* *Temps de pause pour le long polling* : Fréquence à laquelle Jeedom vérifie si il y a des événements en attente pour les clients (interface web, application mobile...). Plus ce temps est cours plus l'interface se mettra à jour rapidement, en contre partie cela utilise plus de ressources et peut donc ralentir Jeedom

== Interactions

=== Général

Vous avez ici 3 paramètres : 

* *Sensibilité* : il y a 4 niveaux de correspondance (La sensibilité va de 1 (correspond exactement) à 99)
** pour 1 mot : le niveau de correspondance pour les interactions à un seul mot
** 2 mots : le niveau de correspondance pour les interactions à deux mots
** 3 mots : le niveau de correspondance pour les interactions à trois mots
** + de 3 mots : le niveau de correspondance pour les interactions à plus de trois mots
* *Ne pas répondre si l'interaction n'est pas comprise* : par défaut Jeedom répond "je n'ai pas compris" si l'interaction n'est pas comprise. Il est possible de désactiver ce fonctionnement pour que Jeedom ne réponde rien, mettre le bouton à oui pour désactiver la réponse.
* *Regex général d'exclusion pour les interactions* : permet de définir une regexp qui, si elle correspond à une interaction, supprimera automatiquement cette phrase de la génération (réservé aux experts). Pour plus d'informations voir les explications dans le chapitre *"Regexp d'exclusion"*

=== Interaction automatique, contextuelle & avertissement

Les interactions automatiques permettent à Jeedom de tenter de comprendre la commande même si il n'y a pas d'interaction définie (il va chercher un nom d'objet et/ou d'équipement et/ou de commande pour essayer de répondre le mieux possible)

Les interactions contextuelles vous permettent d'enchainer plusieurs demandes sans tout répéter, Jeedom gardant le contexte, exemple : 

* Vous : Combien fait-il dans la chambre ?
* Jeedom : Température 25.2 °C
* Vous : et dans le salon ?
* Jeedom : Température 27.2 °C

Il est aussi possible de poser 2 questions en une : 

* Vous : Combien fait-il dans la chambre et dans le salon ?
* Jeedom : Température 27.2 °C
		   Température 27.2 °C

Les interactions de type "préviens moi" permettent de demander à Jeedom de vous prévenir si une commande dépasse/descend ou vaut une certaine valeur. Ex :

* Vous : Préviens moi si la température du salon dépasse 25°C ?
* Jeedom : OK

Dès que la température du salon dépassera 25°C jeedom vous le dira (une seule fois)

[NOTE]
Par défaut Jeedom vous répondra par le même canal que celui que vous avez utilisé pour lui demander de vous prévenir. Si il n'en trouve pas alors il utilisera la commande par défaut spécifiée dans la configuration

* *Activer les interactions automatiques* : active les interactions automatiques
* *Activer les réponses contextuelles* : active les interactions contextuelles
* *Réponse contextuelle prioritaire si la phrase commence par* : si la phrase commence par le mot en question alors Jeedom va prioritiser une réponse contextuelle (vous pouvez mettre plusieurs mots en les séparant par des ;)
* *Découper une interaction en 2 si elle contient* : idem mais pour le découpage d'une interaction contenant plusieurs questions
* *Réponse de type "préviens moi" si la phrase commence par* : si la phrase commence par ce/ces mots alors Jeedom cherchera pour faire une interaction de type préviens moi (vous pouvez mettre plusieurs mots en les séparant par des ;)
* *Commande de retour par défaut* : commande de retour par défaut pour une interaction de type préviens (utilisé notament si vous avez programmé l'alerte par l'interface mobile)
* *Synonyme pour les objets* : liste des synomnymes pour les objets (ex : rdc|rez de chaussé|sous sol|bas;sdb|salle de bain)
* *Synonyme pour les équipements* : liste des synomnymes pour les équipements
* *Synonyme pour les commandes* : liste des synomnymes pour les commandes
* *Synonyme pour les résumé* : liste des synomnymes pour les résumés

=== Couleurs

Cette partie permet de définir les couleurs pour le pilotage des bandeaux de LED par exemple (pour que Jeedom comprenne les couleurs type rouge/bleu/noir...)

== Rapports

Permet de configurer la génération et la gestion des raports

* *Delai d'attente après génération de la page (en ms)* : Délai d'attente après chargement du rapport pour faire la "photo", à changer si votre rapport est incomplet par exemple
* *Nettoyer les rapports plus anciens de (jours)* : défini le nombre de jours avant de supprimer un rapport (les rapports prennent un peu de place donc attention à ne pas mettre trop de conservation)

== Liens

Permet de configurer le graphique de liens

* *Profondeur pour les scénarios* : Permet de définir, lors de l'affichage d'un graphique de liens d'un scénario, le nombre d'éléments maximum à afficher (plus il y a d'éléments plus le graphique sera lent à générer et plus il sera difficile à lire)
* *Profondeur pour les objets* : idem pour les objets
* *Profondeur pour les équipements* : idem pour les équipements
* *Profondeur pour les commandes* : idem pour les commandes
* *Profondeur pour les variables* : idem pour les variables
* *Paramètre de prerender* : permet d'agir sur la disposition du graph
* *Paramètre de render* : idem

== Résumés

Permet d'ajouter des résumés d'objets (information affichée tout en haut dans la barre de menu Jeedom ou à coté des objets) : 

* *Clef* : clef du résumé, à ne surtout pas toucher
* *Nom* : nom du résumé
* *Calcul* : méthode de calcul, peut être de type 
** *Somme* : somme les différentes valeurs
** *Moyenne* : fait la moyenne des valeurs
** *Texte* : afficher textuellement la valeur (surtout pour celles de type chaine de caractères)
* *Icone* : icone du résumé
* *Unité* : unité du résumé
* *Méthode de comptage* : si vous comptez une donnée binaire alors il faut mettre cette valeur à binaire, exemple si vous comptez le nombre de lampes allumées mais que vous avez juste la valeur du variateur (0 à 100), alors il faut mettre binaire, comme cela Jeedom considéra que si la valeur est >1 alors la lampe est allumée 
* *Afficher si valeur égale 0* : masquer la valeur si elle vaut 0 
* *Lier à un virtuel* : lance la création de commandes virtuelles ayant pour valeur celles du résumé

== Logs

Vous avez ici les options suivantes :

* *Message*
** *Ajouter un message à chaque erreur dans les logs* : si un plugin ou Jeedom écrit un message d'erreur dans un log, Jeedom ajoute automatiquement un message dans le centre des messages (au moins vous êtes sûr de ne pas le manquer)
** *Commande d'information utilisateur* : permet de sélectionner une ou plusieurs commandes (à séparer par des &&) de type message qui seront utilisées lors de nouveaux messages (permet d'être tout de suite prévenu)
* *Alertes*
** *Ajouter un message à chaque Timeout* : ajoute un message dans le centre de message si un équipement tombe en timeout
** *Commande sur Timeout* : commande de type message à utiliser si un équipement est en timeout
** *Ajouter un message à chaque Batterie en Warning* : ajoute un message dans le centre de messages si un équipement à son niveau de batterie en warning
** *Commande sur Batterie en Warning* : commande de type message à utiliser si un équipement à son niveau de batterie en warning
** *Ajouter un message à chaque Batterie en Danger* : ajoute un message dans le centre de messages si un équipement à son niveau de batterie en danger
** *Commande sur Batterie en Danger* : commande de type message à utiliser si un équipement à son niveau de batterie en danger
** *Ajouter un message à chaque Warning* : ajoute un message dans le centre de messages si une commande passe en alerte warning
** *Commande sur Warning* : commande de type message à utiliser si une commande passe en alerte warning
** *Ajouter un message à chaque Danger* : ajoute un message dans le centre de messages si une commande passe en alerte danger
** *Commande sur Danger* : commande de type message à utiliser si une commande passe en alerte danger
* *Log* 
** *Moteur de log* : permet de changer le moteur de log pour par exemple les envoyer à un demon syslog(d)
** *Format des logs* : Format de logs à utiliser (attention ça n'affecte pas les logs des démons)
** *Nombre de lignes maximum dans un fichier de log* : Définit le nombre maximum de lignes dans un fichier de log, il est recommandé de ne pas toucher cette valeur, car une valeur trop grande pourrait remplir le système de fichiers et/ou rendre Jeedom incapable d'afficher le log
** *Niveau de log par défaut* : niveau de log par défaut de Jeedom

En dessous vous retrouvez un tableau permettant de gérer finement le niveau de log par type ou plugin de Jeedom

== Equipements

* *Nombre d'échecs avant désactivation de l'équipement* : nombre d'échecs de communication avec l'équipement avant désactivation de celui-ci (un message vous préviendra si cela arrive)
* *Seuils des piles* : permet de gérer les seuils d'alertes globaux sur les piles

== Mise à jour et fichiers

* *Source de mise à jour* : choisir la source de mise à jour du core de Jeedom
* *Version du core* : version du core à récupérer
* *Faire une sauvegarde avant la mise à jour* : indique si il faut faire une sauvegarde avant la mise à jour
* *Vérifier automatiquement s'il y a des mises à jour* : indique si il faut chercher automatiquement si il y a de nouvelle mise à jour (attention pour éviter de faire tomber le market l'heure de vérification peut changer)

=== Les dépôts

Les dépôts sont des espaces de stockage (et de service) pour pouvoir mettre des backups, récupérer des plugins, récupérer le core de Jeedom, etc.

==== Fichier

Dépôt servant à activer l'envoi de plugins par des fichiers.

==== Github

Dépôt servant à relier Jeedom à Github.

* *Token* : token pour l'accès au dépôt privé
* *Utilisateur ou organisation du dépôt pour le core Jeedom* : nom de l'utilisateur ou de l'organisation sur github pour le core
* *Nom du dépôt pour le core Jeedom* : nom du dépôt pour le core
* *Branche pour le core Jeedom* : branche du dépôt pour le core

==== Market

Dépôt servant à relier Jeedom au market, il est vivement conseillé d'utiliser ce dépôt. Attention toute demande de support pourra être refusée si vous utilisez un autre dépôt que celui-ci.

* *Adresse* : adresse du Market
* *Nom d'utilisateur* : votre nom d'utilisateur sur le Market
* *Mot de passe* : votre mot de passe du Market

==== Samba

Dépôt permettant d'envoyer automatiquement un backup de Jeedom sur un partage Samba (ex NAS Synology).

* *[Backup] IP* : IP du serveur Samba
* *[Backup] Utilisateur* : nom d'utilisateur pour la connexion (les connexions anonymes ne sont pas possibles)
* * L'utilisateur doit forcement avoir les droits lecture/écriture sur ce répertoire
* *[Backup] Mot de passe* : mot de passe de l'utilisateur
* *[Backup] Partage* : chemin du partage (attention à bien s'arrêter au niveau du partage)
* *[Backup] Chemin* : chemin dans le partage (à mettre en relatif), celui-ci doit exister

[NOTE]
Si le chemin d'accès à votre dossier de sauvegarde samba est : \\192.168.0.1\Sauvegardes\Domotique\Jeedom
Alors IP = 192.168.0.1 , Partage = //192.168.0.1/Sauvegardes , Chemin = Domotique/Jeedom

[NOTE]
Lors de la validation du partage samba, tel que décrit précédement, une nouvelle forme de sauvegarde apparait dans l'onglet
backup de Jeedom. En l'activant, Jeedom procedera à son envoi automatique lors du prochain backup. Un test est possible en
effectuant un backup manuel.

[IMPORTANT]
Il vous faudra peut-être installer le package smbclient pour que le dépôt fonctionne.

[IMPORTANT]
Jeedom doit être le seul à écrire dans ce dossier et il doit être vide par défaut (c'est à dire avant la configuration et l'envoi du premier backup, le dossier ne doit contenir aucun fichier ou dossier).

==== URL

* *URL core Jeedom*
* *URL version core Jeedom*
