= Administration

C’est ici que se trouvent la plupart des paramètres de configuration. Bien que nombreux, ils sont pré-configurés par défaut.

La page est accessible par Administration -> Configuration : 


[IMPORTANT]
Si vous n'êtes pas en mode expert certains paramètres peuvent ne pas être visibles.

== Générale

Dans cet onglet on retrouve des informations générales sur Jeedom : 

* *Nom de votre Jeedom* : peut être réutilisé dans les scénarios ou permettre d'identifier un backup
* *Système* : Type hardware du systeme sur lequelle est installé jeedom
* *Clef d'installation* : clef hardware de votre Jeedom sur le market. Si votre Jeedom n'apparaît pas dans la liste de vos Jeedom sur le market il est conseillé de cliquer sur le bouton *Remise à zéro*
* *Langue* : Langue de votre Jeedom
* *Générer les traductions* : permet de générer les traductions, attention peut ralentir votre système
* *Durée de vie des sessions (heure)* : durée de vie des sessions PHP, il est conseillé de ne pas y toucher
* *Date et heure* : votre fuseau horaire
* *Serveur de temps optionnel* : permet d'ajouter un serveur de temps optionnel (à réserver aux experts)
* *Ignorer la vérification de l'heure* : indique à Jeedom de ne pas vérifier si l'heure est cohérente. Utile par exemple si vous ne connectez pas Jeedom à Internet et qu'il n'a pas de pile RTC

== API

Liste les differentes clef API de Jeedom : 

* le core à 2 clef API, une general (autant que possibile il faut eviter de l'utiliser) et pour les Pro (utilisée pour la gestion de parc)
* et une clef api par plugin en ayant besoin

Pour chaque clef API vous pouvez definir la porté : 

* *Désactiver* : la clef api ne peut etre utilisée
* *IP blanche* : seule une liste d'ip est autorisé (voir configuration réseaux)
* *Localhost* : seules les requetes venant du systeme lui meme sont autorisé
* *Activé* : aucune restriction

De plus vous pouvez aussi limiter l'accès (par le même système) aux APIs HTTP, JsonRpc et TTS

== OS/DB
 
=== Système

Permet d'accès à une interface d'administration systeme, sorte de console shell  (ATTENTION en touchant à cela le support peut refuser de vous aider)

=== Base de données

* *Administration* : permet d'accèder à une interface d'administration de la base en ligne de commande (ATTENTION en touchant à cela le support peut refuser de vous aider)
* *Machine (hostname)* : localisation de la base
* *Utilisateur* : nom d'utilisateur utilisé par Jeedom
* *Mot de passe* : mot de passe d'accès à la base utilisée par Jeedom

== Sécurité

=== LDAP

* *Activer l'authentification LDAP* : active l'authentification à travers un AD (LDAP)
* *Hôte* : serveur hébergeant l'AD
* *Domaine* : domaine de votre AD
* *Base DN* : base DN de votre AD
* *Nom d'utilisateur* : nom d'utilisateur pour que Jeedom se connecte à l'AD
* *Mot de passe* : mot de passe pour que Jeedom se connecte à l'AD
* *Filtre (optionnel)* : filtre sur l'AD (pour la gestion des groupes par exemple)
* *Autoriser REMOTE_USER* : Active le REMOTE_USER (utilisé en SSO par exemple)

=== Connexion

* *Nombre d'échec toléré* : defini le nombre de tentative successivent autorisées avant de bannir l'IP
* *Temps maximum entre les échecs (s)* : temps maximum pour que 2 tentatives soient considéré comme successive
* *Durée du bannissement (s), -1 pour infini* : temps de banissement de l'IP
* *IP "blanche"* : liste d'IP qui ne peuvent jamais etre banni

En dessous vous avez un tableau qui donne la liste des IP bannis

== Configuration réseau

Partie très importante dans Jeedom, il faut absolument la configurer correctement sinon beaucoup de plugins risquent d'être non fonctionnels.

* *Accès interne* : information pour joindre Jeedom à partir d'un équipement sur le même réseau
** *Protocole* : le protocole à utiliser, souvent HTTP
** *Adresse URL ou IP* : IP de Jeedom, à renseigner
** *Complément (exemple : /jeedom)* : le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
** *Port* : le port, en général 80. Attention changer le port ici ne change pas le port réel de Jeedom qui restera le même
** *Statut* : indique si la configuration réseau interne est correcte
* *Accès externe* : information pour joindre Jeedom de l'extérieur. À ne remplir que si vous n'utilisez pas le DNS Jeedom
** *Protocole* : protocole utilisé pour l'accès extérieur
** *Adresse URL ou IP* : adresse ou IP externe si fixe
** *Complément (exemple : /jeedom)* :  le fragment d'URL complémentaire (type /jeedom). Pour savoir si vous avez besoin de définir une valeur ici, regardez si quand vous vous connectez à Jeedom vous devez renseigner /jeedom après l'IP
* *Gestion avancée* : peut ne pas apparaitre en fonction de la compatibilité avec votre matériel. Vous aurez ici la liste de vos interface réseaux
** *Désactiver la gestion du réseau par Jeedom* : indique à Jeedom de ne pas monitorer le réseau (à activer si Jeedom n'est connecté à aucun réseau)
* *Proxy market* : permet un accès distant à votre Jeedom sans avoir besoin d'un DNS, d'une IP fixe ou d'ouvrir les ports de votre box
** *Utiliser les DNS Jeedom* : active les DNS Jeedom (attention cela nécessite au moins un service pack)
** *Statut DNS* : statut du DNS HTTP
** *Gestion* : permet d'arrêter et relancer le service DNS

[TIP]
Si vous êtes en HTTPS le port est le 443 (par défaut) et en HTTP le port est par défaut le 80

[IMPORTANT]
Cette partie est juste là pour expliquer à Jeedom son environnement : une modification du port ou de l'IP ici ne changera pas le port ou l'IP de Jeedom. Pour cela il faut se connecter en SSH et éditer le fichier /etc/network/interfaces pour l'IP et les fichiers etc/nginx/sites-available/default et etc/nginx/sites-available/default_ssl (pour le HTTPS). En cas de mauvaise manipulation de votre Jeedom, l'équipe Jeedom ne pourra être tenue pour responsable et pourra refuser toute demande de support.

[NOTE]
Vous pouvez voir link:http://blog.domadoo.fr/2014/10/15/acceder-depuis-lexterieur-jeedom-en-https[ici] un tutoriel pour mettre en place un certificat HTTPS auto-signé.

[IMPORTANT]
Si vous n'arrivez pas à faire fonctionner le DNS Jeedom, regardez la configuration du pare-feu et filtre parental de votre box (sur livebox il faut par exemple le pare-feu en moyen).

== Couleurs

La colorisation des widgets est effectuée en fonction de la catégorie d'appartenance du widget qui est définie dans la configuration de chaque module (voir plugin Z-Wave, RFXCOM... etc). Parmi les catégories on retrouve le chauffage, les lumières, les automatismes etc...

Pour chaque catégorie, on pourra choisir une couleur différente entre la version desktop et la version mobile. Il y a également 2 types de couleurs, les couleurs de fond des widgets et les couleurs des commandes lorsque le widget est de type graduel, par exemple les lumières, les volets, les températures.

En cliquant sur la couleur une fenêtre s'ouvre, permettant de choisir sa couleur.

Vous pouvez aussi configurer ici la transparence des widgets de manière globale (qui sera la valeur par défaut, il est possible ensuite de modifier cette valeur widget par widget).

[TIP]
N'oubliez pas de sauvegarder après toute modification.

== Commandes

=== Historique

* *Afficher les statistiques sur les widgets* : permet d'afficher ou non les statistiques sur les widgets ; il faut que le widget soit compatible, ce qui est le cas pour la plupart ; il faut aussi que la commande soit de type numérique
* *Période de calcul pour min, max, moyenne (en heures)* : période de calcul des statistiques (par défaut 24h), il n'est pas possible de mettre moins d'une heure
* *Période de calcul pour la tendance (en heures)* : période de calcul des tendances (par défaut 2h), il n'est pas possible de mettre moins d'une heure
* *Délai avant archivage (en heures)* : donne le délai avant archivage, par défaut la valeur est de 24h, c'est-à-dire que les données historisées doivent avoir plus de 24h pour être archivées (pour rappel, l'archivage va soit moyenner, soit prendre le maximum ou le minimum de la donnée sur une période qui correspond à la taille des paquets)
* *Archiver par paquet de (en heures)* : ce paramètre donne justement la taille des paquets, par defaut 1h ; cela signifie que Jeedom va prendre des périodes de 1h, moyenner (par exemple, suivant le réglage de la commande) et stocker cette nouvelle valeur (en supprimant les valeurs moyennées).
* *Seuil de calcul de tendance basse* : cette valeur correspond au seuil de tendance basse (Jeedom indique que la valeur est en baisse), il doit être négatif (par défaut -0.1).
* *Seuil de calcul de tendance haut* : idem mais à la tendance haute.
* *Période d'affichage des graphiques par defaut* : pour des questions de performance lors de l'affichage à la volée (en cliquant sur le widget ou par la page historique) Jeedom n'affiche qu'une période restreinte de l'historique (cela permet un affichage plus rapide) ; il est ici possible de régler cette valeur.

[NOTE]
Il est possible d'activer sur les widgets l'affichage du minimum, de la moyenne, du maximum et de la tendance (par défaut ceci est désactivé car cela a une tendance à allonger le temps d'affichage du dashboard à cause des calculs). Si vous activez cette option, par défaut, Jeedom se fonde sur les données des dernières 24h pour calculer ces statistiques. Les tendances sont par défaut calculées sur 2h. Ce paramètre est bien sûr modifiable (voir plus bas).La méthode de calcul de tendance est fondée sur le calcul des moindres carrés (voir https://fr.wikipedia.org/wiki/M%C3%A9thode_des_moindres_carr%C3%A9s[ici] pour le détail).

=== Push

** *URL de push globale* :  permet de rajouter une URL à appeler en cas de mise à jour d'une commande. Vous pouvez utiliser les tags suivant : \#value# pour la valeur de la commande, \#cmd_name# pour le nom de la commande, \#cmd_id# pour l'identifiant unique de la commande, \#humanname# pour le nom complet de la commande (ex : \#[Salle de bain][Hydrometrie][Humidité]#)

== Cache

Permet de surveiller et d'agir sur le cache de Jeedom : 

* *Statistiques* : Nombre d'objet actuellement en cache
* *Nettoyer le cache* : Force la suppression des objets qui ne sont plus utile (Jeedom le fait automatiquement toute les nuits)
* *Vider toutes les données en cache* : Vide completement le cache (attention cela peut faire perdre des données)
* *Temps de pause pour le long polling* : Fréquence a laquelle Jeedom verifie si il y a des evenements en attente pour les clients (interface web, application mobile...). Plus ce temps est cours plus l'interface se mettra à jour rapidement, en contre partie cela utilise plus de ressources et peut donc ralentir jeedom

== Interactions

Voir link:doc-core-interact.html#_configuration_2[ici]

== Rapports

Permet de configuration la generation et la gestion des raports

* *Delai d'attente après génération de la page (en ms)* : Délai d'attente après chargement du rapport pour faire la "photo", à changer si votre rapport est incomplet par exemple
* *Nettoyer les rapport plus anciens de (jours)* : défini le nombre de jour avant de supprimer un rapport (les rapports prennent un peu de place donc attention à ne pas mettre trop de conservation)

== Liens

Permet de configurer le graphique de lien

* *Profondeur pour les scénarios* : Permet de définir, lors de l'affichage d'un graphique de lien d'un scénario, le nombre d'élément maximum à afficher (plus il y a d'élément plus le graphique sera lent à générer et plus il sera difficile à lire)
* *Profondeur pour les objets* : idem pour les objets
* *Profondeur pour les équipements* : idem pour les équipements
* *Profondeur pour les commandes* : idem pour les commandes
* *Profondeur pour les variables* : idem pour les variables
* *Paramètre de prerender* : permet d'agir sur la disposition du graph
* *Paramètre de render* : idem

== Résumés

Permet d'ajouter des résumés d'objet (information affiché tout en haut dans la barre de menu Jeedom ou a coté des objets) : 

* *Clef* : clef du résumé, a ne surtout pas toucher
* *Nom* : Nom du résumé
* *Calcul* : Méthode de calcul, peut etre de type 
** *Somme* : somme les differentes valeur
** *Moyenne* : fait la moyenne des valeurs
** *Texte* : afficher textuellement la valeur (surtout pour celle de type chaine de caractere)
* *Icone* : icone du résumé
* *Unité* : unité du résumé
* *Méthode de comptage* : si vous compté une donnée binaire alors il faut mettre cette valeur a binaire, exemple si vous comptez ne nombre de lampe allumées mais que vous avez juste la valeur du variateur (0 à 100), alors il faut mettre binaire, comme cela jeedom considera que si la valeur est >1 alors Jeedom considera la lampe allumée 
* *Affiché si valeur égale 0* : masquer la valeur si elle vos 0 
* *Liée à un virtuel* : lance la création de commande virtuel ayant pour valeur celle du résumé

== Logs

Voir link:doc-core-log.html#_configuration[ici]

== Equipements

* *Nombre d'échecs avant désactivation de l'équipement* : nombre d'échecs de communication avec l'équipement avant desactivation de celui-ci (un message vous préviendra si cela arrive)
* *Seuils des piles* : permet de gérer les seuils d'alertes globaux sur les piles

== Mise à jour et fichiers

* *Source de mise à jour* : choisir la source de mise à jour du core de jeedom
* *Version du core* : version du core à récuperer
* *Faire une sauvegarde avant la mise à jour* : indique si il faut faire une sauvegarde avant la mise à jour
* *Vérifier automatiquement s'il y a des mises à jour* : indique si il faut chercher automatiquement si il y a de nouvelle mise à jour (attention pour eviter de faire tomber le market l'heure de verification peut changer)

=== Les dépots

Les dépôts sont des espaces de stockage (et de service) pour pouvoir mettre des backups, récupérer des plugins, récupérer le core de jeedom....

==== Fichier

Dépôt servant à activer l'envoi de plugins par des fichiers.

==== Github

Dépôt servant à relier Jeedom à Github.

* *Token* : token pour l'accès au dépôt privé
* *Utilisateur ou organisation du dépôt pour le core Jeedom* : nom de l'utilisateur ou de l'organisation sur github pour le core
* *Nom du dépôt pour le core Jeedom* : nom du dépot pour le core
* *Branche pour le core Jeedom* : branche du dépot pour le core

==== Market

Dépôt servant à relier Jeedom au market, il est vivement conseillé d'utiliser ce dépôt. Attention toute demande de support pourra être refusée si vous utilisez un autre dépôt que celui-ci.

* *Adresse* : adresse du Market
* *Nom d'utilisateur* : votre nom d'utilisateur sur le Market
* *Mot de passe* : votre mot de passe du Market

==== Samba

Dépôt permettant d'envoyer automatiquement un backup de Jeedom sur un partage Samba (ex NAS Synology).

* *[Backup] IP* : IP du serveur Samba
* *[Backup] Utilisateur* : nom d'utilisateur pour la connexion (les connexions anonymes ne sont pas possibles)
* * L'utilisateur doit forcement avoir les droits lecture/ecriture sur ce repertoire
* *[Backup] Mot de passe* : mot de passe de l'utilisateur
* *[Backup] Partage* : chemin du partage (attention à bien s'arrêter au niveau du partage)
* *[Backup] Chemin* : chemin dans le partage (à mettre en relatif), celui-ci doit exister

[NOTE]
Si le chemin d'accès à votre dossier de sauvegarde samba est : \\192.168.0.1\Sauvegardes\Domotique\Jeedom
Alors IP = 192.168.0.1 , Partage = //192.168.0.1/Sauvegardes , Chemin = Domotique/Jeedom

[NOTE]
Lors de la validation du partage samba, tel que décrit précédement, une nouvelle forme de sauvegarde apparait dans l'onglet
backup de jeedom. En l'activant, jeedom procedera à son envoi automatique lors du prochain backup. Un test est possible en
effectuant un backup manuel. Le log devra donc ressembler à ceci :

[IMPORTANT]
Il vous faudra peut-être installer le package smbclient pour que le dépôt fonctionne.

[IMPORTANT]
Jeedom doit être le seul à écrire dans ce dossier et il doit être vide par défaut (c'est à dire avant la configuration et l'envoi du premier backup, le dossier ne doit contenir aucun fichier ou dossier).

==== URL

* *URL core Jeedom*
* *URL version core Jeedom*
