= API HTTP

Jeedom met à disposition des développeurs et des utilisateurs une API complète afin de pouvoir piloter Jeedom depuis n'importe quel objet connecté.

Deux API sont disponibles : une orientée développeur qui se pilote en JSON RPC 2.0, et une autre via URL et requête HTTP.

Cette API s'utilise très facilement par de simples requêtes HTTP via URL.

[NOTE]
Pour toute cette documentation \#IP_JEEDOM# correspond à votre url d’accès à Jeedom. Il s’agit (sauf si vous êtes connecté à votre réseau local) de l’adresse internet que vous utilisez pour accéder à Jeedom depuis l’extérieur.

[NOTE]
Pour toute cette documentation \#API_KEY# correspond à votre clé API, propre à votre installation. Pour la trouver il faut aller dans le menu « Général », puis « Administration »

== Scénario

Voici l'URL = http://\#IP_JEEDOM#/core/api/jeeApi.php?apikey=\#APIKEY#&type=scenario&id=\#ID#&action=\#ACTION#

* *id* :  correspond à l’id de votre scénario. L'ID se trouve sur la page des scénarios...(Ne pas oublier d'activer le mode Expert)
* *action* :  correspond à l'action que vous voulez appliquer au scénario. Les commandes disponibles sont : "start" pour démarrer un scénario ,"stop" pour arrêter un scénario ,"désactiver" pour désactiver un scénario ,"activer" pour activer un scénario
* *tags* [optionnel] : si l'action est start vous pouvez passer des tags au scénario (voir doc scénario) sous la forme tags=toto%3D1%20tata%3D2 (a noter que %20 est pour un espace et %3D pour =)

== Info/Action commande

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=cmd&id=\#ID#

* *id* : correspond à l’id de ce que vous voulez piloter ou recevoir comme informations

Le plus simple pour avoir cette URL est d'aller sur la page Résumé domotique, de chercher la commande puis d'ouvrir sa configuration avancée et là vous allez voir une URL qui contient déjà tout ce qu'il faut en fonction du type et du sous-type de la commande.

[NOTE]
Il est possible pour le champs \#ID# de passer plusieurs commande d'un coup, pour cela il faut passer un tableau en json (ex %5B12,58,23%5D, a noter que [ et ] doivent etre encodé d'ou les %5B et %5D). Le retour de Jeedom sera un json

[NOTE]
Les parametres doivent etre encoder pour les url, voir https://meyerweb.com/eric/tools/dencoder/[ici]

== Interaction

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=interact&query=\#QUERY#

* *query* : question à poser à jeedom
* *utf8* [optionnel] : indique à jeedom si il faut encoder query en utf8 avant de chercher à répondre
* *emptyReply* [optionnel] : 0 pour que jeedom réponde meme si il n'a pas compris, 1 sinon
* *profile* [optionnel] : nom d'utilisateur de la personne déclenchant l'interaction

== Message

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=message&category=\#CATEGORY#&message=\#MESSAGE#

* *category* : categorie du message à ajouter au centre de message
* *message* : message en question, attention a bien penser à encoder le message (espace devient %20, = %3D...)

== Objet

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=object

Renvoi en json la liste de tous les objets de jeedom

== Equipement

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=eqLogic&object_id=\#OBJECT_ID#

* *object_id* : ID de l'objet dont on veut récuperer les équipements

== Commande

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=command&eqLogic_id=\#EQLOGIC_ID#

* *eqLogic_id* : ID de l'équipement dont on veut récuperer les commande

== Full Data

Voici l'URL = http://\#IP_JEEDOM#/jeedom/core/api/jeeApi.php?apikey=\#APIKEY#&type=fullData

Renvoi toutes les objets,equipement,commande (et leur valeur si c'est des infos) en json



