Voici un petit guide pour bien débuter avec Jeedom (car oui Jeedom peut faire un peu peur au premier abord).

Dans un premier temps je vais juste décrire le matériel type pour commencer :

=== Les box

- Mini : http://www.domadoo.fr/fr/informatique/2575-jeedom-pack-de-demarrage-jeedom-mini-z-wave.html
- Mini + RFXCOM : http://www.domadoo.fr/fr/informatique/2576-jeedom-pack-de-demarrage-jeedom-mini-z-wave-rfxcom.html
- Carte SD préinstallé : http://www.domadoo.fr/fr/informatique/2571-jeedom-carte-micro-sd-avec-logiciel-jeedom-pre-installe.html

=== DIY
Le plus simple du Z-wave partout il faut :

- Un raspberry  ~ 40 €
- Un razberry ~ 60 €
- Une carte SD ~ 7 €
- Alimentation USB ~ 8 €
Soit un total de 115€ pour une box domotique open-source avec une maîtrise complète de son installation

Idem mais en plus performant (par la même occasion plus cher et un peu plus compliqué à mettre en place) :

- Un cubieboard  ~ 70 €
- Un razberry ~ 60 €
- Alimentation USB ~ 8 €
Plus cher 138 € mais avec un système nettement plus performant (bien que Jeedom soit pleinement utilisable sous un raspberry il faut avoué que le raspberry est un peu poussif pour les plus exigeants)

Il faut installer le razberry (je passe l’installation du système en lui même il faut juste installer Debian )


----
wget -q -O – razberry.z-wave.me/install | sudo bash
----

Pour l’installation  de Jeedom il suffit de suivre la page d’explication

Ensuite pour ce qui est des équipements, Jeedom est compatible avec autant de matériel que le razberrry (dans ceux qui ont été testé  : Fibaro Wall Plug, Fibaro Variateur, Fibaro relais 2 charges, Everspring ST814, Aeon Multisensors ).

Ensuite vous avez accès à toutes les fonctions des modules.

Pour les plus aventureux il est possible d’utiliser des Jeenodes (il faut les assembler, mettre le code dedans…. mais ça permet vraiment de tout contrôler :-) )

En espérant que cet article vous donne envie de vous lancer ! :-)
