[panel,primary]
.Jeedom nécessite t'il un abonnement ?
--
Non, Jeedom ne nécessite pas d'abonnement pour son utilisation. Seul un service de sauvegarde en ligne optionnel est payant.
--

[panel,primary]
.Jeedom utilise t'il des serveurs extérieurs pour fonctionner ?
--
Non, Jeedom n'utilise pas d'infrastructure type "Cloud". Tous se fait en local et vous n'avez pas besoin de nos serveurs pour que votre installation fonctionne. Seuls les services comme le Market ou la sauvegarde online nécessitent l'utilisation de nos serveurs.
--

[panel,primary]
.Peut-on utiliser une clé usb zwave à la place du Razberry ?
--
Jeedom est conçu à la base pour fonctionner avec la carte Razberry. Cependant un plugin Openzwave actuellement en développement permettra la compatibilité de Jeedom avec les clés usb zwave (notamment zwave plus).
--

[panel,primary]
.Peut on reordonner les équipements sur le dashboard
--
Non ce n'est pas possible, mais il existe les vues pour ça
--

[panel,primary]
.Peut on reordonner les commandes d'un équipement
--
Oui c'est possible il suffit de glisser/deposer les commandes de votre objets sur ça configuration
--

[panel,primary]
.Peut on éditer le style des widgets
--
Oui c'est possible soit en passant par le plugin widget, ou en utilisant la page generale -> Affichage
--

[panel,primary]
.Peut on mettre plusieurs fois le meme équipements sur un design
--
Non ce n'est pas possible, mais vous pouvez dupliquer celui-ci grace au plugin virtuel
--

[panel,primary]
.Comment changer une donner erronée de l'historique
--
Il suffit sur une courbe historique de la commande de cliquer sur le point en question. Si vous laissez le champs alors la valeur est supprimé
--

[panel,primary]
.Comment enregistrer un ordinateur pour ne plus avoir à s'identifier
--
Il suffit lors de la connexion de cocher la case "Enregistrer cer ordinateur"
--

[panel,primary]
.On me demande de mettre à jour jeedom alors qu'il ne me propose rien meme après verification
--
C'est normale, pendant la pahse de developpement de la futur beta les numéros de version ne sont pas incrementés après chaque mise à jour
--

[panel,primary]
.Combien de temp doit durer un backup
--
Il n' a pas de durée standard, cela depend du systeme mais il peut prendre plus de 5min, c'est normale
--

[panel,primary]
.Y a t'il une application mobile dédiée ?
--
Il n'y a pas d'application mobile en développement par l'équipe actuellement. Néanmoins Jeedom possède une version mobile adaptée à l'utilisation sur mobile et tablette.
Il est tout à fait possible que des développeurs tiers réalisent dans le future des applications dédiées pour Jeedom.
--

[panel,primary]
.Quels sont les identifiants pour me connecter la première fois ?
--
Lors de votre première connexion à Jeedom (et même après si vous ne les avez pas modifiés) le nom d'utilisateur et le mot de passe par défaut sont admin. Il est fortement conseillé de les modifier pour plus de sécurité.
--

[panel,primary]
.Comment externaliser la BDD ?
--
Il suffit d'éditer le fichier /usr/share/nginx/www/jeedom/core/config/common.config.php.
Dans ce fichier se trouve la configuration de la base de données :

----
    $CONFIG = array(
        //MySQL parametres
        'db' => array(
            'host' => 'localhost',
            'port' => 3306,
            'dbname' => 'jeedom',
            'username' => 'jeedom',
            'password' => '************',
        )
    );
----

Il suffiit de modifier les paramètres en fonction des identifiants de la base Jeedom sur le serveur MySQL.
On exécute ces changements :

----
sudo php /usr/share/nginx/www/jeedom/install/install.php
----

Le tour est joué ! 
--

[panel,primary]
.Ou acheter la mini ?
--
La Jeedom Mini est commercialisée chez notre partenaire http://www.domadoo.fr/ à partir de 119.00€
--

[panel,primary]
.Quelle est la date de sortie de la Jeedom Center ?
--
La Jeedom Center est prévue pour début l'année 2015.
--

[panel,primary]
.Quelle est le tarif de la Jeedom Center ?
--
Il n'y a pas de tarif annoncé pour le moment.
--

[panel,primary]
.Impossible d'accéder à Jeedom de l'extérieur depuis l'achat d'une box
--
Par défaut Jeedom est à la racine de Nginx sur les box. Vous n'avez plus à rajouter /jeedom/ dans l'adresse d'accès. L'adresse exacte sera donc : votre_ip_public:votre_port/
--

[panel,primary]
.Peut on mettre Jeedom en https
--
Oui, 2 possibilités, soit avez un DNS et vous savez mettre en place un certificat valide, dans ce cas c'est une installation standard d'un certificat. Soit vous n'avez pas de DNS, et avoir un certificat auto-signé (pour rappel un certificat auto-signé assure le cryptage des données mais pas la validation du site) ne vous gène pas, dans ce cas il faut faire ce qui suit, si ça ne marche pas quand vous mettez https devant l'URL : 

----
sudo su -
/usr/share/nginx/www/jeedom/install/install.sh nginx_ssl
----

Vous pouvez ensuite forcer le https dans la configuration Jeedom.

--

[panel,primary]
.J'ai le message : "Vous avez un trop grand nombre de système jeedom déclaré, veuillez en réduire le nombre et demander une réinitialisation de vos clefs d'installation" que faire ?
--
Rendez vous sur le market, connectez vous avec votre compte puis aller sur votre page profils et demandez une reinitilisation de clefs d'installation
--

[panel,primary]
.Qu'est ce que evenement seulement et  lifetime cache ?
--

- Évènement seulement : indique à Jeedom de ne jamais demander la valeur (c'est l'équipement qui la remonte). Donc lors de la réception d'une valeur, celle-ci a une durée de vie infinie (jusqu’à la réception suivante).
- Lifetime cache : Durée de validité d'une valeur, si vous mettez 60 secondes par exemple, quand la valeur datetera de plus de 60 ET que jeedom en a besoin (dashboard, scénario...) alors il ira interroger le module pour avoir une valeur à jour

Attention ces 2 options sont reservées aux utilisateurs avancés qui comprennent parfaitement leur fonction, une erreur de configuration la dedans peut rendre une installation instable voir inopérante. Par exemple en zwave, rfxcom et enocean la case evenement seulement devrait TOUJOURS etre cochée
--

[panel,primary]
.Comment remettre à plat les droits ?
--
En ssh faites : 
----
sudo su -
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom
----
--

[panel,primary]
.Ou se trouve les backups de jeedom ?
--
Ils sont dans le dossier /usr/share/nginx/www/jeedom/backup
--

[panel,primary]
.Comment mettre à jour jeedom en SSH ?
--
En ssh faites : 
----
sudo su -
php /usr/share/nginx/www/jeedom/install/install.php
chmod -R 775 /usr/share/nginx/www/jeedom
chown -R www-data:www-data /usr/share/nginx/www/jeedom
----
--
