==== Général

Jeedom nécessite t'il un abonnement ?:::
Non, Jeedom ne nécessite pas d'abonnement pour son utilisation. Seul un service de sauvegarde en ligne optionnel est payant.

Jeedom utilise t'il des serveurs extérieurs pour fonctionner ?:::
Non, Jeedom n'utilise pas d'infrastructure type "Cloud". Tous se fait en local et vous n'avez pas besoin de nos serveurs pour que votre installation fonctionne. Seuls les services comme le Market ou la sauvegarde online nécessitent l'utilisation de nos serveurs.

Peut-on utiliser une clé usb zwave à la place du Razberry ?:::
Jeedom est conçu à la base pour fonctionner avec la carte Razberry. Cependant un plugin Openzwave actuellement en développement permettra la compatibilité de Jeedom avec les clés usb zwave (notamment zwave plus).

==== Version desktop

J'ai une page blanche quand j'accède à @ip/jeedom:::
N'oubliez pas de mettre le deuxième "/" après jeedom, ce qui donnera @ip/jeedom/

==== Version mobile

Il y a t'il une application mobile dédiée ?:::
Il n'y a pas d'application mobile en développement par l'équipe actuellement. Néanmoins Jeedom possède une version mobile adaptée à l'utilisation sur mobile et tablette.
Il est tout à fait possible que des développeurs tiers réalisent dans le future des applications dédiées pour Jeedom.

==== Divers

Quels sont les identifiants pour me connecter la première fois ?:::
Lors de votre première connexion à Jeedom (et même après si vous ne les avez pas modifiés) le nom d'utilisateur et le mot de passe par défaut sont admin. Il est fortement conseillé de les modifier pour plus de sécurité.

Page blanche suite à une mise a jour ou à une installation ?:::
Il faut regarder le log : /usr/share/nginx/www/jeedom/log/nginx.error (commande en ssh : tail /usr/share/nginx/www/jeedom/log/nginx.error)
Souvent c'est un problème de mot de passe de la BDD, pour le réinitialiser il faut : 

----
bdd_password=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 15)
echo "DROP USER 'jeedom'@'localhost'" | mysql -uroot -p
echo "CREATE USER 'jeedom'@'localhost' IDENTIFIED BY '${bdd_password}';" | mysql -uroot -p
echo "GRANT ALL PRIVILEGES ON jeedom.* TO 'jeedom'@'localhost';" | mysql -uroot -p
cd /usr/share/nginx/www/jeedom
sudo cp core/config/common.config.sample.php core/config/common.config.php
sudo sed -i -e "s/#PASSWORD#/${bdd_password}/g" core/config/common.config.php 
sudo chown www-data:www-data core/config/common.config.php
----

Comment externaliser la BDD ?:::
Il suffit d'éditer le fichier /usr/share/nginx/www/jeedom/core/config/common.config.php.
Dans ce fichier se trouve la configuration de la base de données :

----
    $CONFIG = array(
        //MySQL parametres
        'db' => array(
            'host' => 'localhost',
            'port' => 3306,
            'dbname' => 'jeedom',
            'username' => 'jeedom',
            'password' => '************',
        )
    );
----

Il suffiit de modifier les paramètres en fonction des identifiants de la base Jeedom sur le serveur MySQL.
On exécute ces changements :

----
sudo php /usr/share/nginx/www/jeedom/install/install.php
----

Le tour est joué ! 
