Partie au combien importante : comment installer le projet ?

Les instructions suivantes sont valables uniquement pour ubuntu/debian, elles seront donc à adapter pour d’autres systèmes Linux (j’ai jamais testé Jeedom sous Windows et bien qu’en théorie ça marche il doit y avoir quelques modifications à faire).

Voici donc les commandes pour une installation type sous Raspberry  (en root):

=== Mode simple
[source,shell]
----
wget -q http://git.jeedom.fr/jeedom/core/raw/stable/install/install.sh; sudo chmod 777 install.sh; sudo ./install.sh
----

Et vous n’avez plus qu’a suivre les instructions

Ensuite aller sur IP_MACHINE/jeedom (les identifiants étant admin/admin)

=== Mode détaillé
Récupération des fichiers
[source,shell]
----
apt-get update
apt-get install git git-core git-man
apt-get install nginx-common  nginx-full
apt-get install mysql-client mysql-common mysql-server mysql-server-core-5.5
apt-get install nodejs php5-common php5-fpm php5-cli php5-curl php5-json php5-mysql
sudo mkdir -p /usr/share/nginx/www
cd /usr/share/nginx/www
sudo chown www-data:www-data -R /usr/share/nginx/www
sudo -u www-data -H git clone –depth=1 -b stable http://git.jeedom.fr/jeedom/core.git jeedom
sudo chmod 775 -R /usr/share/nginx/www

mkdir /usr/share/nginx/www/jeedom/core/class/../../tmp

chmod 777 -R /usr/share/nginx/www/jeedom/core/class/../../tmp
cd jeedom
sudo cp jeedom /etc/init.d/
sudo chmod +x /etc/init.d/jeedom
sudo update-rc.d jeedom defaults
sudo service jeedom start
----

=== Configuration de la BDD
Se connecter à MySQL (avec le mot de passe tapé précédemment) :

[source,shell]
----
mysql -uroot -p
----

Création de l’utilisateur MySQL (ne pas oublier de remplacer #PASSWORD# par le mot de passe voulu) :

[source,shell]
----
CREATE USER ‘jeedom’@’localhost’ IDENTIFIED BY ‘#PASSWORD#';
CREATE DATABASE jeedom;
GRANT ALL PRIVILEGES ON jeedom.* TO ‘jeedom’@’localhost’
----

Installation de la BDD
Aller dans le répertoire d’installation de Jeedom

[source,shell]
----
cd /usr/share/nginx/www/jeedom
----

Copier le fichier core/config/common.config.sample.php en core/config/common.config.php

[source,shell]
----
sudo -u www-data -H cp core/config/common.config.sample.php core/config/common.config.php
----

Éditer le fichier configuration pour mettre les informations de connexion à la base de données

[source,shell]
----
vi core/config/common.config.php
----

Il faut juste compléter le TODO par le mot de passe tapé précédemment. Sauvegarder puis lancer l’installation :

[source,shell]
----
php install/install.php
----

=== Configuration de nginx
[source,shell]
----
Editer le fichier /etc/nginx/sites-available/default
----

[source,shell]
----
vi /etc/nginx/sites-available/default
----

Puis ajouter les lignes suivante entre “server{” et sa balise fermante “}”

[source,shell]
----
location / {
try_files $uri $uri/ /index.html /index.php;
}

location /nodeJS/ {
proxy_set_header X-NginX-Proxy true;
proxy_pass http://127.0.0.1:8070/;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection “upgrade”;
proxy_set_header Host $host;
proxy_redirect off;
}

location /socket.io/ {
proxy_pass http://127.0.0.1:8070/socket.io/;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection “upgrade”;
proxy_set_header Host $host;
proxy_redirect off;
}

location ~ \.php$ {
try_files $uri =404;
fastcgi_pass unix:/var/run/php5-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
}
----

=== Redémarrer nginx

[source,shell]
----
sudo service nginx restart
----


A partir de la vous devriez pouvoir accéder à Jeedom avec IP_MACHINE/jeedom avec comme identifiant : admin/admin (si erreur 403 essayez IP_MACHINE/jeedom/index.php)

Ajouter la tâche Jeedom à la crontab
Il faut ajouter la ligne suivante dans la crontab :

[source,shell]
----
* * * * * su --shell=/bin/bash - www-data -c "/usr/bin/php /usr/share/nginx/www/jeedom/core/php/jeeCron.php" >> /dev/null 2>&1
----

Pour ce faire il faut taper la commande suivante :

[source,shell]
----
crontab -e
----

Voilà l’installation est finie

=== Mise à jour
Pour les mises à jour c’est facile 2 possibilités :

- En ligne de commande
[source,shell]
----
cd /usr/share/nginx/www/jeedom
php install/install.php
----
- Par l’interface de jeedom dans Général -> Administration -> Mises à jour

Voilà normalement ça devrait marcher (bien que l’ayant déjà fait plusieurs fois j’ai fait la procédure de tête donc si il y a la moindre erreur ou amélioration n’hésitez pas à me le dire ;-) )
