= Log

== Affichage

Le menu Logs permet de suivre ce qui se passe sur sa domotique. Dans la plupart des cas les logs ne serviront qu'à effectuer du debuggage et à résoudre des problèmes par l'équipe de support. 

Pour y accéder il faut aller dans Analyse -> Logs : 

La page de Logs contient à gauche la liste des logs à visualiser, ainsi qu'un champs de recherche du nom du log.

En haut à droite vous avez 5 boutons :

* *Rechercher* : permet de filtrer l'affichage du log
* *Pause/Reprendre* : permet de mettre en pause/reprendre la mise à jour en temps réel des logs
* *Télécharger* : permet de télécharger le log actuel,
* *Vider* : permet de vider le log actuel,
* *Supprimer* : permet de supprimer le log actuel. Si Jeedom en a besoin il le recréera automatiquement,
* *Supprimer tous les logs* : supprime tous les logs présents.

[TIP]
A noter que le log http.error ne peut être supprimé. Il est essentiel ! si vous le supprimez (en ligne de commande par exemple) celui-ci ne se recréera pas tout seul, il faudra alors redémarrer le système.

== Le log "jeeEvent"

Le log "jeeEvent" est un peu particulier : tout d'abord, pour qu'il fonctionne, il faut qu'il soit en niveau *info* ou *debug*, ensuite celui-ci recense tous les évènements ou actions qui se passent sur la domotique. Pour y accéder, il faut soit aller sur la page de log soit aller dans Analyse -> Temps réel.

Une fois que vous avez cliqué dessus, vous obtenez une fenêtre qui se met à jour en temps réel et vous affiche tous les évènements de votre domotique.
