= Dépannage

== J'ai une page blanche

Il faut se connecter en SSH à jeedom et lancer un script d'auto-diagnostic : 

[source,bash]
sudo chmod +x /var/www/html/health.sh;sudo /var/www/html/health.sh

S'il y a un souci, le script essaie de corriger, s'il n'y arrive pas il vous l'indiquera.

Vous pouvez aussi regarder le log /var/www/html/http.error, très souvent celui-ci indique le souci

== J'ai un problème d'identifiant BDD

Il faut réinitialiser ceux-ci
[source,bash]
bdd_password=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 15)
echo "DROP USER 'jeedom'@'localhost'" | mysql -uroot -p
echo "CREATE USER 'jeedom'@'localhost' IDENTIFIED BY '${bdd_password}';" | mysql -uroot -p
echo "GRANT ALL PRIVILEGES ON jeedom.* TO 'jeedom'@'localhost';" | mysql -uroot -p
cd /usr/share/nginx/www/jeedom
sudo cp core/config/common.config.sample.php core/config/common.config.php
sudo sed -i -e "s/#PASSWORD#/${bdd_password}/g" core/config/common.config.php 
sudo chown www-data:www-data core/config/common.config.php

== J'ai des {{...}} partout

La cause la plus fréquente est l'utilisation d'un plugin en version beta, et Jeedom en stable, ou l'inverse. Pour avoir le détails de l'erreur il faut regarder le log http.error (dans /var/www/html/log)

== Lors d'une commande, j'ai une roue qui tourne sans s'arrêter

Encore une fois cela est souvent dû à un plugin en beta alors que Jeedom est en stable. Pour voir l'erreur, il faut faire F12 puis console

== Je n'ai plus accès à Jeedom ni en SSH

Cette erreur n'est pas due à Jeedom mais à un problème avec le système. Si celui-ci persiste suite à une réinstallation il est conseillé de voir avec le SAV pour un souci hardware

== Mon scénario ne s'arrête plus/pas

Il est conseillé de regarder les commandes exécutées par le scénario, souvent cela vient d'une commande qui ne se termine pas

== Mon scénario est lent à se déclencher

Si dans le scénario il n'y a pas de pause il est conseillé de cocher la case "éxécuter le plus rapidement possible"

== J'ai des instabilités ou des erreurs 504

Vérifiez si votre système de fichiers n'est pas corrompu, en ssh la commande est : "sudo dmesg | grep error"

== Je ne vois pas tous mes équipements sur le dashboard

Souvent cela est dû au fait que les équipements sont affectés à un objet qui n'est pas le fils ou l'objet lui-même du premier objet sélectionné à gauche dans l'arbre (vous pouvez dans votre profil configurer celui-ci)

== Lors de la connexion du maître avec les esclaves j'ai des erreurs

Vérifiez que vous avez bien mis les /jeedom si vous utilisez ceux-ci juste après l'IP de jeedom (souvent le cas en installation DIY)

== J'ai l'erreur suivante : SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

Cela est dû à MySQL qui s'est arrêté, ce n'est pas normal, les cas courants sont : 

* souci de place sur le système de fichiers (peut être vérifié en faisant la commande "df -h", en ssh)
* problème de corruption de fichier(s), arrive souvent suite à un arrêt non propre de Jeedom (coupure de courant)

Malheureusement, il n'y a pas beaucoup de solution si c'est le deuxième cas, le mieux étant de récupérer un backup (disponible dans /usr/share/nginx/www/jeedom/backup par défaut), de réinstaller Jeedom et de restaurer le backup. Vous pouvez aussi en ssh regarder pourquoi mysql ne veut pas démarrer : 
[source,bash]
sudo su -
service mysql stop
mysqld --verbose

Ou consulter le log : /var/log/mysql/error.log

== Les boutons Eteindre/Redémarrer ne fonctionnent pas

Sur une installation DIY c'est normal, il faut faire en ssh la commande visudo et à la fin du fichier vous devez ajouter : www-data ALL=(ALL) NOPASSWD: ALL.

[source,bash]
sudo service apache2 restart

== Je ne vois pas certains plugins du Market

Ce genre de cas arrive si votre Jeedom n'est pas compatible avec le plugin, en général une mise à jour de jeedom corrige le souci
