= Centre de mise à jour

Le centre de mise à jour centralise l'ensemble des fonctions de Jeedom, et permet de mettre à jour toutes les fonctionnalités de Jeedom, incluant le logiciel de base, les plugins, les widgets, etc...

Il est accessible par le menu Administration -> Centre de mise à jour : 

Il présente sous forme de tableau l'ensemble des éléments installés dans Jeedom. 

[TIP]
En mode Expert, on affiche tous les élements, si non, on affiche uniquement les éléments à mettre à jour.

En haut du tableau se trouvent les boutons de commande. Jeedom se connecte périodiquement avec le Market pour voir si des mises à jour sont disponibles (la date de dernière vérification est indiquée tout en haut du tableau à gauche). Si vous voulez réaliser une vérification manuelle, vous pouvez appuyer sur le bouton "Vérifier les mises à jour".

Le bouton "Mettre à jour" permet de mettre à jour l'ensemble de Jeedom :

* *Tout forcer* : met à jour Jeedom et les plugins en mode forcé c'est-à-dire que même s'il y a une erreur Jeedom continue et ne restaurera pas la sauvegarde
* *Plugins seulement* : met à jour seulement les plugins
* *Plugins seulement forcés* : met à jour seulement les plugins en mode forcé (continue en cas d'erreur)
* *Jeedom seulement* : met à jour seulement Jeedom
* *Jeedom seulement forcés* : met à jour seulement Jeedom en mode forcé c'est-à-dire que même s'il y a une erreur Jeedom continue et ne restaurera pas la sauvegarde
* *Réappliquer une mise à jour* : permet de réappliquer une mise à jour. Toutes les mises à jour ne peuvent être réappliquées. En cliquant dessus vous obtenez cette fenêtre : 

[IMPORTANT]
Avant une mise à jour, Jeedom va par défaut faire une sauvegarde. En cas de souci lors de l'application d'une mise à jour, Jeedom va automatiquement restaurer la sauvegarde faite juste avant. Ce principe n'est bien sûr valable que pour les mises à jour de Jeedom et non des plugins.

[TIP]
Vous pouvez forcer une mise à jour de Jeedom meme si celui-ci ne vous en propose pas

Dans le tableau vous retrouvez la liste des plugins (sur le premiere onglet et des widgets et autre élements sur le deuxieme), sur chaque ligne vous pouvez faire : 

* *Reinstaller* : force la reinstallation du plugin en question
* *Supprimer* : permet de désinstaller un élément
* *Verifier* : vérifie si l'élement en question à une mise à jour
* *Mettre à jour* : permet de mettre à jour l'élément (si celui-ci à une mise à jour)
* *Changelog* : permet de voir les changement de la mise à jour

[IMPORTANT]
Si le changelog est vide mais que vous avez une mise à jour quand meme cela signifie juste que c'est la documentation qui a été mise à jour, il n'est donc pas necessaire de demander au développeur les changements vu qu'il n'y en as pas forcement (c'est souvent juste une mise à jour de la traduction de la documentation)

[TIP]
A noter que "core : jeedom" signifie la mise à jour du logiciel de base Jeedom.

== Mise à jour en ligne de commande

Il est possible de faire une mise à jour de Jeedom directement en SSH, voici comment faire : 

----
sudo php /var/www/html/install/install.php
----

Voilà les paramètres possibles :

* *mode* : force, pour lancer une mise à jour en mode forcé (ne tiens pas compte des erreurs)
* *version* : numéro de version, pour réapliquer les changements depuis cette version

Exemple pour faire une mise à jour forcée en réappliquant les changements depuis la 1.188.0 : 

----
sudo php  /var/www/html/install/install.php mode=force version=1.188.0
----

Attention, après une mise à jour en ligne de commande, il faut réappliquer les droits sur le dossier Jeedom :

----
chown -R www-data:www-data /var/www/html
----
