= Centre de mise à jour

Le centre de mise à jour centralise l'ensemble des fonctions de Jeedom, et permet de mettre à jour toutes les fonctionnalités de Jeedom, incluant le logiciel de base, les plugins, les widgets, etc.

Il est accessible par le menu Administration -> Centre de mise à jour : 

Il présente, sous forme de tableau, l'ensemble des éléments installés dans Jeedom. 

En haut du tableau se trouvent les boutons de commande. Jeedom se connecte périodiquement avec le Market pour voir si des mises à jour sont disponibles (la date de dernière vérification est indiquée tout en haut du tableau, à gauche). Si vous voulez réaliser une vérification manuelle, vous pouvez appuyer sur le bouton "Vérifier les mises à jour".

Le bouton "Mettre à jour" permet de mettre à jour l'ensemble de Jeedom. On y trouve ces différentes options :

* *Sauvegarder avant* : Effectue une sauvegarde de Jeedom avant d'effectuer la mise à jour
* *Mettre à jour les plugins* : Permet d'inclure les plugins dans la mise à jour
* *Mettre à jour le core* : Permet d'inclure le noyau de Jeedom dans la mise à jour
* *Mode forcé* : met à jour Jeedom et les plugins en mode forcé c'est-à-dire que même s'il y a une erreur Jeedom continue et ne restaurera pas la sauvegarde
* *Mise à jour à réappliquer* : permet de réappliquer une mise à jour. Toutes les mises à jour ne peuvent être réappliquées.

[IMPORTANT]
Avant une mise à jour, par défaut, Jeedom va faire une sauvegarde. En cas de souci lors de l'application d'une mise à jour, Jeedom va automatiquement restaurer la sauvegarde faite juste avant. Ce principe n'est bien sûr valable que pour les mises à jour de Jeedom et non des plugins.

[TIP]
Vous pouvez forcer une mise à jour de Jeedom, même si celui-ci ne vous en propose pas.

Dans le tableau, vous retrouvez la liste des plugins sur le premier onglet "Core et plugins" et la liste des widgets et des autres élements sur l'onglet "Autre". Sur chaque ligne vous pouvez faire : 

* *Reinstaller* : force la réinstallation du plugin en question
* *Supprimer* : permet de désinstaller un élément
* *Vérifier* : vérifie si l'élément en question a une mise à jour
* *Mettre à jour* : permet de mettre à jour l'élément (si celui-ci a une mise à jour)
* *Changelog* : permet d'accéder à la liste des changements de la mise à jour

[IMPORTANT]
Si le changelog est vide mais que vous avez tout de même une mise à jour, cela signifie que c'est la documentation qui a été mise à jour. Il n'est donc pas nécessaire de demander au développeur les changements, vu qu'il n'y en a pas forcément. (c'est souvent une mise à jour de la traduction de la documentation)

[TIP]
A noter que "core : jeedom" signifie "la mise à jour du logiciel de base Jeedom".

== Mise à jour en ligne de commande

Il est possible de faire une mise à jour de Jeedom directement en SSH, voici comment faire : 

----
sudo php /var/www/html/install/update.php
----

Voilà les paramètres possibles :

* *mode* : force, pour lancer une mise à jour en mode forcé (ne tient pas compte des erreurs)
* *version* : numéro de version, pour réappliquer les changements depuis cette version

Exemple de syntaxe pour faire une mise à jour forcée en réappliquant les changements depuis la 1.188.0 : 

----
sudo php  /var/www/html/install/update.php mode=force version=1.188.0
----

Attention, après une mise à jour en ligne de commande, il faut réappliquer les droits sur le dossier Jeedom :

----
chown -R www-data:www-data /var/www/html
----
