= Utilisateur

C'est ici que l'on va pouvoir définir la liste des utilisateurs autorisés à se connecter à Jeedom, mais également leurs droits d'administrateur

Accessible par Administration -> Utilisateurs.

En haut vous avez en haut à droite un bouton pour ajouter un utilisateur et un pour sauvegarder.

En dessous vous avez un tableau :

* *Nom d'utilisateur* : le login de l'utilisateur
* *Actif* : la possibilité de désactiver le compte
* *Local seulement* : autorise la connexion de l'utilisateur que si il est en local
* *Profils* : permet de choisir le profils de l'utilisateur : 
** *Administrateur* : tous les droits sur Jeedom
** *Utilisateur* : peut voir le dashboard, les vues, les design... et agir sur les équipements/commandes, en revanche il n'aura pas accès a la configuration des commandes/équipements et de Jeedom
** *Utilisateur limité* : l'utilisateur ne voit que les équipements autorisé (configurable avec le bouton "Gerer les droits")
* *Clef API* : clef API personnelle de l'utilisateur
* *Double authentification* : indique si la double authentification est active ou non
* *Date de dernière connexion* : date de dernière connexion de l'utilisateur. Attention, ici c'est la date de connexion réelle; ainsi si vous enregistrez votre ordinateur, la date de connexion n'est pas mise à jour à chaque fois que vous y retournez.
* *Changer le mot de passe* : permet de changer le mot de passe de l'utilisateur
* *Supprimer* : permet de supprimer l'utilisateur
* *Regenerer clef API* : regenere la clef API de l'utilisateur
* *Gerer les droits* : permet de gerer finiment les droits de l'utilisateur (attention le profils doit etre en "utilisateur limité")

== Gestion des droits

Lors du clique sur "Gerer les droits" une fenetre apparait et vous permet de gerer finement les droits de l'utilisateur

[IMPORTANT]
Le profils doit etre en limité sinon aucun restriction mise ici ne marchera

Vous avez ici un trableau qui permet pour chaque équipement et chaque scénario de définir les droits de l'utilisateur : 

* *Aucun* : l'utilisateur ne voit pas l'équipement/scénario
* *Visualisation* : l'utilisateur voit l'équipement/scénario mais ne peut pas agir dessus
* *Visualisation et éxecution* : l'utilisateur voit l'équipement/scénario et peut agir dessus (allumé une lampe, lancer le scénario...)
