= Vues

Les vues permettent de créer un affichage personnalisé simple. Ce n'est pas aussi puissant que les designs, mais cela permet en quelques minutes d'avoir un affichage plus personnalisé.

Les vues sont accessibles à partir du menu Accueil -> Vue : 

[TIP]
Il est possible d'aller directement sur une vue grâce au sous-menu.

[TIP]
Dans votre profil, vous pouvez choisir la vue par défaut lors du clic sur le menu des vues.

== Les vues

On peut mettre aussi bien des widgets, des graphiques (qui peuvent être composés de plusieurs données) ou des zones tableaux (qui contiennent les widgets des commandes)

Sur cette page, en haut à gauche, on retrouve un bouton pour montrer ou masquer la liste des vues ainsi que le bouton pour en ajouter une (Jeedom vous demandera son nom et vous enverra sur la page d'édition) : 

[TIP]
Dans votre profil, vous pouvez modifier cette option pour que la liste des vues soit visible par défaut.

En haut à droite, deux options d'édition sont disponibles :

* *L'icône "crayon"* : Permet d'effectuer une édition simple de la page actuelle. Il est alors possible de déplacer et redimensionner les widgets, ainsi que de changer l'ordre de leurs commandes.
* *Edition complète* : Permet d'accéder à l'édition complète des vues, celle que vous aviez utilisé pour créer les premières déjà présentes.

== Ajout/Edition d'une vue

Une vue est composée de zones (on peut en mettre autant que l'on veut). Chaque zone est de type graphique, widget ou tableau. En fonction du type, vous pourrez y mettre des widgets d'équipement, de commande ou des graphiques.

[TIP]
Il est possible de déplacer l'ordre des zones par glisser/déposer.

Sur la gauche de la page on retrouve la liste des vues ainsi qu'un bouton pour créer une nouvelle vue. Le champs *Rechercher* permet de filtrer les vues que vous avez déjà créées.

Au centre se trouve un bouton pour renommer une vue et un autre pour changer son icône.

A droite, vous trouverez un bouton pour ajouter une zone, un autre pour voir le résultat (ou pour sortir du mode édition), un pour enregistrer les changements effectués et un dernier pour supprimer la vue.

Après avoir cliqué sur le bouton d'ajout de zone, Jeedom vous demandera son nom et son type.

Sur chaque zone vous avez les options générales suivantes : 

* *Largeur* : définit la largeur de la zone (en mode desktop seulement)
* *Editer* : permet de changer le nom de la zone
* *Supprimer* : permet de supprimer la zone

=== Zone de type widget

Une zone de type widget permet d'ajouter des widgets, un bouton supplémentaire est disponible : 

* *Ajouter widget* : permet d'ajouter un widget à la zone. Une fenêtre vous demandera de sélectionner l'équipement concerné.

[TIP]
Vous pouvez supprimer un widget directement en cliquant sur la poubelle devant celui-ci.

[TIP]
Il est possible de modifier l'ordre des widgets dans la zone par glisser/déposer.

=== Zone de type graphique

Une zone de type graphique permet d'ajouter des graphiques à votre vue, elle possède les options suivantes : 

* *Période* : permet de choisir la période d'affichage des graphiques (30 min, 1 jour, 1 semaine, 1 mois, 1 année ou tout)
* *Ajouter courbe* : permet d'ajouter/modifier des graphiques

Quand vous pressez le bouton "Ajouter courbe" jeedom affichera la liste des commandes historisées et vous pouvez choisir celle à ajouter, une fois cela fait vous avez accès aux options suivantes : 

* *Poubelle* : supprime la commande du graphique
* *Nom* : nom de la commande graphée
* *Couleur* : couleur de la courbe
* *Type* : type de la courbe
* *Groupement* : permet de grouper les données (type maximum par jour)
* *Echelle* : échelle (droite ou gauche) de la courbe
* *Escalier* : affiche la courbe en escalier
* *Empiler* : empile la courbe avec les autres courbes de type empiler
* *Variation* : graphe seulement les variations avec la valeur précédente

[TIP]
Il est possible de modifier l'ordre des graphiques dans la zone par glisser/déposer.
 
=== Zone de type tableau

Vous avez ici les boutons : 

* *Ajouter colonne* : permet d'ajouter une ligne au tableau
* *Ajouter ligne* : permet d'ajouter une colonne au tableau

[NOTE]
Il est possible de réorganiser les lignes par glisser/déposer mais pas les colonnes.

Une fois que vous avez ajoutez vos lignes/colonnes vous pouvez ajouter des informations dans les cases : 

* *texte* : juste du texte à écrire
* *html* : n'importe quel code html (javascript possible mais fortement déconseillé)
* *widget de commande* : le bouton à droite vous permet de choisir la commande à afficher (attention cela affiche le widget de la commande)

[TIP]
Vous pouvez utiliser les boutons "poubelle" pour supprimer une ligne ou une colonne entière.
