<?php include 'header.phtml'; ?>
<div id="div_alertMessage" class="alert alert-warning" style="margin:15px;">';
<center style="font-size:1.2em;"><i class="fa fa-spinner fa-spin"></i> The installation jeedom is ongoing.</center>';
</div>';
<pre id="pre_installLog" style="margin:15px;"></pre>
<script>
    function loadLog(){
        $( "#pre_installLog" ).load( "setup.php?log=1&key=<?php echo $tmp_key ?>", function(data) {
            if(data.indexOf('[END INSTALL SUCCESS]') > 0){
                $('#div_alertMessage').removeClass('alert-warning').addClass('alert-success').html('<center style="font-size:1.2em;"><i class="fas fa-check"></i> Jeedom successfully install. Login is <strong>admin</strong>, password is <strong>admin</strong>. Click <a href="/index.php">here</a> for connection</center>');
                return;
            }
            if(data.indexOf('[END INSTALL ERROR]') > 0){
                $('#div_alertMessage').removeClass('alert-warning').addClass('alert-danger').html('<center style="font-size:1.2em;"><i class="fas fa-times"></i> Error on installation, please read the log.</center>');
                return;
            }
            setTimeout(function(){ loadLog(); }, 1000);
        });
    }
    loadLog();
</script>
<?php include 'footer.phtml'; ?>