= Objet

Le sous-menu Objets, permet de définir l'arborescence de sa domotique. Elle se fait en créant des objets. Accessible à partir du menu Outils -> Objets

Pour laisser libre choix à la personnalisation, vous pouvez nommer ces objets comme vous le voulez. Mais dans la plupart des cas on y définira les différentes parties de sa maison, comme le nom des pièces (c'est d'ailleurs la configuration recommandée).

== Configuration

=== Objet

A partir de là vous avez différentes options : 

* *Nom de l'objet* : le nom de votre objet
* *Père* : l'objet père de l'objet courant, cela permet de définir une hiérarchie type, le salon est le fils de l'appartement. Un objet ne peut avoir qu'un seul père mais il peut avoir autant de fils qu'il le veut.
* *Visible* : permet de définir si cet objet est visible sur le dashboard ou non
* *Masquer sur le dashboard* : permet de masquer l'objet sur le dashboard mais le conserve dans la liste, cela permet donc de l'afficher mais que si explicitement demandée
* *Icône* : vous permet de choisir une icône pour votre objet
* *Couleur du tag* : permet de choisir la couleur de l'objet (cette couleur est par exemple utilisée sur la page de résumé domotique)
* *Couleur du texte du tag* : permet de choisir la couleur du texte de l'objet (cette couleur est par exemple utilisée sur la page de résumé domotique)
* *Taille sur le dashboard (1 à 12)* : indique la largeur que la "carré" objet prend sur le dashboard. Si vous mettez 6 à 2 objets qui se suivent alors il seront cote à cote sur l'objet

=== Résumé

Cette partie vous permet de configurer les résumé des objets en leur affectant les commandes correspondante 

[INFO]
Les résumés sont des informations global à l'objet s'affichant sur le dashboard en face du nom de celui-ci, ou si il est global en haut dans la barre de menu de Jeedom. A noter que vous pouvez lier les résumé à une commande virtuel pour pouvoir historiser celui-ci ou faire des scénarios dessus

[NOTE]
Vous pouvez ajouter des résumés en allant dans la configuration de Jeedom (voir documentation sur l'administration de Jeedom)

==== Général

Ici vous indiquer pour chaque résumé si celui-ci doit remonter en global ou non. Vous pouvez aussi décider de l'affichage en mobile/desktop ou non de certain résumé

==== Commandes

C'est ici que vous ajouter les commandes pour le calcul des résumés (la méthode de calcul étant elle configuré dans l'administration de Jeedom)

== Vue d'ensemble

La vue d'ensemble vous permet d'avoir une vue global de la configuration des objets dans Jeedom : 

* *ID* : ID de l'objet
* *Objet* : Nom de l'objet
* *Père* : Nom de l'objet père
* *Visible* : visible ou non
* *Masqué sur le dashboard* : maqué ou non sur le dashboard
* *Résumé Défini* : indique le nombre de commande par résumé ainsi que si il est global (bleu) ou non
* *Résumé Dashboard Masqué* : indique les résumé masqué sur le dashboard
* *Résumé Mobile Masqué* : indique les résumé masqué sur le mobile