= Plugins

Le sous-menu Plugins, permet de gérer ses plugins, à savoir : les télécharger, les mettre à jour et les activer.

== Gestion des plugins

Vous pouvez accéder à la page plugins à partir de Plugins -> Gestion des plugins. Une fois que l'on clique dessus on retrouve la page qui nous présente la liste des plugins. 

[TIP]
Comme à beaucoup d'endroits sur Jeedom, mettre la souris tout à gauche permet de faire apparaître un menu d'accès rapide (vous pouvez à partir de votre profil le laisser toujours visible).

Sur cette page vous retrouvez tous les plugins présents sur votre Jeedom; en opaque ceux qui sont désactivés. En cliquant sur un plugin vous accèdez à sa configuration.

En haut vous retrouvez l'ID et le nom du plugin, ainsi que la version installée. En dessous vous avez le bouton d'activation/désactivation d'un plugin

[IMPORTANT]
Lors du téléchargement d'un plugin celui-ci n'est pas activé, il faut donc que vous l'activiez

Sur la droite vous retrouvez 4 boutons : 

* *Changelog* : permet de voir le changelog du plugin si il existe 
* *Envoyer sur le Market* : permet d'envoyer le plugin sur le Market (uniquement disponible si vous en êtes l'auteur)
* *Supprimer* : Supprime le plugin de votre Jeedom. Attention cela supprime définitivement tous les équipements de ce plugin aussi
* *Documentation* : Permet d'accéder directement à la page de documentation du plugin

En dessous on retrouve une zone etat avec : 

* *Statut* : permet de voir le statut du plugin (actif / inactif)
* *Version* : la version du plugin que vous possédez
* *Auteur* : l'auteur du plugin
* *Action* : Permet d'activer ou désactiver le plugin
* *Version jeedom* : Indique la version minimum requise du plugin
* *Licence* : Indique la licence du plugin qui sera généralement AGPL

A droite on retrouve la zone log qui permet de spécifier le niveau de log spécifiquement pour le plugin (on retrouve cette même possibilité dans Administatrion--> Configuration sur l'onglet logs).

Si le plugin possède des dépendances et /ou un démon on peut retrouver ces deux zones.

Dépendances :

* *Nom* : généralement sera local
* *Statut* : vous dira si les dépendances sont OK ou KO
* *Installation* : permettra d'installer ou réinstaller les dépendances (si vous ne le faites pas manuellement et qu'elles sont KO jeedom se chargera de lui même au bout d'un moment de le faire)
* *Dernière installation* : date de la dernière installation des dépendances

Démon :

* *Nom* : généralement sera local
* *Statut* : vous dira si le démon est OK ou KO
* *Configuration* : sera OK si tous les critères pour que le démon tourne sont réunis ou donnera la cause du blocage
* *(Re)Démarrer* : permet de lancer ou relancer le démon
* *Arrêter* : permet d'arrêter le démon (que dans le cas ou la gestion automatique est désactivée
* *Gestion automatique* : permet d'activer ou désactiver la gestion automatique (ce qui permet à jeedom de gérer lui même le démon et le relancer si besoin, sauf contre indications il est conseiller de laisser la gestion automatique active)
* *Dernièr lancement* : date du dernier lancement du démon

[TIP]
Certains plugins ont une partie configuration, il faut dans ce cas se référer à la doc du plugin en question pour savoir comment le configurer (si tel est le cas elle apparaitra ici)

En dessous on retrouve une zone fonctionnalités. Celle-ci permet de voir si le plugin utilise ou non une des fonctions cores Jeedom tel que :

* *Interact* : des interactions spécifiques
* *Cron* : un cron à la minute
* *Cron5* : un cron toutes les 5 minutes
* *Cron15* : toutes les 15 minutes
* *Cron30* : toutes les 30 minutes
* *CronHourly* : toutes les heures
* *CronDaily* : journalier

[TIP]
Si le plugin utilise une de ces fonctions. Vous pourrez spécifiquement lui interdire de le faire en décochant la case "activer" qui sera présente à côté.

Enfin on peut retrouver un section Panel qui permettra d'activer ou désactiver l'affichage du panel sur le dashboard ou en mobile si le plugin en propose un.


== Installation d'un plugin

Pour installer un nouveau plugin il suffit de cliquer sur le bouton "Market". Après un petit temps de chargement vous obtiendrez la page.

Tout en haut comme sur le Market vous avez des filtres : 

* *Gratuit/Payant* : permet de ne filtrer que sur les gratuits ou les payants, la petite croix permet de réinitialiser le filtre
* *Officiel/Conseillé* : permet d'afficher les plugins officiels ou les conseillés uniquement
* *Installé/Non installé* : permet de n'afficher que les plugins installés ou non, la petite croix permet de réinitialiser le filtre
* *Menu déroulant Catégorie* : permet de n'afficher que certaines catégories de plugins
* *Rechercher* : permet de rechercher un plugin (dans le nom ou la description de celui-ci)
* *Nom d'utilisateur* : affiche le nom d'utilisateur utilisé pour la connexion au Market ainsi que le statut de la connexion (ici ok)

Un fois le plugin voulu trouvé il suffit de cliquer sur celui-ci pour faire apparaître la fiche du plugin.

Cette fiche vous donne beaucoup d'informations sur le plugin, entre autre : 

* S'il est officiel/recommandé ou s'il est obsolète (il faut vraiment éviter d'installer des plugins obsolètes)
* 4 actions : 
** *Installer stable* : permet d'installer le plugin dans sa version stable
** *Installer beta* : permet d'installer le plugin dans sa version beta (seulement pour les betatesteurs)
** *Installer pro* : permet d'installer la version pro (très peu utilisé)
** *Supprimer* : si le plugin est actuellement installé, ce bouton permet de le supprimer

En dessous vous retrouvez la description du plugin, la compatibilité (si Jeedom détecte une incompatibilité il vous le signalera), les avis sur le plugin (vous pouvez ici le noter) et des informations complémentaires (l'auteur, la personne ayant fait la dernière mise à jour, un lien vers la doc, le nombre de téléchargements).
Sur la droite vous retrouvez la liste des dernières mises à jour (un bouton tout voir vous permet d'avoir tout l'historique), une documentation rapide d'utilisation (il est recommandé quand même de lire la documentation complète) et enfin le type (plugin, widget...), la langue et les diverses informations sur la date de la dernière stable.

[IMPORTANT]
Il n'est vraiment pas recommandé de mettre un plugin beta sur un Jeedom non beta, beaucoup de soucis de fonctionnement peuvent en résulter.

[IMPORTANT]
Certains plugins sont payants, dans ce cas la fiche du plugin vous proposera de l'acheter, une fois cela fait il faut attendre une dizaine de minutes (temps de validation du paiement), puis retourner sur la fiche du plugin pour l'installer normalement.

[TIP]
Vous pouvez aussi ajouter un plugin à Jeedom à partir d'un fichier ou depuis un dépôt Github. Pour cela, il faut, dans la configuration de Jeedom, activer la fonction adéquate dans la partie "Mises à jour et fichiers". Il sera ensuite possible, en mettant la souris tout à gauche, et en faisant apparaitre le menu de la page plugin, de cliquer sur "Ajout depuis une autre source". Vous pourrez ensuite choisir la source "Fichier". Attention, dans le cas de l'ajout par un fichier zip, le nom du zip doit être le même que l'id du plugin et dès l'ouverture du ZIP un dossier plugin_info doit être présent.