= Profils

La page profils vous permet de configurer certains comportements de Jeedom spécifiques à l'utilisateur : page d'accueil, thèmes de la version desktop, de la version mobile, des graphiques... Elle permet aussi de changer votre mot de passe et de passer en mode expert permettant une configuration plus poussée de Jeedom.

Vous retrouvez en haut à droite en cliquant sur le l'icone bonhomme puis profils

== Thèmes

Le panneau thèmes vous permet de régler des paramètres d'interface : 

* *Desktop* : thèmes à utiliser en mode desktop, attention seul le thème par défaut est officiellement supporté par Jeedom
* *Mobile couleur* : permet de choisir la couleur de l'interface (ici tout est supporté)
* *Graphique Desktop* : permet de définir le thème par défaut des graphiques en mode desktop
* *Graphique Mobile* : permet de définir le thème par défaut des graphiques en mode mobile
* *Opacité par des widgets Dashboard* : permet de donner l'opacité (entre 0 et 1) des widgets sur le dashboard
* *Opacité par des widgets Design* : permet de donner l'opacité (entre 0 et 1) des widgets sur les designs
* *Opacité par des widgets Vue* : permet de donner l'opacité (entre 0 et 1) des widgets sur les vues
* *Opacité par des widgets Mobile* : permet de donner l'opacité (entre 0 et 1) des widgets en mobile

=== Interface

Vous permet de définir certains comportements de l'interface :

* *Général*
** *Afficher les menus* : indique à Jeedom d'afficher le panneau de gauche, lorsqu'il existe, pour rappel ce panneau est disponible sur la plupart des pages des plugins, ainsi que la page des scénarios, des interactions, des objets....
* *Page par défaut*
** *Desktop* : page par défaut à afficher lors de la connexion en desktop
** *Mobile* : page par défaut à afficher lors de la connexion en mobile
* *Objet par défaut sur le dashboard* : objet à afficher par défaut lors de l'arrivée sur le dashboard
* *Vue par défaut* : vue à afficher par défaut lors de l'arrivée sur le dashboard
* *Design par défaut* : design à afficher par défaut lors de l'arrivée sur le dashboard
** *Plein écran* : affichage par défaut en plein écran lors de l'arrivée sur les designs
* *Dashboard*
** *Déplier le panneau des scénarios* : permet de rendre visible par défaut le menu des scénarios (à droite) sur le dashboard
** *Déplier le panneau des objets* : permet de rendre visible par défaut le menu des objets (à gauche) sur le dashboard
* *Vue*
** *Déplier le panneau des vues* : permet de rendre visible par défaut le menu des vues (à gauche) sur les vues

=== Sécurité

* *Authentification en 2 étapes* : permet de configurer l'authentification en 2 étape (pour rappels c'est un code changeant toute les XX secondes qui s'affiche sur une application mobile, type google authentificator)
* *Mot de passe* : permet de changer votre mot de passe (ne pas oublier de le retaper en dessous)
* *Hash de l'utilisateur* : votre clef api d'utilisateur

=== Notifications

* *Commande de notification utilisateur* : Commande par défaut pour vous joindre (commande de type message)