name: translate

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - uses: jeedom/jeetranslate@main
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          include_empty_translation: false
          target_languages: "en_US,es_ES,de_DE,it_IT,pt_PT"
          use_core_translations: false