name: Update PHPStan baseline

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'
        default: 'Manual launch'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-baseline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate new baseline
        run: vendor/bin/phpstan analyse --configuration phpstan.neon --generate-baseline --error-format=github

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: '[skip ci] Update PHPStan baseline'
          title: '[CI] Update PHPStan baseline'
          body: |
            Automatic update of the PHPStan baseline following error fixes.

            This PR was automatically generated by the Update PHPStan baseline workflow.
          branch: update-phpstan-baseline
          base: develop
          delete-branch: true
          add-paths: |
            phpstan-baseline.neon
          reviewers: |
            zoic21
            Hotfirenet
            Salvialf
            Sekiro-kost
            reineabs
            Mips2648
